package onkimport

import (
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/1homsi/onekit/internal/onklang"
)

const (
	protoEmptyType = "google.protobuf.Empty"
	methodPatch    = "patch"
	methodPost     = "post"
	methodPut      = "put"
)

var protoScalars = map[string]string{
	"double": "float64", "float": "float32",
	"int32": "int32", "sint32": "int32", "sfixed32": "int32",
	"int64": "int64", "sint64": "int64", "sfixed64": "int64",
	"uint32": "uint32", "fixed32": "uint32",
	"uint64": "uint64", "fixed64": "uint64",
	"bool": "bool", "string": "string", "bytes": "bytes",
}

var protoWrappers = map[string]string{
	"google.protobuf.StringValue": "string", "google.protobuf.BoolValue": "bool",
	"google.protobuf.Int32Value": "int32", "google.protobuf.Int64Value": "int64",
	"google.protobuf.UInt32Value": "uint32", "google.protobuf.UInt64Value": "uint64",
	"google.protobuf.FloatValue": "float32", "google.protobuf.DoubleValue": "float64",
	"google.protobuf.BytesValue": "bytes",
}

type protoDecl struct {
	onkName string
	isEnum  bool
}

type protoImporter struct {
	file     *protoFile
	opts     Options
	warnings []string
	decls    map[string]protoDecl
	used     map[string]bool
	emptyMsg string
	oneofs   bool
	out      strings.Builder

	queryFields map[string]map[string]bool
	requestUse  map[string]string
}

var protoPathParam = regexp.MustCompile(`\{([^{}=]+)(=[^{}]*)?\}`)

// ImportProto converts a .proto file (proto3, with the proto2 constructs that
// matter for APIs) into .onk source. It has no dependency on protobuf tooling:
// messages, enums, oneofs, maps, services, google.api.http bindings, and
// server-streaming RPCs are carried over; everything it cannot express is
// reported in Warnings rather than dropped silently.
func ImportProto(data []byte, opts Options) (*Result, error) {
	file, err := parseProto(string(data))
	if err != nil {
		return nil, err
	}
	if len(file.messages) == 0 && len(file.enums) == 0 && len(file.services) == 0 {
		return nil, errors.New("proto: the file declares no messages, enums or services")
	}
	pkg := opts.Package
	if pkg == "" {
		pkg = file.pkg
	}
	if pkg == "" {
		pkg = "api"
	}
	im := &protoImporter{
		file:        file,
		opts:        Options{Package: pkg},
		decls:       map[string]protoDecl{},
		used:        map[string]bool{},
		queryFields: map[string]map[string]bool{},
		requestUse:  map[string]string{},
	}
	for _, imp := range file.imports {
		if !strings.HasPrefix(imp, "google/protobuf/") && !strings.HasPrefix(imp, "google/api/") {
			im.warnf("import %q is not followed; types declared there become json fields", imp)
		}
	}
	im.declare()
	services := im.renderServices()
	im.renderDecls()
	im.out.WriteString(services)
	source := "// Code generated by onek import; re-run import instead of editing.\npackage " + pkg + "\n\n" + im.out.String()
	formatted, err := onklang.Format(source)
	if err != nil {
		return nil, fmt.Errorf("internal: imported proto does not format: %w\n%s", err, source)
	}
	return &Result{Source: formatted, Package: pkg, Warnings: im.warnings}, nil
}

func (im *protoImporter) warnf(format string, args ...any) {
	im.warnings = append(im.warnings, fmt.Sprintf(format, args...))
}

func (im *protoImporter) unique(name string) string {
	candidate := name
	for n := 2; im.used[candidate]; n++ {
		candidate = fmt.Sprintf("%s%d", name, n)
	}
	if candidate != name {
		im.warnf("%s was renamed to %s to keep every declaration name unique", name, candidate)
	}
	im.used[candidate] = true
	return candidate
}

func (im *protoImporter) declare() {
	prefix := im.file.pkg
	var walkEnum func(scope string, parents []string, e *protoEnum)
	var walkMessage func(scope string, parents []string, m *protoMessage)
	walkEnum = func(scope string, parents []string, e *protoEnum) {
		qualified := join(scope, e.name)
		im.decls[qualified] = protoDecl{onkName: im.unique(pascalIdent(strings.Join(append(append([]string{}, parents...), e.name), ""))), isEnum: true}
	}
	walkMessage = func(scope string, parents []string, m *protoMessage) {
		qualified := join(scope, m.name)
		im.decls[qualified] = protoDecl{onkName: im.unique(pascalIdent(strings.Join(append(append([]string{}, parents...), m.name), "")))}
		inner := append(append([]string{}, parents...), m.name)
		for _, nested := range m.nested {
			walkMessage(qualified, inner, nested)
		}
		for _, e := range m.enums {
			walkEnum(qualified, inner, e)
		}
	}
	for _, m := range im.file.messages {
		walkMessage(prefix, nil, m)
	}
	for _, e := range im.file.enums {
		walkEnum(prefix, nil, e)
	}
}

func join(scope, name string) string {
	if scope == "" {
		return name
	}
	return scope + "." + name
}

func (im *protoImporter) lookup(scope, ref string) (protoDecl, bool) {
	if strings.HasPrefix(ref, ".") {
		decl, ok := im.decls[strings.TrimPrefix(ref, ".")]
		return decl, ok
	}
	for {
		if decl, ok := im.decls[join(scope, ref)]; ok {
			return decl, true
		}
		if scope == "" {
			return protoDecl{}, false
		}
		if idx := strings.LastIndex(scope, "."); idx >= 0 {
			scope = scope[:idx]
		} else {
			scope = ""
		}
	}
}

func (im *protoImporter) empty() string {
	if im.emptyMsg == "" {
		im.emptyMsg = im.unique("Empty")
	}
	return im.emptyMsg
}

func (im *protoImporter) typeExpr(scope, ref, context string) (string, bool) {
	if scalar, ok := protoScalars[ref]; ok {
		return scalar, false
	}
	full := strings.TrimPrefix(ref, ".")
	if wrapped, ok := protoWrappers[full]; ok {
		return wrapped, true
	}
	switch full {
	case "google.protobuf.Timestamp":
		return "timestamp", false
	case "google.protobuf.Duration":
		im.warnf("%s: google.protobuf.Duration has no onekit equivalent and became a string such as \"3.5s\"", context)
		return "string", false
	case protoEmptyType:
		return im.empty(), false
	case "google.protobuf.Struct", "google.protobuf.Value", "google.protobuf.ListValue":
		return scalarJSON, false
	case "google.protobuf.Any":
		im.warnf("%s: google.protobuf.Any became an untyped json value", context)
		return scalarJSON, false
	case "google.protobuf.FieldMask":
		im.warnf("%s: google.protobuf.FieldMask became a string", context)
		return "string", false
	}
	if decl, ok := im.lookup(scope, ref); ok {
		return decl.onkName, false
	}
	im.warnf("%s: type %q is not declared in this file; it became an untyped json value", context, ref)
	return scalarJSON, false
}

func (im *protoImporter) renderDecls() {
	var decls strings.Builder
	var walkMessage func(scope string, m *protoMessage)
	walkEnum := func(scope string, e *protoEnum) {
		decl := im.decls[join(scope, e.name)]
		if len(e.values) == 0 {
			im.warnf("enum %s has no values and was skipped", e.name)
			return
		}
		decls.WriteString(docBlock(e.doc, ""))
		decls.WriteString("enum " + decl.onkName + " {\n")
		for _, v := range e.values {
			decls.WriteString(docBlock(v.doc, "  "))
			decls.WriteString("  " + safeIdent(v.name) + "\n")
		}
		decls.WriteString("}\n\n")
	}
	walkMessage = func(scope string, m *protoMessage) {
		qualified := join(scope, m.name)
		decls.WriteString(im.renderMessage(qualified, m))
		for _, nested := range m.nested {
			walkMessage(qualified, nested)
		}
		for _, e := range m.enums {
			walkEnum(qualified, e)
		}
	}
	for _, m := range im.file.messages {
		walkMessage(im.file.pkg, m)
	}
	for _, e := range im.file.enums {
		walkEnum(im.file.pkg, e)
	}
	if im.emptyMsg != "" {
		decls.WriteString("message " + im.emptyMsg + " {}\n\n")
	}
	im.out.WriteString(decls.String())
}

func docBlock(doc, indent string) string {
	doc = strings.TrimSpace(doc)
	if doc == "" {
		return ""
	}
	var b strings.Builder
	for _, line := range strings.Split(doc, "\n") {
		b.WriteString(indent + "/// " + strings.TrimSpace(line) + "\n")
	}
	return b.String()
}

func (im *protoImporter) renderMessage(qualified string, m *protoMessage) string {
	decl := im.decls[qualified]
	var b strings.Builder
	b.WriteString(docBlock(m.doc, ""))
	b.WriteString("message " + decl.onkName + " {\n")
	seen := map[string]bool{}
	for i := 0; i < len(m.fields); i++ {
		field := m.fields[i]
		name := safeIdent(field.name)
		if name != field.name {
			im.warnf("%s.%s: field renamed to %s", m.name, field.name, name)
		}
		if seen[name] {
			im.warnf("%s.%s: duplicate field name after conversion; skipped", m.name, field.name)
			continue
		}
		seen[name] = true
		if field.oneof != "" {
			group := []*protoField{field}
			for i+1 < len(m.fields) && m.fields[i+1].oneof == field.oneof {
				i++
				group = append(group, m.fields[i])
			}
			b.WriteString(im.renderOneof(qualified, m, field.oneof, group))
			continue
		}
		b.WriteString(docBlock(field.doc, "  "))
		b.WriteString("  " + name + ": " + im.fieldType(qualified, m, field) + im.fieldDecorators(decl.onkName, field) + "\n")
	}
	b.WriteString("}\n\n")
	return b.String()
}

func (im *protoImporter) fieldType(scope string, m *protoMessage, f *protoField) string {
	context := m.name + "." + f.name
	if f.mapKey != "" {
		if _, ok := protoScalars[f.mapKey]; !ok || f.mapKey == "bytes" || f.mapKey == "float" || f.mapKey == "double" {
			im.warnf("%s: map keys must be strings, integers or bools; the key type %q was treated as a string", context, f.mapKey)
		}
		value, _ := im.typeExpr(scope, f.mapValue, context)
		return "map[string, " + value + "]"
	}
	typ, wrapped := im.typeExpr(scope, f.typ, context)
	switch {
	case f.repeated:
		return typ + "[]"
	case f.optional || wrapped:
		return typ + "?"
	}
	return typ
}

func (im *protoImporter) fieldDecorators(message string, f *protoField) string {
	var parts []string
	if im.queryFields[message][f.name] {
		parts = append(parts, "@query")
	}
	if f.deprecated {
		parts = append(parts, "@deprecated")
	}
	if len(parts) == 0 {
		return ""
	}
	return " " + strings.Join(parts, " ")
}

func (im *protoImporter) renderOneof(scope string, m *protoMessage, name string, fields []*protoField) string {
	if !im.oneofs {
		im.oneofs = true
		im.warnf("oneofs use onekit's discriminated encoding ({\"type\": ..., \"<field>\": ...}), which differs from protobuf JSON, where the set field's name is the key")
	}
	var b strings.Builder
	b.WriteString("  " + safeIdent(name) + ": oneof(discriminator: \"type\") {\n")
	for _, f := range fields {
		typ, _ := im.typeExpr(scope, f.typ, m.name+"."+f.name)
		b.WriteString(docBlock(f.doc, "    "))
		b.WriteString("    " + safeIdent(f.name) + ": " + typ + " @tag(\"" + f.name + "\")\n")
	}
	b.WriteString("  }\n")
	return b.String()
}

func (im *protoImporter) findMessage(scope, ref string) (*protoMessage, string, bool) {
	decl, ok := im.lookup(scope, ref)
	if !ok || decl.isEnum {
		return nil, "", false
	}
	var found *protoMessage
	var walk func(prefix string, m *protoMessage)
	walk = func(prefix string, m *protoMessage) {
		qualified := join(prefix, m.name)
		if im.decls[qualified] == decl {
			found = m
		}
		for _, nested := range m.nested {
			walk(qualified, nested)
		}
	}
	for _, m := range im.file.messages {
		walk(im.file.pkg, m)
	}
	return found, decl.onkName, found != nil
}

func lowerFirst(name string) string {
	if name == "" {
		return name
	}
	return strings.ToLower(name[:1]) + name[1:]
}

func isScalarField(f *protoField) bool {
	if f.mapKey != "" {
		return false
	}
	if _, ok := protoScalars[f.typ]; ok {
		return true
	}
	return false
}

func (im *protoImporter) renderServices() string {
	var b strings.Builder
	for _, service := range im.file.services {
		name := im.unique(pascalIdent(service.name))
		b.WriteString(docBlock(service.doc, ""))
		b.WriteString("service " + name + " {\n")
		first := true
		for _, method := range service.methods {
			line := im.renderMethod(service, method)
			if line == "" {
				continue
			}
			if !first {
				b.WriteString("\n")
			}
			first = false
			b.WriteString(line)
		}
		b.WriteString("}\n\n")
	}
	return b.String()
}

func (im *protoImporter) renderMethod(service *protoService, method *protoMethod) string {
	context := service.name + "." + method.name
	if method.clientStream {
		im.warnf("%s: client and bidirectional streaming have no HTTP mapping and the RPC was skipped", context)
		return ""
	}
	scope := im.file.pkg
	reqMsg, reqName, ok := im.findMessage(scope, method.request)
	var request string
	switch {
	case ok:
		request = reqName
	case strings.TrimPrefix(method.request, ".") == protoEmptyType:
		request = im.empty()
	default:
		im.warnf("%s: request type %q is not a message declared in this file; the RPC was skipped", context, method.request)
		return ""
	}
	var response string
	if _, name, found := im.findMessage(scope, method.response); found {
		response = name
	} else if strings.TrimPrefix(method.response, ".") == protoEmptyType {
		response = im.empty()
	} else {
		im.warnf("%s: response type %q is not a message declared in this file; the RPC was skipped", context, method.response)
		return ""
	}
	verb, route, body := im.binding(service, method)
	pathFields := map[string]bool{}
	if route != "" {
		for _, match := range protoPathParam.FindAllStringSubmatch(route, -1) {
			if match[2] != "" {
				im.warnf("%s: path template %q lost its pattern; only the field name was kept", context, match[0])
			}
			pathFields[match[1]] = true
		}
		route = protoPathParam.ReplaceAllString(route, "{$1}")
	}
	for field := range pathFields {
		var target *protoField
		if reqMsg != nil {
			for _, candidate := range reqMsg.fields {
				if candidate.name == field {
					target = candidate
				}
			}
		}
		if target == nil || !isScalarField(target) || target.repeated {
			im.warnf("%s: path parameter %q is not a top-level scalar field of %s; the RPC was skipped", context, field, method.request)
			return ""
		}
	}
	bodyVerb := verb == methodPost || verb == methodPut || verb == methodPatch
	stream := method.serverStream
	if stream && bodyVerb {
		im.warnf("%s: server streaming needs a GET binding; %s %s was changed to GET and the request fields became query parameters", context, strings.ToUpper(verb), route)
		verb, body, bodyVerb = "get", "", false
	}
	if !bodyVerb && body != "" {
		im.warnf("%s: a request body is not supported on %s; \"body: %s\" was ignored", context, strings.ToUpper(verb), body)
		body = ""
	}
	if !bodyVerb && reqMsg != nil {
		im.markQuery(context, reqName, reqMsg, pathFields)
	}
	if bodyVerb && body != "" && body != "*" {
		found := false
		for _, f := range reqMsg.fields {
			if f.name == body {
				found = true
			}
		}
		if !found {
			im.warnf("%s: body field %q is not declared on %s; the RPC was skipped", context, body, method.request)
			return ""
		}
	}
	var b strings.Builder
	b.WriteString(docBlock(method.doc, "  "))
	b.WriteString("  " + lowerFirst(pascalIdent(method.name)) + "(" + request + ") -> " + response)
	if bodyVerb && body != "" && body != "*" {
		b.WriteString(" @body(\"" + body + "\")")
	}
	b.WriteString(" @" + verb + "(\"" + route + "\")")
	if stream {
		b.WriteString(" @stream")
	}
	if method.deprecated {
		b.WriteString(" @deprecated")
	}
	b.WriteString("\n")
	return b.String()
}

func (im *protoImporter) binding(service *protoService, method *protoMethod) (string, string, string) {
	if rule := method.http; rule != nil && rule.verb != "" {
		return rule.verb, rule.path, rule.body
	}
	path := "/" + service.name + "/" + method.name
	if im.file.pkg != "" {
		path = "/" + im.file.pkg + "." + service.name + "/" + method.name
	}
	return methodPost, path, "*"
}

func (im *protoImporter) markQuery(context, name string, msg *protoMessage, pathFields map[string]bool) {
	keys := make([]string, 0, len(pathFields))
	for field := range pathFields {
		keys = append(keys, field)
	}
	sort.Strings(keys)
	binding := strings.Join(keys, ",")
	if previous, ok := im.requestUse[name]; ok && previous != binding {
		im.warnf("%s: request message %s is shared by RPCs with different HTTP bindings; its query parameters follow the first one", context, msg.name)
		return
	}
	im.requestUse[name] = binding
	if im.queryFields[name] == nil {
		im.queryFields[name] = map[string]bool{}
	}
	for _, f := range msg.fields {
		if pathFields[f.name] || f.oneof != "" {
			if f.oneof != "" {
				im.warnf("%s: oneof field %q cannot be sent as a query parameter and is not sent", context, f.name)
			}
			continue
		}
		if isScalarField(f) {
			im.queryFields[name][f.name] = true
			continue
		}
		im.warnf("%s: field %q (%s) cannot be sent as a query parameter and is not sent", context, f.name, describeProtoField(f))
	}
}

func describeProtoField(f *protoField) string {
	switch {
	case f.mapKey != "":
		return "map"
	case f.repeated:
		return "repeated " + f.typ
	}
	return f.typ
}
