// Code generated by onek. DO NOT EDIT.

import 'package:web_socket_channel/io.dart';
import 'package:web_socket_channel/web_socket_channel.dart';

Future<WebSocketChannel> onekitWsConnect(
  Uri uri,
  Map<String, String> headers,
  Duration? pingInterval,
) async {
  final channel = IOWebSocketChannel.connect(
    uri,
    headers: headers,
    pingInterval: pingInterval,
  );
  await channel.ready;
  return channel;
}
