// Code generated by onek. DO NOT EDIT.

import 'package:web_socket_channel/web_socket_channel.dart';

Future<WebSocketChannel> onekitWsConnect(
  Uri uri,
  Map<String, String> headers,
  Duration? pingInterval,
) async {
  if (headers.isNotEmpty) {
    throw UnsupportedError(
      'browsers cannot send custom headers on a WebSocket handshake',
    );
  }
  final channel = WebSocketChannel.connect(uri);
  await channel.ready;
  return channel;
}
