// Code generated by onek. DO NOT EDIT.

import 'dart:async';
import 'dart:collection';
import 'dart:convert';
import 'dart:typed_data';

import 'package:http/http.dart' as http;

const int defaultMaxResponseBodyBytes = 8 << 20;
const int defaultMaxSseLineBytes = 1 << 20;
const Duration defaultRequestTimeout = Duration(seconds: 30);

final RegExp onekitEmailPattern = RegExp(r'^[^@\s]+@[^@\s]+\.[^@\s]+$');
final RegExp onekitUuidPattern = RegExp(
  r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
);
final RegExp onekitUriPattern = RegExp(r'^[a-zA-Z][a-zA-Z0-9+.-]*://[^\s]+$');
final BigInt onekitMaxUint64 = BigInt.parse('18446744073709551615');

class RequestValidationException implements Exception {
  RequestValidationException(this.violations);

  final List<String> violations;

  @override
  String toString() => 'RequestValidationException: ${violations.join('; ')}';
}

class UnexpectedStatusException implements Exception {
  UnexpectedStatusException(this.status, this.body, this.headers);

  final int status;
  final Uint8List body;
  final Map<String, String> headers;

  String get bodyText => utf8.decode(body, allowMalformed: true);

  @override
  String toString() => 'UnexpectedStatusException: $status $bodyText';
}

class StreamException implements Exception {
  StreamException(this.payload);

  final Object? payload;

  @override
  String toString() => 'StreamException: $payload';
}

class ResponseTooLargeException implements Exception {
  ResponseTooLargeException(this.limit);

  final int limit;

  @override
  String toString() =>
      'ResponseTooLargeException: response exceeds $limit bytes';
}

class OnekitResponse {
  OnekitResponse(this.status, this.headers, this.body);

  final int status;
  final Map<String, String> headers;
  final Uint8List body;

  bool get ok => status >= 200 && status < 300;
}

void onekitCheck(List<String> violations) {
  if (violations.isNotEmpty) throw RequestValidationException(violations);
}

String onekitTrimSlash(String baseUrl) {
  var out = baseUrl;
  while (out.endsWith('/')) {
    out = out.substring(0, out.length - 1);
  }
  return out;
}

Uri onekitUri(
  String baseUrl,
  String path,
  List<MapEntry<String, String>> query,
) {
  if (query.isEmpty) return Uri.parse(baseUrl + path);
  final encoded = query
      .map(
        (e) =>
            '${Uri.encodeQueryComponent(e.key)}=${Uri.encodeQueryComponent(e.value)}',
      )
      .join('&');
  return Uri.parse('$baseUrl$path?$encoded');
}

String onekitPathValue(Object value) => Uri.encodeComponent(value.toString());

Map<String, String> onekitHeaders(
  Map<String, String> base,
  Map<String, String>? extra,
) => {...base, ...?extra};

Duration? onekitTimeout(Duration? client, Duration? call) {
  final timeout = call ?? client;
  if (timeout == null || timeout <= Duration.zero) return null;
  return timeout;
}

Future<Uint8List> onekitReadBounded(Stream<List<int>> stream, int limit) async {
  final max = limit > 0 ? limit : defaultMaxResponseBodyBytes;
  final builder = BytesBuilder(copy: false);
  await for (final chunk in stream) {
    builder.add(chunk);
    if (builder.length > max) throw ResponseTooLargeException(max);
  }
  return builder.takeBytes();
}

Future<OnekitResponse> onekitSend(
  http.Client client,
  http.BaseRequest request,
  Duration? timeout,
  int maxBodyBytes,
) {
  Future<OnekitResponse> run() async {
    final response = await client.send(request);
    final body = await onekitReadBounded(response.stream, maxBodyBytes);
    return OnekitResponse(response.statusCode, response.headers, body);
  }

  return timeout == null ? run() : run().timeout(timeout);
}

Object? onekitDecodeBody(Uint8List body) {
  final text = utf8.decode(body);
  if (text.trim().isEmpty) return const <String, dynamic>{};
  return jsonDecode(text);
}

Object? onekitTryJson(Uint8List body) {
  try {
    return jsonDecode(utf8.decode(body));
  } on FormatException {
    return null;
  }
}

Map<String, dynamic> onekitObject(Object? value) {
  if (value == null) return <String, dynamic>{};
  if (value is Map<String, dynamic>) return value;
  if (value is Map) return value.map((k, v) => MapEntry(k.toString(), v));
  throw FormatException('expected a JSON object, got ${value.runtimeType}');
}

String onekitString(Object? value) {
  if (value is String) return value;
  throw FormatException('expected a string, got ${value.runtimeType}');
}

bool onekitBool(Object? value) {
  if (value is bool) return value;
  throw FormatException('expected a boolean, got ${value.runtimeType}');
}

int onekitInt(Object? value) {
  if (value is int) return value;
  if (value is double && value == value.truncateToDouble())
    return value.toInt();
  if (value is String) return int.parse(value);
  throw FormatException('expected an integer, got ${value.runtimeType}');
}

BigInt onekitBigInt(Object? value) {
  if (value is int) return BigInt.from(value);
  if (value is String) return BigInt.parse(value);
  if (value is double && value == value.truncateToDouble())
    return BigInt.from(value);
  throw FormatException('expected an integer, got ${value.runtimeType}');
}

double onekitDouble(Object? value) {
  if (value is num) return value.toDouble();
  if (value is String) return double.parse(value);
  throw FormatException('expected a number, got ${value.runtimeType}');
}

List<T> onekitList<T>(Object? value, T Function(Object?) decode) {
  if (value is List) return value.map(decode).toList();
  throw FormatException('expected a JSON array, got ${value.runtimeType}');
}

Map<String, T> onekitMap<T>(Object? value, T Function(Object?) decode) =>
    onekitObject(value).map((k, v) => MapEntry(k, decode(v)));

T onekitEnumByIndex<T extends Enum>(List<T> values, Object? value) {
  final index = onekitInt(value);
  if (index < 0 || index >= values.length)
    throw FormatException('enum index $index out of range');
  return values[index];
}

String onekitBytesEncode(Uint8List value, String encoding) {
  switch (encoding) {
    case 'hex':
      return value.map((b) => b.toRadixString(16).padLeft(2, '0')).join();
    case 'base64_raw':
      return base64.encode(value).replaceAll('=', '');
    case 'base64url':
      return base64Url.encode(value);
    case 'base64url_raw':
      return base64Url.encode(value).replaceAll('=', '');
    default:
      return base64.encode(value);
  }
}

Uint8List onekitBytesDecode(Object? value, String encoding) {
  final text = onekitString(value);
  switch (encoding) {
    case 'hex':
      if (text.length.isOdd)
        throw const FormatException('odd-length hex string');
      return Uint8List.fromList([
        for (var i = 0; i < text.length; i += 2)
          int.parse(text.substring(i, i + 2), radix: 16),
      ]);
    case 'base64url':
    case 'base64url_raw':
      return base64Url.decode(base64Url.normalize(text));
    default:
      return base64.decode(base64.normalize(text));
  }
}

String _two(int n) => n.toString().padLeft(2, '0');

Object onekitTimeEncode(DateTime value, String encoding) {
  final utc = value.toUtc();
  switch (encoding) {
    case 'unix_seconds':
      return utc.millisecondsSinceEpoch ~/ 1000;
    case 'unix_millis':
      return utc.millisecondsSinceEpoch;
    case 'date':
      return '${utc.year.toString().padLeft(4, '0')}-${_two(utc.month)}-${_two(utc.day)}';
    default:
      return utc.toIso8601String();
  }
}

DateTime onekitTimeDecode(Object? value, String encoding) {
  switch (encoding) {
    case 'unix_seconds':
      return DateTime.fromMillisecondsSinceEpoch(
        onekitInt(value) * 1000,
        isUtc: true,
      );
    case 'unix_millis':
      return DateTime.fromMillisecondsSinceEpoch(onekitInt(value), isUtc: true);
    case 'date':
      return DateTime.parse('${onekitString(value)}T00:00:00Z');
    default:
      return DateTime.parse(onekitString(value)).toUtc();
  }
}

bool onekitHasPrefix(Map<String, dynamic> json, String prefix) =>
    json.keys.any((k) => k.startsWith(prefix));

Map<String, dynamic> onekitStripPrefix(
  Map<String, dynamic> json,
  String prefix,
) => {
  for (final entry in json.entries)
    if (entry.key.startsWith(prefix))
      entry.key.substring(prefix.length): entry.value,
};

Object? _canonical(Object? value) {
  if (value is Map) {
    final keys = value.keys.map((k) => k.toString()).toList()..sort();
    return SplayTreeMap<String, Object?>.fromIterable(
      keys,
      value: (k) => _canonical(value[k]),
    );
  }
  if (value is List) return value.map(_canonical).toList();
  return value;
}

bool onekitJsonEquals(Object? a, Object? b) =>
    jsonEncode(_canonical(a)) == jsonEncode(_canonical(b));

int onekitJsonHash(Object? value) => jsonEncode(_canonical(value)).hashCode;

class OnekitSseEvent {
  OnekitSseEvent(this.event, this.data);

  final String event;
  final String data;
}

Stream<OnekitSseEvent> onekitSseEvents(
  Stream<List<int>> body,
  int maxLineBytes,
) async* {
  final limit = maxLineBytes > 0 ? maxLineBytes : defaultMaxSseLineBytes;
  var event = '';
  final data = <String>[];
  await for (final line
      in body.transform(utf8.decoder).transform(const LineSplitter())) {
    if (line.length > limit)
      throw const FormatException('SSE line exceeds configured limit');
    if (line.isEmpty) {
      if (data.isNotEmpty) yield OnekitSseEvent(event, data.join('\n'));
      event = '';
      data.clear();
      continue;
    }
    if (line.startsWith(':')) continue;
    final colon = line.indexOf(':');
    final name = colon < 0 ? line : line.substring(0, colon);
    var value = colon < 0 ? '' : line.substring(colon + 1);
    if (value.startsWith(' ')) value = value.substring(1);
    if (name == 'event') {
      event = value;
    } else if (name == 'data') {
      data.add(value);
    }
  }
  if (data.isNotEmpty) yield OnekitSseEvent(event, data.join('\n'));
}
