package gents

import (
	"fmt"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

// referencedTypeNames returns the request/response/error type names that
// belong to this same generated module - the ones imported directly from
// "./types". A type resolved to a different module gets its own qualified
// namespace import instead (see collectServiceExternalRefs).
func referencedTypeNames(file *onkir.File, resolver PackageResolver) []string {
	seen := map[string]bool{}
	var names []string
	add := func(m *onkir.Message) {
		if !isLocalMessage(resolver, m) {
			return
		}
		if !seen[m.Name] {
			seen[m.Name] = true
			names = append(names, m.Name)
		}
	}
	for _, s := range file.Services {
		for _, m := range s.Methods {
			add(m.Request)
			add(m.Response)
			for _, errType := range m.ErrorTypes {
				add(errType)
			}
		}
	}
	return names
}

// referencedCodecNames returns the encode<Request>/decode<Response|Error>
// function names this file's client methods need from "./types" - every
// local request/response/error message has one of each (see types.go).
func referencedCodecNames(file *onkir.File, resolver PackageResolver) []string {
	seen := map[string]bool{}
	var names []string
	add := func(prefix string, m *onkir.Message) {
		if !isLocalMessage(resolver, m) {
			return
		}
		key := prefix + m.Name
		if !seen[key] {
			seen[key] = true
			names = append(names, key)
		}
	}
	for _, s := range file.Services {
		for _, m := range s.Methods {
			add("encode", m.Request)
			add("validate", m.Request)
			add("decode", m.Response)
			for _, errType := range m.ErrorTypes {
				add("decode", errType)
			}
		}
	}
	return names
}

// GenerateClient generates client.ts treating every message/enum type as
// local. Use GenerateClientWithResolver for a multi-package project where
// some referenced types live in a different generated module.
func GenerateClient(file *onkir.File) []byte {
	return GenerateClientWithResolver(file, nil)
}

func GenerateClientWithResolver(file *onkir.File, resolver PackageResolver) []byte {
	return GenerateClientWithOptions(file, resolver, Options{})
}

func GenerateClientWithOptions(file *onkir.File, resolver PackageResolver, opts Options) []byte {
	if len(file.Services) == 0 {
		return nil
	}

	p := newPrinterWithOptions(resolver, opts)
	p.P("// Code generated by onek. DO NOT EDIT.")
	if names := referencedTypeNames(file, resolver); len(names) > 0 {
		p.P(`import type { `, strings.Join(names, ", "), ` } from "./types.js";`)
	}
	fns := append(referencedCodecNames(file, resolver), wsRawImportNames(p, file, func(m *onkir.Method) []*onkir.Message { return []*onkir.Message{m.Request, m.Response} })...)
	if len(fns) > 0 {
		p.P(`import { `, strings.Join(fns, ", "), ` } from "./types.js";`)
	}
	for _, ref := range collectServiceExternalRefs(file, resolver) {
		p.P(`import * as `, ref.Alias, ` from "`, ref.ImportPath, `";`)
	}
	p.P()

	if opts.SharedRuntime != "" {
		writeSharedRuntimeImports(p, opts.SharedRuntime)
	} else {
		writeResponseBodyRuntime(p)
		writeAPIError(p)
		writeTypedAPIError(p)
	}
	if onkir.FileHasWSMethods(file) {
		writeTSWSSharedRuntime(p)
	}
	if onkir.FileHasWSCorrelation(file) {
		writeTSWSPendingType(p)
	}

	for _, s := range file.Services {
		writeClientClass(p, s)
	}

	return pruneUnusedNamedImports(pruneUnusedHelpers(p.Bytes(), clientHelpers))
}

// writeAPIError emits a shared error type thrown for any response status
// that doesn't match one of a method's declared error types. Carries the raw
// body text and status code as plain properties (not a parsed/decoded
// shape, since the body isn't necessarily JSON) for callers that want to
// inspect a failure beyond the generic message.
func writeAPIError(p *Printer) {
	p.P("export class RequestValidationError extends TypeError {")
	p.P("readonly violations: string[];")
	p.P()
	p.P("constructor(prefix: string, violations: string[]) {")
	p.P(`super(prefix + ": " + violations.join("; "));`)
	p.P(`this.name = "RequestValidationError";`)
	p.P("this.violations = violations;")
	p.P("}")
	p.P("}")
	p.P()
	p.P("export interface RequestOptions {")
	p.P("signal?: AbortSignal;")
	p.P("headers?: Record<string, string>;")
	p.P("timeoutMs?: number;")
	p.P("}")
	p.P()
	p.P("export const DEFAULT_REQUEST_TIMEOUT_MS = 30000;")
	p.P()
	p.P("function requestSignal(signal: AbortSignal | undefined, timeoutMs: number): AbortSignal | null {")
	p.P("if (!(timeoutMs > 0)) return signal ?? null;")
	p.P("const timeout = AbortSignal.timeout(timeoutMs);")
	p.P("return signal ? AbortSignal.any([signal, timeout]) : timeout;")
	p.P("}")
	p.P()
	p.P("export interface ApiErrorDetails {")
	p.P("message?: string;")
	p.P("code?: string;")
	p.P("requestId?: string;")
	p.P("}")
	p.P()
	p.P("export type ApiErrorParser = (error: { statusCode: number; body: string; json: unknown; headers: Headers | undefined }) => ApiErrorDetails | undefined;")
	p.P()
	p.P("export type DefaultHeaders = Record<string, string> | (() => Record<string, string> | Promise<Record<string, string>>);")
	p.P()
	p.P("function isRecord(value: unknown): value is Record<string, unknown> {")
	p.P(`return typeof value === "object" && value !== null && !Array.isArray(value);`)
	p.P("}")
	p.P()
	p.P("function defaultErrorDetails(json: unknown): ApiErrorDetails {")
	p.P("const out: ApiErrorDetails = {};")
	p.P("const inner = isRecord(json) && isRecord(json.error) ? json.error : json;")
	p.P("if (!isRecord(inner)) return out;")
	p.P(`if (typeof inner.message === "string") out.message = inner.message;`)
	p.P(`if (typeof inner.code === "string") out.code = inner.code;`)
	p.P("const requestId = inner.request_id ?? inner.requestId;")
	p.P(`if (typeof requestId === "string") out.requestId = requestId;`)
	p.P("return out;")
	p.P("}")
	p.P()
	p.P("// ApiError is thrown for any response status a method does not declare. It")
	p.P("// keeps the status and the raw body, and also parses a JSON body so callers")
	p.P("// can read json, message, code and requestId without re-parsing. The default")
	p.P("// parser understands {message}, {code, message, request_id} and the nested")
	p.P("// {error: {code, message, request_id}} envelope, and falls back to the")
	p.P("// X-Request-ID header; pass errorParser in the client options for any other")
	p.P("// shape.")
	p.P("export class ApiError extends Error {")
	p.P("statusCode: number;")
	p.P("body: string;")
	p.P("json: unknown;")
	p.P("code?: string;")
	p.P("requestId?: string;")
	p.P()
	p.P("constructor(statusCode: number, body: string, options?: { headers?: Headers; parse?: ApiErrorParser }) {")
	p.P("let json: unknown;")
	p.P("try { json = JSON.parse(body); } catch { json = undefined; }")
	p.P("const details = (json === undefined ? undefined : (options?.parse?.({ statusCode, body, json, headers: options.headers }) ?? defaultErrorDetails(json))) ?? {};")
	p.P(`super(details.message ?? "unexpected status " + statusCode + ": " + body);`)
	p.P(`this.name = "ApiError";`)
	p.P("this.statusCode = statusCode;")
	p.P("this.body = body;")
	p.P("this.json = json;")
	p.P("if (details.code !== undefined) this.code = details.code;")
	p.P(`const requestId = details.requestId ?? options?.headers?.get("x-request-id") ?? undefined;`)
	p.P("if (requestId !== undefined) this.requestId = requestId;")
	p.P("}")
	p.P("}")
	p.P()
}

func writeTypedAPIError(p *Printer) {
	p.P("export class TypedApiError<T extends object = Record<string, unknown>> extends ApiError {")
	p.P("readonly errorType: string;")
	p.P("readonly data: T;")
	p.P()
	p.P("constructor(statusCode: number, body: string, errorType: string, data: T, options?: { headers?: Headers; parse?: ApiErrorParser }) {")
	p.P("super(statusCode, body, options);")
	p.P("this.name = errorType;")
	p.P("this.errorType = errorType;")
	p.P("this.data = data;")
	p.P("Object.assign(this, data);")
	p.P("}")
	p.P("}")
	p.P()
}

func writeResponseBodyRuntime(p *Printer) {
	p.P("const DEFAULT_MAX_RESPONSE_BODY_BYTES = 8 * 1024 * 1024;")
	p.P("const DEFAULT_MAX_SSE_LINE_BYTES = 1024 * 1024;")
	p.P()
	p.P("function responseBodyLimit(value: number | undefined): number {")
	p.P("return value && value > 0 ? value : DEFAULT_MAX_RESPONSE_BODY_BYTES;")
	p.P("}")
	p.P()
	p.P("async function readResponseText(res: Response, configuredLimit?: number): Promise<string> {")
	p.P("const limit = responseBodyLimit(configuredLimit);")
	p.P("const contentLength = Number(res.headers.get(\"content-length\"));")
	p.P("if (Number.isFinite(contentLength) && contentLength > limit) throw new Error(\"response body exceeds configured limit\");")
	p.P("if (!res.body) {")
	p.P("const text = await res.text();")
	p.P("if (new TextEncoder().encode(text).byteLength > limit) throw new Error(\"response body exceeds configured limit\");")
	p.P("return text;")
	p.P("}")
	p.P("const reader = res.body.getReader();")
	p.P("const chunks: Uint8Array[] = [];")
	p.P("let total = 0;")
	p.P("try {")
	p.P("while (true) {")
	p.P("const { done, value } = await reader.read();")
	p.P("if (done) break;")
	p.P("total += value.byteLength;")
	p.P("if (total > limit) { await reader.cancel(); throw new Error(\"response body exceeds configured limit\"); }")
	p.P("chunks.push(value);")
	p.P("}")
	p.P("} finally {")
	p.P("reader.releaseLock();")
	p.P("}")
	p.P("const body = new Uint8Array(total);")
	p.P("let offset = 0;")
	p.P("for (const chunk of chunks) { body.set(chunk, offset); offset += chunk.byteLength; }")
	p.P("return new TextDecoder().decode(body);")
	p.P("}")
	p.P()
}

func writeClientClass(p *Printer, s *onkir.Service) {
	// Duplex classes are top-level types returned by client methods below,
	// not members of ServiceClient - emit them before it opens so they don't
	// land nested inside another class body (invalid TS/JS syntax).
	for _, m := range s.Methods {
		if m.IsWebSocket() {
			writeTSDuplexClass(p, m)
		}
	}

	p.P("export interface ", s.Name, "ClientOptions {")
	p.P("fetch?: typeof fetch;")
	p.P("// Headers sent on every request. A function is called before each request,")
	p.P("// so a token that changes can be read fresh; per-call headers win.")
	p.P("defaultHeaders?: DefaultHeaders;")
	p.P("// Called with every response before it is read or turned into an error.")
	p.P("onResponse?: (res: Response, request: { method: string; url: string }) => void | Promise<void>;")
	p.P("// Called when a response is 401, before the ApiError is thrown, for")
	p.P("// example to redirect to a sign-in page.")
	p.P("onUnauthorized?: (res: Response, request: { method: string; url: string }) => void | Promise<void>;")
	p.P("maxResponseBodyBytes?: number;")
	p.P("maxSSELineBytes?: number;")
	p.P("timeoutMs?: number;")
	p.P("errorParser?: ApiErrorParser;")
	for _, m := range s.Methods {
		if m.IsWebSocket() {
			p.P("// Cap on one inbound WebSocket message (default DEFAULT_MAX_WS_FRAME_BYTES);")
			p.P("// a larger one closes the socket with 1009. Negative disables it.")
			p.P("maxFrameBytes?: number;")
			p.P("maxMessageBytes?: number;")
			p.P("// send() waits while more than this many bytes are queued on the")
			p.P("// socket (default DEFAULT_WS_HIGH_WATER_MARK_BYTES).")
			p.P("highWaterMarkBytes?: number;")
			break
		}
	}
	p.P("}")
	p.P()

	writeJSDoc(p, s.Doc)
	p.P("export class ", s.Name, "Client {")
	p.P("private baseUrl: string;")
	p.P("private options: ", s.Name, "ClientOptions;")
	p.P()
	p.P("constructor(baseUrl: string, options: ", s.Name, "ClientOptions = {}) {")
	p.P("this.baseUrl = baseUrl;")
	p.P("this.options = options;")
	p.P("}")
	p.P()
	if serviceHasHTTPRoutes(s) {
		p.P("private async request(input: string, init: RequestInit): Promise<Response> {")
		p.P("const doFetch = this.options.fetch ?? fetch;")
		p.P("const defaults = typeof this.options.defaultHeaders === \"function\" ? await this.options.defaultHeaders() : this.options.defaultHeaders;")
		p.P("const res = await doFetch(input, { ...init, headers: { ...defaults, ...(init.headers as Record<string, string> | undefined) } });")
		p.P("const info = { method: init.method ?? \"GET\", url: input };")
		p.P("if (this.options.onResponse) await this.options.onResponse(res, info);")
		p.P("if (res.status === 401 && this.options.onUnauthorized) await this.options.onUnauthorized(res, info);")
		p.P("return res;")
		p.P("}")
		p.P()
	}

	for _, m := range s.Methods {
		switch {
		case m.IsWebSocket():
			writeTSWSClientMethod(p, s, m)
		case m.IsStream():
			writeSSEClientMethod(p, s, m)
		default:
			writeClientMethod(p, s, m)
		}
	}

	p.P("}")
	p.P()
}

func writeClientMethod(p *Printer, s *onkir.Service, m *onkir.Method) {
	verb, _ := m.Verb()
	path, _ := m.Path()
	fullPath := s.BasePath + path
	bodyBearing := onkir.IsBodyBearingVerb(verb)

	writeJSDoc(p, tsDeprecatedDoc(m.Doc, m.Deprecated))
	p.P("async ", CamelCase(m.Name), "(req: ", p.MessageTypeName(m.Request),
		", opts?: RequestOptions): Promise<", p.MessageTypeName(m.Response), "> {")
	validator := p.MessageCodecName(m.Request, "validate")
	p.P("const violations = ", validator, "(req);")
	p.P(`if (violations.length > 0) throw new RequestValidationError("invalid request", violations);`)
	p.P(fmt.Sprintf("let path = %q;", fullPath))
	for _, paramName := range onkir.PathParamNames(path) {
		field := onkir.FindField(m.Request, paramName)
		if field == nil {
			continue
		}
		if onkir.IsWildcardParam(path, paramName) {
			p.P(fmt.Sprintf(`if (String(req.%s).split("/").some((segment) => segment === "." || segment === "..")) throw new RequestValidationError("invalid request", [%q]);`,
				p.naming.ident(field.Name), paramName+": dot segments are not allowed"))
		}
		p.P(fmt.Sprintf(
			"path = path.replace(%q, %s);",
			onkir.PathPlaceholder(path, paramName), tsPathEncodeExpr(path, paramName, "req."+p.naming.ident(field.Name)),
		))
	}

	if !bodyBearing {
		writeClientQueryParams(p, m.Request)
	}

	p.P("const res = await this.request(this.baseUrl + path, {")
	p.P(fmt.Sprintf("method: %q,", strings.ToUpper(verb)))
	if bodyBearing {
		p.P(`headers: { "Content-Type": "application/json", ...opts?.headers },`)
		if bodyField, ok := m.BodyField(); ok {
			p.P("body: JSON.stringify(", p.MessageCodecName(m.Request, "encode"), "(req)[", fmt.Sprintf("%q", bodyField), "]),")
		} else {
			p.P("body: JSON.stringify(", p.MessageCodecName(m.Request, "encode"), "(req)),")
		}
	} else {
		p.P("headers: { ...opts?.headers },")
	}
	p.P("signal: requestSignal(opts?.signal, opts?.timeoutMs ?? this.options.timeoutMs ?? DEFAULT_REQUEST_TIMEOUT_MS),")
	p.P("});")
	p.P()

	p.P("if (!res.ok) {")
	writeClientErrorHandling(p, m)
	p.P("}")
	p.P()
	// A success with no body must not reach JSON.parse. A 204 has none by
	// definition, and an empty 200 is equally legal, but JSON.parse("") throws
	// SyntaxError("Unexpected end of JSON input") - which a caller sees as an
	// opaque failure for an operation that actually succeeded.
	//
	// writeClientErrorHandling already guards this same hazard on the error
	// path; this is the success path catching up. Emptiness is tested rather
	// than the status code, so it covers 204 and an empty 200 alike.
	p.P("const text = await readResponseText(res, this.options.maxResponseBodyBytes);")
	p.P("return ", p.MessageCodecName(m.Response, "decode"), `(text.trim() === "" ? {} : JSON.parse(text));`)
	p.P("}")
	p.P()
}

func writeClientQueryParams(p *Printer, req *onkir.Message) {
	p.P("const query = new URLSearchParams();")
	for _, field := range req.Fields {
		d, ok := field.Decorator("query")
		if !ok || field.Type == nil || field.Type.Kind != onkir.KindScalar {
			continue
		}
		queryName, _ := d.Value()
		if queryName == "" {
			queryName = field.Name
		}
		tsName := p.naming.ident(field.Name)
		p.P("if (req.", tsName, " !== undefined) {")
		if field.Repeated {
			p.P("for (const value of req.", tsName, ") {")
			p.P(fmt.Sprintf("query.append(%q, String(value));", queryName))
			p.P("}")
		} else {
			p.P(fmt.Sprintf("query.set(%q, String(req.%s));", queryName, tsName))
		}
		p.P("}")
	}
	p.P(`const queryStr = query.toString();`)
	p.P(`if (queryStr) { path += "?" + queryStr; }`)
}

func writeClientErrorHandling(p *Printer, m *onkir.Method) {
	p.P("const body = await readResponseText(res, this.options.maxResponseBodyBytes);")
	for _, errType := range m.ErrorTypes {
		status := 500
		if code, ok := errType.StatusCode(); ok {
			status = code
		}
		p.P(fmt.Sprintf("if (res.status === %d) {", status))
		p.P("try {")
		p.P("throw new TypedApiError(res.status, body, ", fmt.Sprintf("%q", errType.Name), ", ", p.MessageCodecName(errType, "decode"), "(JSON.parse(body)), { headers: res.headers, ...(this.options.errorParser ? { parse: this.options.errorParser } : {}) });")
		p.P("} catch (err) {")
		p.P("if (!(err instanceof SyntaxError)) throw err;")
		p.P("}")
		p.P("}")
	}
	p.P(`throw new ApiError(res.status, body, { headers: res.headers, ...(this.options.errorParser ? { parse: this.options.errorParser } : {}) });`)
}

func tsPathEncodeExpr(path, name, value string) string {
	if onkir.IsWildcardParam(path, name) {
		return "String(" + value + ").split(\"/\").map(encodeURIComponent).join(\"/\")"
	}
	return "encodeURIComponent(String(" + value + "))"
}
