package gents

import (
	"fmt"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

// referencedTypeNames returns the request/response/error type names that
// belong to this same generated module - the ones imported directly from
// "./types". A type resolved to a different module gets its own qualified
// namespace import instead (see collectServiceExternalRefs).
func referencedTypeNames(file *onkir.File, resolver PackageResolver) []string {
	seen := map[string]bool{}
	var names []string
	add := func(m *onkir.Message) {
		if !isLocalMessage(resolver, m) {
			return
		}
		if !seen[m.Name] {
			seen[m.Name] = true
			names = append(names, m.Name)
		}
	}
	for _, s := range file.Services {
		for _, m := range s.Methods {
			add(m.Request)
			add(m.Response)
			for _, errType := range m.ErrorTypes {
				add(errType)
			}
		}
	}
	return names
}

// referencedCodecNames returns the encode<Request>/decode<Response|Error>
// function names this file's client methods need from "./types" - every
// local request/response/error message has one of each (see types.go).
func referencedCodecNames(file *onkir.File, resolver PackageResolver) []string {
	seen := map[string]bool{}
	var names []string
	add := func(prefix string, m *onkir.Message) {
		if !isLocalMessage(resolver, m) {
			return
		}
		key := prefix + m.Name
		if !seen[key] {
			seen[key] = true
			names = append(names, key)
		}
	}
	for _, s := range file.Services {
		for _, m := range s.Methods {
			add("encode", m.Request)
			add("decode", m.Response)
			for _, errType := range m.ErrorTypes {
				add("decode", errType)
			}
		}
	}
	return names
}

// GenerateClient generates client.ts treating every message/enum type as
// local. Use GenerateClientWithResolver for a multi-package project where
// some referenced types live in a different generated module.
func GenerateClient(file *onkir.File) []byte {
	return GenerateClientWithResolver(file, nil)
}

func GenerateClientWithResolver(file *onkir.File, resolver PackageResolver) []byte {
	if len(file.Services) == 0 {
		return nil
	}

	p := newPrinter(resolver)
	p.P("// Code generated by onek. DO NOT EDIT.")
	if names := referencedTypeNames(file, resolver); len(names) > 0 {
		p.P(`import type { `, strings.Join(names, ", "), ` } from "./types";`)
	}
	if fns := referencedCodecNames(file, resolver); len(fns) > 0 {
		p.P(`import { `, strings.Join(fns, ", "), ` } from "./types";`)
	}
	for _, ref := range collectServiceExternalRefs(file, resolver) {
		p.P(`import * as `, ref.Alias, ` from "`, ref.ImportPath, `";`)
	}
	p.P()

	writeAPIError(p)

	for _, s := range file.Services {
		writeClientClass(p, s)
	}

	return p.Bytes()
}

// writeAPIError emits a shared error type thrown for any response status
// that doesn't match one of a method's declared error types. Carries the raw
// body text and status code as plain properties (not a parsed/decoded
// shape, since the body isn't necessarily JSON) for callers that want to
// inspect a failure beyond the generic message.
func writeAPIError(p *Printer) {
	p.P("export class ApiError extends Error {")
	p.P("statusCode: number;")
	p.P("body: string;")
	p.P()
	p.P("constructor(statusCode: number, body: string) {")
	p.P(`super("unexpected status " + statusCode + ": " + body);`)
	p.P(`this.name = "ApiError";`)
	p.P("this.statusCode = statusCode;")
	p.P("this.body = body;")
	p.P("}")
	p.P("}")
	p.P()
}

func writeClientClass(p *Printer, s *onkir.Service) {
	p.P("export interface ", s.Name, "ClientOptions {")
	p.P("fetch?: typeof fetch;")
	p.P("defaultHeaders?: Record<string, string>;")
	p.P("}")
	p.P()

	p.P("export class ", s.Name, "Client {")
	p.P("private baseUrl: string;")
	p.P("private options: ", s.Name, "ClientOptions;")
	p.P()
	p.P("constructor(baseUrl: string, options: ", s.Name, "ClientOptions = {}) {")
	p.P("this.baseUrl = baseUrl;")
	p.P("this.options = options;")
	p.P("}")
	p.P()
	p.P("private request(input: string, init: RequestInit): Promise<Response> {")
	p.P("const doFetch = this.options.fetch ?? fetch;")
	p.P("return doFetch(input, init);")
	p.P("}")
	p.P()

	for _, m := range s.Methods {
		if m.IsStream() {
			writeSSEClientMethod(p, s, m)
		} else {
			writeClientMethod(p, s, m)
		}
	}

	p.P("}")
	p.P()
}

func writeClientMethod(p *Printer, s *onkir.Service, m *onkir.Method) {
	verb, _ := m.Verb()
	path, _ := m.Path()
	fullPath := s.BasePath + path
	bodyBearing := isBodyBearingVerb(verb)

	p.P("async ", CamelCase(m.Name), "(req: ", p.MessageTypeName(m.Request),
		"): Promise<", p.MessageTypeName(m.Response), "> {")
	p.P(fmt.Sprintf("let path = %q;", fullPath))
	for _, paramName := range pathParamNames(path) {
		field := findField(m.Request, paramName)
		if field == nil {
			continue
		}
		p.P(fmt.Sprintf(
			"path = path.replace(%q, encodeURIComponent(String(req.%s)));",
			"{"+paramName+"}", CamelCase(field.Name),
		))
	}

	if !bodyBearing {
		writeClientQueryParams(p, m.Request)
	}

	p.P("const res = await this.request(this.baseUrl + path, {")
	p.P(fmt.Sprintf("method: %q,", strings.ToUpper(verb)))
	if bodyBearing {
		p.P(`headers: { "Content-Type": "application/json", ...this.options.defaultHeaders },`)
		p.P("body: JSON.stringify(encode", m.Request.Name, "(req)),")
	} else {
		p.P("headers: { ...this.options.defaultHeaders },")
	}
	p.P("});")
	p.P()

	p.P("if (!res.ok) {")
	writeClientErrorHandling(p, m)
	p.P("}")
	p.P()
	p.P("return decode", m.Response.Name, "(await res.json());")
	p.P("}")
	p.P()
}

func findField(msg *onkir.Message, name string) *onkir.Field {
	for _, f := range msg.Fields {
		if f.Name == name {
			return f
		}
	}
	return nil
}

func pathParamNames(path string) []string {
	var names []string
	start := -1
	for i, c := range path {
		if c == '{' {
			start = i + 1
		} else if c == '}' && start >= 0 {
			names = append(names, path[start:i])
			start = -1
		}
	}
	return names
}

func isBodyBearingVerb(verb string) bool {
	return verb == "post" || verb == "put" || verb == "patch" || verb == "query"
}

func writeClientQueryParams(p *Printer, req *onkir.Message) {
	p.P("const query = new URLSearchParams();")
	for _, field := range req.Fields {
		d, ok := field.Decorator("query")
		if !ok || field.Type == nil || field.Type.Kind != onkir.KindScalar {
			continue
		}
		queryName, _ := d.Value()
		if queryName == "" {
			queryName = field.Name
		}
		tsName := CamelCase(field.Name)
		p.P("if (req.", tsName, " !== undefined) {")
		p.P(fmt.Sprintf("query.set(%q, String(req.%s));", queryName, tsName))
		p.P("}")
	}
	p.P(`const queryStr = query.toString();`)
	p.P(`if (queryStr) { path += "?" + queryStr; }`)
}

func writeClientErrorHandling(p *Printer, m *onkir.Method) {
	p.P("const body = await res.text();")
	for _, errType := range m.ErrorTypes {
		status := 500
		if code, ok := errType.StatusCode(); ok {
			status = code
		}
		p.P(fmt.Sprintf("if (res.status === %d) {", status))
		p.P("throw decode", errType.Name, "(JSON.parse(body));")
		p.P("}")
	}
	p.P(`throw new ApiError(res.status, body);`)
}
