package gents

import (
	"strconv"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

// literalNull is the shared fixture for absent values.
const literalNull = "null"

// GenerateMSWHandlers generates msw.ts: Mock Service Worker request handlers
// mirroring every route, returning deterministic schema-derived fixtures so
// frontend test suites intercept fetch with contract-accurate responses
// without running a backend.
func GenerateMSWHandlers(file *onkir.File) []byte {
	return GenerateMSWHandlersWithResolver(file, nil)
}

func GenerateMSWHandlersWithResolver(file *onkir.File, resolver PackageResolver) []byte {
	if len(file.Services) == 0 {
		return nil
	}
	p := newPrinter(resolver)
	p.P("// Code generated by onek. DO NOT EDIT.")
	p.P(`import { http, HttpResponse } from "msw";`)
	p.P()

	for _, s := range file.Services {
		writeMSWService(p, s)
	}
	return p.Bytes()
}

func writeMSWService(p *Printer, s *onkir.Service) {
	p.P("export const ", s.Name, "Handlers = [")
	for _, m := range s.Methods {
		writeMSWHandler(p, s, m)
	}
	p.P("];")
	p.P()
}

func writeMSWHandler(p *Printer, s *onkir.Service, m *onkir.Method) {
	verb, _ := m.Verb()
	path, _ := m.Path()
	fullPath := s.BasePath + path
	mswPath := strconv.Quote(mswPathPattern(fullPath))
	example := mswMessageLiteral(m.Response, 0)

	if m.IsStream() {
		// SSE streams are served as a fixed two-event frame.
		p.P("// ", strings.ToUpper(verb), " ", fullPath, " (SSE)")
		p.P("http.all(", mswPath, ", ({ request }) => {")
		p.P(`if (request.method !== `, strconv.Quote(strings.ToUpper(verb)), ") return;")
		p.P("const event = ", example, ";")
		p.P(`const frame = "data: " + JSON.stringify(event) + "\n\n";`)
		p.P(`return new HttpResponse(frame + frame, { headers: { "Content-Type": "text/event-stream" } });`)
		p.P("}),")
		return
	}

	switch verb {
	case "query":
		// MSW has no shortcut for custom methods; match all and enforce QUERY.
		p.P("// Custom HTTP QUERY method: match all requests on the path,")
		p.P("// fall through to the network for any other method.")
		p.P("http.all(", mswPath, ", ({ request }) => {")
		p.P(`if (request.method !== "QUERY") return undefined;`)
		p.P("return HttpResponse.json(", example, ");")
		p.P("}),")
	default:
		p.P("http.", verb, "(", mswPath, ", () => HttpResponse.json(", example, ")),")
	}
}

// mswPathPattern converts OneKit `{param}` wildcards into MSW's `:param`
// form.
func mswPathPattern(path string) string {
	var out strings.Builder
	start := -1
	for i, c := range path {
		switch {
		case c == '{':
			start = i + 1
			out.WriteByte(':')
		case c == '}' && start >= 0:
			start = -1
		default:
			out.WriteRune(c)
		}
	}
	return out.String()
}

// mswMessageLiteral renders a full wire-shaped object literal for msg,
// honoring @unwrap transparency and flattened children.
func mswMessageLiteral(msg *onkir.Message, depth int) string {
	if msg == nil || depth > 4 {
		return "{}"
	}
	if field := rootUnwrapField(msg); field != nil {
		literal := mswFieldLiteral(field, depth)
		if field.Repeated {
			return "[" + literal + "]"
		}
		return literal
	}
	if len(msg.Fields) == 0 {
		return "{}"
	}
	var parts []string
	for _, plan := range collectCodecFields(msg, "") {
		parts = append(parts, strconv.Quote(plan.wire)+": "+mswFieldLiteral(plan.field, depth))
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

// mswFieldLiteral renders one field's fixture value honoring repetition,
// nullability, maps, oneofs, and flattened children.
func mswFieldLiteral(f *onkir.Field, depth int) string {
	if emptyBehaviorValue(f) == emptyBehaviorNull {
		return literalNull
	}
	if f.Oneof != nil && len(f.Oneof.Variants) > 0 {
		return mswOneofLiteral(f, depth)
	}
	if _, ok := flattenPrefix(f); ok {
		// Flattened children are merged upstream by collectCodecFields.
		return "{}"
	}
	value := syntheticFieldLiteral(f, depth)
	if f.Repeated {
		value = "[" + value + "]"
	}
	return value
}

// mswOneofLiteral renders the first variant's wire shape: the discriminator
// key plus either a named payload property or, when flattened, the variant's
// fields inlined into the same object.
func mswOneofLiteral(f *onkir.Field, depth int) string {
	v := f.Oneof.Variants[0]
	discriminator := oneofDiscriminatorKey(f)
	tag := strconv.Quote(v.Tag())
	if f.Oneof.Flatten() && v.Type != nil && v.Type.Kind == onkir.KindMessage {
		inner := mswMessageLiteral(v.Type.Message, depth+1)
		tail := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(inner, "{"), "}"))
		if tail == "" {
			return "{" + strconv.Quote(discriminator) + ": " + tag + "}"
		}
		return "{" + strconv.Quote(discriminator) + ": " + tag + ", " + tail + "}"
	}
	payload := syntheticTypeLiteral(v.Type, depth+1)
	return "{" + strconv.Quote(discriminator) + ": " + tag + ", " + strconv.Quote(CamelCase(v.Name)) + ": " + payload + "}"
}

// syntheticFieldLiteral renders the single-item fixture for a field's type,
// applying field-level @encode choices and validator-derived overrides.
func syntheticFieldLiteral(f *onkir.Field, depth int) string {
	switch {
	case f.Type == nil:
		return literalNull
	case f.Type.Kind == onkir.KindEnum && needsEnumNumberEncoding(f):
		return "0"
	case f.Type.Kind == onkir.KindEnum:
		return strconv.Quote(firstEnumJSONName(f.Type.Enum))
	case f.Type.Kind == onkir.KindScalar && f.Type.Scalar == onkir.ScalarInt64,
		f.Type.Kind == onkir.KindScalar && f.Type.Scalar == onkir.ScalarUint64:
		if !needsInt64NumberEncoding(f) {
			return `"1"`
		}
		return "1"
	case f.Type.Kind == onkir.KindScalar && f.Type.Scalar == onkir.ScalarTimestamp:
		switch timestampEncodingValue(f) {
		case timestampEncodeUnixSeconds:
			return "1735689600"
		case timestampEncodeUnixMillis:
			return "1735689600000"
		case timestampEncodeDate:
			return `"2025-01-01"`
		}
		return `"2025-01-01T00:00:00Z"`
	case f.Type.Kind == onkir.KindScalar && f.Type.Scalar == onkir.ScalarBytes:
		if encoding, ok := fieldEncodeValue(f); ok {
			switch encoding {
			case "hex":
				return `"61"`
			case "base64url", "base64url_raw", "base64_raw":
				return `"YQ"`
			}
		}
		return `"YQ=="`
	case f.Type.Kind == onkir.KindScalar && f.Type.Scalar == onkir.ScalarString:
		if literal, ok := stringScalarExample(f); ok {
			return literal
		}
	}
	return typeLiteral(f.Type, depth)
}

func firstEnumJSONName(e *onkir.Enum) string {
	if len(e.Values) > 0 {
		return e.Values[0].JSONName()
	}
	return ""
}

// syntheticTypeLiteral is syntheticFieldLiteral's counterpart for types
// without an owning field (oneof payloads, map values).
func syntheticTypeLiteral(t *onkir.Type, depth int) string {
	return syntheticFieldLiteral(&onkir.Field{Type: t}, depth)
}

// typeLiteral renders a bare TypeRef fixture.
func typeLiteral(t *onkir.Type, depth int) string {
	if t == nil || depth > 6 {
		return literalNull
	}
	switch t.Kind {
	case onkir.KindMessage:
		return mswMessageLiteral(t.Message, depth+1)
	case onkir.KindEnum:
		return strconv.Quote(firstEnumJSONName(t.Enum))
	case onkir.KindMap:
		return `{"key": ` + typeLiteral(t.MapValue, depth+1) + `}`
	case onkir.KindScalar:
		return scalarLiteral(t.Scalar)
	default:
		return literalNull
	}
}

func scalarLiteral(kind onkir.ScalarKind) string {
	switch kind {
	case onkir.ScalarString:
		return `"string"`
	case onkir.ScalarBool:
		return "true"
	case onkir.ScalarInt32, onkir.ScalarUint32, onkir.ScalarInt64, onkir.ScalarUint64:
		return "1"
	case onkir.ScalarFloat32, onkir.ScalarFloat64:
		return "1.5"
	case onkir.ScalarBytes:
		return `"YQ=="`
	case onkir.ScalarTimestamp:
		return `"2025-01-01T00:00:00Z"`
	case onkir.ScalarJSON:
		return "{}"
	default:
		return literalNull
	}
}

// stringScalarExample derives constrained string fixtures from validators so
// mocked responses pass client-side zod schemas unchanged.
func stringScalarExample(f *onkir.Field) (string, bool) {
	if d, ok := f.Decorator("in"); ok {
		value, _ := d.Arg(0)
		return strconv.Quote(value), true
	}
	if f.HasDecorator("email") {
		return `"user@example.com"`, true
	}
	if f.HasDecorator("uuid") {
		return `"0f9ad6e5-8c1a-4b2e-9d3f-5a7c8e1b2d4f"`, true
	}
	if f.HasDecorator("uri") {
		return `"https://example.com/resource"`, true
	}
	if d, ok := f.Decorator("len"); ok && len(d.Args) == 2 {
		minimum, _ := d.Arg(0)
		n, err := strconv.Atoi(minimum)
		if err != nil || n < 1 {
			n = 1
		}
		if n > 16 {
			n = 16
		}
		return strconv.Quote(strings.Repeat("x", n)), true
	}
	if _, ok := f.Decorator("pattern"); ok {
		return `"match"`, true
	}
	return "", false
}
