package gents

import (
	"fmt"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

// GenerateReactQuery generates query.ts: TanStack Query hooks wrapping the
// generated fetch client, plus a resilient React hook for SSE streams.
// Hooks live behind a create<Service>Hooks(client) factory so applications
// control client construction (base URL, auth headers, SSR setup).
func GenerateReactQuery(file *onkir.File) []byte {
	return GenerateReactQueryWithResolver(file, nil)
}

func GenerateReactQueryWithResolver(file *onkir.File, resolver PackageResolver) []byte {
	if len(file.Services) == 0 {
		return nil
	}
	hasStreams := onkir.FileHasStreamMethods(file)
	hasUnary := !hasStreams || fileHasUnaryMethods(file)

	p := newPrinter(resolver)
	p.P("// Code generated by onek. DO NOT EDIT.")
	p.P(`import { useCallback, useEffect, useRef, useState } from "react";`)
	if hasUnary {
		p.P(`import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";`)
	}
	if names := referencedTypeNames(file, resolver); len(names) > 0 {
		p.P(`import type { `, strings.Join(names, ", "), ` } from "./types";`)
	}
	p.P(`import { ApiError } from "./client";`)
	for _, s := range file.Services {
		p.P(`import { `, s.Name, `Client } from "./client";`)
	}
	p.P()
	writeStreamStateHelpers(p)

	for _, s := range file.Services {
		writeServiceHooks(p, s)
	}
	return p.Bytes()
}

func fileHasUnaryMethods(file *onkir.File) bool {
	for _, s := range file.Services {
		for _, m := range s.Methods {
			if !m.IsStream() {
				return true
			}
		}
	}
	return false
}

// writeStreamStateHelpers emits the shared stream-hook machinery once per
// module: reconnecting subscription with exponential backoff and abort-safe
// teardown. The subscribe callback is kept in a ref so consumers can pass an
// inline closure without resubscribing on every render.
func writeStreamStateHelpers(p *Printer) {
	p.P("export interface SchemaStreamResult<T> {")
	p.P("events: T[];")
	p.P("latest: T | undefined;")
	p.P("error: unknown;")
	p.P("connected: boolean;")
	p.P("}")
	p.P()
	p.P("interface SchemaStreamOptions<T> {")
	p.P("enabled: boolean;")
	p.P("retries: number;")
	p.P("subscribe: (signal: AbortSignal) => AsyncGenerator<T>;")
	p.P("}")
	p.P()
	p.P("function useSchemaStream<T>(options: SchemaStreamOptions<T>): SchemaStreamResult<T> {")
	p.P(`const [events, setEvents] = useState<T[]>([]);`)
	p.P(`const [error, setError] = useState<unknown>(undefined);`)
	p.P(`const [connected, setConnected] = useState(false);`)
	p.P(`const subscribeRef = useRef(options.subscribe);`)
	p.P(`subscribeRef.current = options.subscribe;`)
	p.P("useEffect(() => {")
	p.P(`if (!options.enabled) return;`)
	p.P(`const controller = new AbortController();`)
	p.P(`let cancelled = false;`)
	p.P(`let attempt = 0;`)
	p.P("(async () => {")
	p.P("while (!cancelled) {")
	p.P("try {")
	p.P("setConnected(true);")
	p.P("setError(undefined);")
	p.P("for await (const event of subscribeRef.current(controller.signal)) {")
	p.P("if (cancelled) return;")
	p.P("setEvents((prev) => [...prev, event]);")
	p.P("}")
	p.P("setConnected(false);")
	p.P("return;")
	p.P("} catch (err) {")
	p.P("if (cancelled || controller.signal.aborted) return;")
	p.P("setConnected(false);")
	p.P("setError(err);")
	p.P("}")
	p.P("attempt += 1;")
	p.P("if (attempt > options.retries) return;")
	p.P(`await new Promise((resolve) => setTimeout(resolve, Math.min(30000, 500 * 2 ** (attempt - 1))));`)
	p.P("}")
	p.P("})();")
	p.P("return () => {")
	p.P("cancelled = true;")
	p.P("controller.abort();")
	p.P("};")
	p.P(`}, [options.enabled, options.retries]);`)
	p.P(`const latest = events.length > 0 ? events[events.length - 1] : undefined;`)
	p.P("return { events, latest, error, connected };")
	p.P("}")
	p.P()

	p.P("export function isApiError(err: unknown): err is ApiError {")
	p.P("return err instanceof ApiError;")
	p.P("}")
	p.P()
	p.P("export function errorMessage(err: unknown): string {")
	p.P("if (isApiError(err)) return err.message;")
	p.P("if (err instanceof Error) return err.message;")
	p.P(`return String(err);`)
	p.P("}")
	p.P()
}

func writeServiceHooks(p *Printer, s *onkir.Service) {
	factory := "create" + s.Name + "Hooks"
	p.P("export function ", factory, "(client: ", s.Name, "Client) {")
	p.P("return {")
	for _, m := range s.Methods {
		hookName := "use" + PascalCase(m.Name)
		reqType := p.MessageTypeName(m.Request)
		resType := p.MessageTypeName(m.Response)
		switch {
		case m.IsStream():
			p.P(hookName, "(req: ", reqType, ", opts?: { enabled?: boolean; retries?: number }): SchemaStreamResult<", resType, "> {")
			p.P("return useSchemaStream<", resType, ">({")
			p.P("enabled: opts?.enabled ?? true,")
			p.P("retries: opts?.retries ?? 5,")
			p.P("subscribe: (signal) => client.", CamelCase(m.Name), "(req, { signal }),")
			p.P("});")
			p.P("},")
		case onkir.IsBodyBearingVerb(mustString(m.Verb())):
			p.P(hookName, "() {")
			p.P(`const queryClient = useQueryClient();`)
			p.P("return useMutation({")
			p.P("mutationFn: (req: ", reqType, ") => client.", CamelCase(m.Name), "(req),")
			p.P("onSuccess: () => {")
			p.P(`queryClient.invalidateQueries({ queryKey: [`, fmt.Sprintf("%q", s.Name), `] });`)
			p.P("},")
			p.P("});")
			p.P("},")
		default:
			p.P(hookName, "(req: ", reqType, ", opts?: { enabled?: boolean }) {")
			p.P("return useQuery({")
			p.P(`queryKey: [`, fmt.Sprintf("%q", s.Name), `, `, fmt.Sprintf("%q", m.Name), `, req],`)
			p.P("queryFn: () => client.", CamelCase(m.Name), "(req),")
			p.P("enabled: opts?.enabled,")
			p.P("});")
			p.P("},")
		}
	}
	p.P("};")
	p.P("}")
	p.P()
}

func mustString(value string, ok bool) string {
	if !ok {
		return ""
	}
	return value
}
