package gents

import (
	"fmt"
	"slices"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

// serverCodecNames returns the decode<Request>/encode<Response|Error>
// function names this file's routes need from "./types" - the reverse
// direction from referencedCodecNames (client.go), since a server decodes
// incoming requests and encodes outgoing responses.
func serverCodecNames(file *onkir.File, resolver PackageResolver) []string {
	seen := map[string]bool{}
	var names []string
	add := func(prefix string, m *onkir.Message) {
		if !isLocalMessage(resolver, m) {
			return
		}
		key := prefix + m.Name
		if !seen[key] {
			seen[key] = true
			names = append(names, key)
		}
	}
	for _, s := range file.Services {
		for _, m := range s.Methods {
			add("decode", m.Request)
			add("validate", m.Request)
			add("encode", m.Response)
			for _, errType := range m.ErrorTypes {
				add("encode", errType)
			}
		}
	}
	return names
}

func writeTypedErrorHelpers(p *Printer, file *onkir.File) {
	seen := map[*onkir.Message]bool{}
	for _, s := range file.Services {
		for _, m := range s.Methods {
			for _, errType := range m.ErrorTypes {
				if seen[errType] {
					continue
				}
				seen[errType] = true
				status := 500
				if code, ok := errType.StatusCode(); ok {
					status = code
				}
				p.P("export function httpErrorFrom", errType.Name, "(value: ", p.MessageTypeName(errType), "): HttpError {")
				p.P("return new HttpError(", status, ", ", p.MessageCodecName(errType, "encode"), "(value));")
				p.P("}")
				p.P()
			}
		}
	}
}

// GenerateServer generates server.ts treating every message/enum type as
// local. Use GenerateServerWithResolver for a multi-package project where
// some referenced types live in a different generated module.
func GenerateServer(file *onkir.File) []byte {
	return GenerateServerWithResolver(file, nil)
}

func GenerateServerWithResolver(file *onkir.File, resolver PackageResolver) []byte {
	if len(file.Services) == 0 {
		return nil
	}

	p := newPrinter(resolver)
	p.P("// Code generated by onek. DO NOT EDIT.")
	if names := referencedTypeNames(file, resolver); len(names) > 0 {
		p.P(`import type { `, strings.Join(names, ", "), ` } from "./types.js";`)
	}
	fns := append(serverCodecNames(file, resolver), wsRawImportNames(p, file, func(m *onkir.Method) []*onkir.Message { return []*onkir.Message{m.Request, m.Response} })...)
	if len(fns) > 0 {
		p.P(`import { `, strings.Join(fns, ", "), ` } from "./types.js";`)
	}
	hasWS := onkir.FileHasWSMethods(file)
	if hasWS {
		p.P(`import { WebSocketServer } from "ws";`)
		p.P(`import type { Server as HttpServer, IncomingHttpHeaders, IncomingMessage } from "node:http";`)
		p.P(`import type { Duplex } from "node:stream";`)
	}
	for _, ref := range collectServiceExternalRefs(file, resolver) {
		p.P(`import * as `, ref.Alias, ` from "`, ref.ImportPath, `";`)
	}
	p.P()

	writeServerRuntime(p)
	if hasWS {
		WriteTSWSServerRuntime(p)
		WriteTSWSNodeServerRuntime(p)
	}
	if onkir.FileHasStreamMethods(file) {
		writeSSEResponseHelper(p)
	}

	if fileHasHTTPRoutes(file) {
		writeTSNodeHTTPRuntime(p)
		p.P(tsFetchRouterSource)
	}
	writeTypedErrorHelpers(p, file)
	for _, s := range file.Services {
		writeHandlerInterface(p, s)
		writeRouteFactory(p, s)
		if serviceHasHTTPRoutes(s) {
			writeTSNodeRouteFactory(p, s)
			p.P("export function create", s.Name, "FetchHandler(handler: ", s.Name, "Handler): (req: Request) => Promise<Response> {")
			p.P("return fetchRouter(create", s.Name, "Routes(handler));")
			p.P("}")
			p.P()
		}
		if hasWS {
			writeTSSocketFactory(p, s)
			writeTSNodeSocketFactory(p, s)
		}
	}

	return p.Bytes()
}

func writeServerRuntime(p *Printer) {
	p.P("export class HttpError extends Error {")
	p.P("status: number;")
	p.P("body: unknown;")
	p.P("constructor(status: number, body: unknown) {")
	p.P("super(`http error ${status}`);")
	p.P("this.status = status;")
	p.P("this.body = body;")
	p.P("}")
	p.P("}")
	p.P()
	p.P("export interface RequestContext {")
	p.P("request: Request;")
	p.P("headers: Headers;")
	p.P("}")
	p.P()

	p.P("export interface RouteDescriptor {")
	p.P("method: string;")
	p.P("path: string;")
	p.P("handler: (req: Request) => Promise<Response>;")
	p.P("}")
	p.P()

	p.P("function matchPath(pattern: string, pathname: string): Record<string, string> | null {")
	p.P("const patternParts = pattern.split(\"/\").filter((s) => s.length > 0);")
	p.P("const pathParts = pathname.split(\"/\").filter((s) => s.length > 0);")
	p.P("if (patternParts.length !== pathParts.length) return null;")
	p.P("const params: Record<string, string> = {};")
	p.P("for (let i = 0; i < patternParts.length; i++) {")
	p.P("const part = patternParts[i] ?? \"\";")
	p.P("const actual = pathParts[i] ?? \"\";")
	p.P("if (part.startsWith(\"{\") && part.endsWith(\"}\")) {")
	p.P("params[part.slice(1, -1)] = decodeURIComponent(actual);")
	p.P("} else if (part !== actual) {")
	p.P("return null;")
	p.P("}")
	p.P("}")
	p.P("return params;")
	p.P("}")
	p.P()

	p.P("function jsonResponse(body: unknown, status = 200): Response {")
	p.P(`return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } });`)
	p.P("}")
	p.P()
	p.P("const maxRequestBodyBytes = 8 * 1024 * 1024;")
	p.P("async function readJSONBody(req: Request): Promise<unknown> {")
	p.P("const declaredLength = req.headers.get(\"content-length\");")
	p.P("if (declaredLength !== null && Number.isFinite(Number(declaredLength)) && Number(declaredLength) > maxRequestBodyBytes) throw new HttpError(413, { message: \"request body too large\" });")
	p.P("if (!req.body) return undefined;")
	p.P("const reader = req.body.getReader();")
	p.P("const chunks: Uint8Array[] = []; let total = 0;")
	p.P("while (true) {")
	p.P("const { done, value } = await reader.read();")
	p.P("if (done) break;")
	p.P("if (value) { total += value.byteLength; if (total > maxRequestBodyBytes) { await reader.cancel(); throw new HttpError(413, { message: \"request body too large\" }); } chunks.push(value); }")
	p.P("}")
	p.P("const bytes = new Uint8Array(total); let offset = 0;")
	p.P("for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; }")
	p.P("const text = new TextDecoder().decode(bytes);")
	p.P("if (text.trim() === \"\") return undefined;")
	p.P("try { return JSON.parse(text); } catch { throw new HttpError(400, { message: \"invalid request body\" }); }")
	p.P("}")
	p.P()

	p.P("function errorResponse(err: unknown): Response {")
	p.P("if (err instanceof HttpError) {")
	p.P("return jsonResponse(err.body, err.status);")
	p.P("}")
	p.P(`return jsonResponse({ message: "internal server error" }, 500);`)
	p.P("}")
	p.P()
	p.P("function parseScalar(value: string, kind: string, name: string): string | number | boolean {")
	p.P("if (kind === \"string\" || kind === \"bytes\" || kind === \"timestamp\") return value;")
	p.P("if (kind === \"bool\") {")
	p.P(`if (value === "true") return true;`)
	p.P(`if (value === "false") return false;`)
	p.P(`throw new HttpError(400, { message: "invalid " + name + ": must be true or false" });`)
	p.P("}")
	p.P("if (kind === \"int64\" || kind === \"uint64\") {")
	p.P("if (!/^-?(0|[1-9][0-9]*)$/.test(value) || (kind === \"uint64\" && value.startsWith(\"-\"))) throw new HttpError(400, { message: \"invalid \" + name });")
	p.P("try { const parsed = BigInt(value); const min = kind === \"int64\" ? -(2n ** 63n) : 0n; const max = kind === \"int64\" ? (2n ** 63n) - 1n : (2n ** 64n) - 1n; if (parsed < min || parsed > max) throw new Error(); } catch { throw new HttpError(400, { message: \"invalid \" + name }); }")
	p.P("return value;")
	p.P("}")
	p.P("const parsed = Number(value);")
	p.P("if (!Number.isFinite(parsed) || ((kind.startsWith(\"int\") || kind.startsWith(\"uint\")) && !Number.isInteger(parsed))) {")
	p.P(`throw new HttpError(400, { message: "invalid " + name });`)
	p.P("}")
	p.P(`if (kind === "int32" && (parsed < -2147483648 || parsed > 2147483647)) throw new HttpError(400, { message: "invalid " + name });`)
	p.P(`if (kind === "uint32" && (parsed < 0 || parsed > 4294967295)) throw new HttpError(400, { message: "invalid " + name });`)
	p.P(`if (kind.startsWith("uint") && parsed < 0) throw new HttpError(400, { message: "invalid " + name });`)
	p.P("return parsed;")
	p.P("}")
	p.P()
	p.P("function validHeaderFormat(value: string, format: string): boolean {")
	p.P(`if (format === "uuid") return /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/.test(value);`)
	p.P(`if (format === "email") return /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(value);`)
	p.P(`if (format === "uri") { try { new URL(value); return true; } catch { return false; } }`)
	p.P("return true;")
	p.P("}")
	p.P()
}

func writeHandlerInterface(p *Printer, s *onkir.Service) {
	p.P("export interface ", s.Name, "Handler {")
	for _, m := range s.Methods {
		switch {
		case m.IsWebSocket():
			outType := "WSOut<" + p.MessageTypeName(m.Response) + ">"
			if idField, ok := m.WSIDField(); ok {
				outType = "WSCallOut<" + p.TSFieldType(idField.Type) + ", " + p.MessageTypeName(m.Response) + ", " + p.MessageTypeName(m.Request) + ">"
			}
			p.P(CamelCase(m.Name), "(req: ", p.MessageTypeName(m.Request),
				", out: ", outType, "): void | Promise<void>;")
		case m.IsStream():
			writeSSEHandlerMethod(p, m)
		default:
			p.P(CamelCase(m.Name), "(req: ", p.MessageTypeName(m.Request),
				", context: RequestContext): Promise<", p.MessageTypeName(m.Response), ">;")
		}
	}
	p.P("}")
	p.P()
}

func writeRouteFactory(p *Printer, s *onkir.Service) {
	factoryName := "create" + s.Name + "Routes"
	p.P("export function ", factoryName, "(handler: ", s.Name, "Handler): RouteDescriptor[] {")
	p.P("return [")
	for _, m := range s.Methods {
		switch {
		case m.IsWebSocket():
			// Gets its own route via createXSocketRoutes (writeTSSocketFactory).
			continue
		case m.IsStream():
			writeSSERoute(p, s, m)
		default:
			writeRoute(p, s, m)
		}
	}
	p.P("];")
	p.P("}")
	p.P()
}

func writeRoute(p *Printer, s *onkir.Service, m *onkir.Method) {
	verb, _ := m.Verb()
	path, _ := m.Path()
	fullPath := s.BasePath + path
	bodyBearing := onkir.IsBodyBearingVerb(verb)
	hasPathParams := len(onkir.PathParamNames(path)) > 0

	p.P("{")
	p.P(fmt.Sprintf("method: %q,", strings.ToUpper(verb)))
	p.P(fmt.Sprintf("path: %q,", fullPath))
	p.P("handler: async (req: Request): Promise<Response> => {")

	if hasPathParams || !bodyBearing {
		p.P("const url = new URL(req.url);")
	}
	if hasPathParams {
		p.P(fmt.Sprintf("const match = matchPath(%q, url.pathname);", fullPath))
		p.P(`if (!match) return new Response("Not Found", { status: 404 });`)
	}

	p.P("try {")
	for _, header := range slices.Concat(s.Headers, m.Headers) {
		format, hasFormat := header.Format()
		p.P("{")
		p.P("const value = req.headers.get(", fmt.Sprintf("%q", header.Name), ");")
		if header.Required() {
			p.P("if (!value) throw new HttpError(400, { message: ", fmt.Sprintf("%q", "missing required header: "+header.Name), " });")
		}
		if hasFormat {
			p.P("if (value && !validHeaderFormat(value, ", fmt.Sprintf("%q", format), ")) throw new HttpError(400, { message: ", fmt.Sprintf("%q", "invalid header "+header.Name+": expected "+format), " });")
		}
		p.P("}")
	}
	p.P("let body: any = {};")
	if bodyBearing {
		if bodyField, ok := m.BodyField(); ok {
			p.P("body[", fmt.Sprintf("%q", bodyField), "] = await readJSONBody(req);")
		} else {
			p.P("body = (await readJSONBody(req)) ?? {};")
		}
	} else {
		writeServerQueryParams(p, m.Request)
	}
	if hasPathParams {
		for _, paramName := range onkir.PathParamNames(path) {
			field := onkir.FindField(m.Request, paramName)
			if field == nil {
				continue
			}
			if field.Type != nil && field.Type.Kind == onkir.KindScalar {
				p.P("body.", field.Name, " = parseScalar(match[", fmt.Sprintf("%q", paramName), "] ?? \"\", ", fmt.Sprintf("%q", field.Type.Scalar.String()), ", ", fmt.Sprintf("%q", "path parameter "+paramName), ");")
			} else {
				p.P("body.", field.Name, " = match[", fmt.Sprintf("%q", paramName), "] ?? \"\";")
			}
		}
	}

	p.P("const decoded = decode", m.Request.Name, "(body);")
	p.P("const violations = validate", m.Request.Name, "(decoded);")
	p.P("if (violations.length > 0) throw new HttpError(400, { message: violations.join(\"; \") });")
	p.P("const result = await handler.", CamelCase(m.Name), "(decoded, { request: req, headers: req.headers });")
	p.P("return jsonResponse(encode", m.Response.Name, "(result));")
	p.P("} catch (err) {")
	p.P("return errorResponse(err);")
	p.P("}")

	p.P("},")
	p.P("},")
}

func writeServerQueryParams(p *Printer, req *onkir.Message) {
	for _, field := range req.Fields {
		d, ok := field.Decorator("query")
		if !ok || field.Type == nil || field.Type.Kind != onkir.KindScalar {
			continue
		}
		queryName, _ := d.Value()
		if queryName == "" {
			queryName = field.Name
		}
		if field.Repeated {
			values := CamelCase(field.Name) + "Values"
			p.P(fmt.Sprintf("const %s = url.searchParams.getAll(%q);", values, queryName))
			p.P("if (", values, ".length > 0) {")
			p.P("body.", field.Name, " = ", values, ".map((value) => ", queryScalarConvert(field.Type.Scalar, "value", "query parameter "+queryName), ");")
			p.P("}")
			continue
		}
		p.P(fmt.Sprintf("const %s = url.searchParams.get(%q);", CamelCase(field.Name), queryName))
		p.P("if (", CamelCase(field.Name), " !== null) {")
		p.P("body.", field.Name, " = ", queryScalarConvert(field.Type.Scalar, CamelCase(field.Name), "query parameter "+queryName), ";")
		p.P("}")
	}
}

func queryScalarConvert(kind onkir.ScalarKind, expr, name string) string {
	return fmt.Sprintf("parseScalar(%s, %q, %q)", expr, kind.String(), name)
}

func serviceHasHTTPRoutes(s *onkir.Service) bool {
	for _, m := range s.Methods {
		if !m.IsWebSocket() {
			return true
		}
	}
	return false
}

func fileHasHTTPRoutes(file *onkir.File) bool {
	for _, s := range file.Services {
		if serviceHasHTTPRoutes(s) {
			return true
		}
	}
	return false
}

func writeTSNodeHTTPRuntime(p *Printer) {
	p.P("export type NodeRequestLike = AsyncIterable<Uint8Array | string> & {")
	p.P("method?: string | undefined;")
	p.P("url?: string | undefined;")
	p.P("headers: Record<string, string | string[] | undefined>;")
	p.P("};")
	p.P()
	p.P("export type NodeResponseLike = {")
	p.P("statusCode: number;")
	p.P("headersSent: boolean;")
	p.P("setHeader(name: string, value: string | string[]): unknown;")
	p.P("write(chunk: Uint8Array): unknown;")
	p.P("end(chunk?: Uint8Array | string): unknown;")
	p.P("writableEnded?: boolean;")
	p.P(`on?(event: "close", listener: () => void): unknown;`)
	p.P("};")
	p.P()
	p.P("export type NodeServerLike = {")
	p.P(`on(event: "request", listener: (req: NodeRequestLike, res: NodeResponseLike) => void): unknown;`)
	p.P("listenerCount(event: string): number;")
	p.P("};")
	p.P()
	p.P("export type NodeRequestHandler = (req: NodeRequestLike, res: NodeResponseLike) => boolean;")
	p.P()
	p.P("function nodeToFetchRequest(req: NodeRequestLike, url: URL, signal: AbortSignal): Request {")
	p.P("const headers = new Headers();")
	p.P("for (const [name, value] of Object.entries(req.headers)) {")
	p.P("if (Array.isArray(value)) { for (const v of value) headers.append(name, v); }")
	p.P("else if (value !== undefined) headers.set(name, value);")
	p.P("}")
	p.P(`const method = req.method ?? "GET";`)
	p.P(`if (method === "GET" || method === "HEAD") return new Request(url, { method, headers, signal });`)
	p.P("const chunks = req[Symbol.asyncIterator]();")
	p.P("const body = new ReadableStream<Uint8Array>({")
	p.P("async pull(controller) {")
	p.P("const next = await chunks.next();")
	p.P("if (next.done) { controller.close(); return; }")
	p.P(`controller.enqueue(typeof next.value === "string" ? new TextEncoder().encode(next.value) : next.value);`)
	p.P("},")
	p.P("async cancel() { await chunks.return?.(); },")
	p.P("});")
	p.P(`return new Request(url, { method, headers, body, signal, duplex: "half" } as RequestInit);`)
	p.P("}")
	p.P()
	p.P("async function writeFetchResponse(response: Response, res: NodeResponseLike, signal: AbortSignal): Promise<void> {")
	p.P("res.statusCode = response.status;")
	p.P(`const cookies = typeof response.headers.getSetCookie === "function" ? response.headers.getSetCookie() : [];`)
	p.P(`response.headers.forEach((value, name) => { if (name !== "set-cookie") res.setHeader(name, value); });`)
	p.P(`if (cookies.length > 0) res.setHeader("set-cookie", cookies);`)
	p.P("if (!response.body) { res.end(); return; }")
	p.P("const reader = response.body.getReader();")
	p.P("const stop = () => { reader.cancel().catch(() => {}); };")
	p.P(`if (signal.aborted) stop(); else signal.addEventListener("abort", stop, { once: true });`)
	p.P("for (;;) {")
	p.P("const { done, value } = await reader.read();")
	p.P("if (done) break;")
	p.P("res.write(value);")
	p.P("}")
	p.P("res.end();")
	p.P("}")
	p.P()
	p.P("function nodeRouteHandler(routes: RouteDescriptor[]): NodeRequestHandler {")
	p.P("return (req, res) => {")
	p.P("const host = req.headers.host;")
	p.P("let url: URL;")
	p.P(`try { url = new URL(req.url ?? "/", "http://" + (typeof host === "string" ? host : "localhost")); } catch { res.statusCode = 400; res.end(); return true; }`)
	p.P(`const method = req.method ?? "GET";`)
	p.P("const route = routes.find((r) => r.method === method && matchPath(r.path, url.pathname) !== null);")
	p.P("if (!route) return false;")
	p.P("const controller = new AbortController();")
	p.P(`res.on?.("close", () => { if (!res.writableEnded) controller.abort(); });`)
	p.P("route.handler(nodeToFetchRequest(req, url, controller.signal))")
	p.P(".then((response) => writeFetchResponse(response, res, controller.signal))")
	p.P(".catch(() => {")
	p.P("if (!res.headersSent) res.statusCode = 500;")
	p.P("res.end();")
	p.P("});")
	p.P("return true;")
	p.P("};")
	p.P("}")
	p.P()
	p.P(`const nodeRequestRoutesKey = Symbol.for("onekit.nodeRequestRoutes");`)
	p.P()
	p.P("function registerNodeRequestHandler(httpServer: NodeServerLike, route: NodeRequestHandler): void {")
	p.P("const holder = httpServer as unknown as Record<symbol, NodeRequestHandler[] | undefined>;")
	p.P("const existing = holder[nodeRequestRoutesKey];")
	p.P("if (existing) { existing.push(route); return; }")
	p.P("const routes: NodeRequestHandler[] = [route];")
	p.P("holder[nodeRequestRoutesKey] = routes;")
	p.P(`httpServer.on("request", (req, res) => {`)
	p.P("for (const r of routes) if (r(req, res)) return;")
	p.P(`if (httpServer.listenerCount("request") > 1) return;`)
	p.P("res.statusCode = 404;")
	p.P("res.end();")
	p.P("});")
	p.P("}")
	p.P()
}

func writeTSNodeRouteFactory(p *Printer, s *onkir.Service) {
	p.P("export function create", s.Name, "NodeHandler(handler: ", s.Name, "Handler): NodeRequestHandler {")
	p.P("return nodeRouteHandler(create", s.Name, "Routes(handler));")
	p.P("}")
	p.P()
	p.P("export function attach", s.Name, "NodeHandlers(httpServer: NodeServerLike, handler: ", s.Name, "Handler): void {")
	p.P("registerNodeRequestHandler(httpServer, create", s.Name, "NodeHandler(handler));")
	p.P("}")
	p.P()
}

const tsFetchRouterSource = `export function fetchRouter(routes: RouteDescriptor[]): (req: Request) => Promise<Response> {
return async (req: Request): Promise<Response> => {
const url = new URL(req.url);
const matching = routes.filter((route) => matchPath(route.path, url.pathname) !== null);
if (matching.length === 0) return jsonResponse({ message: "not found" }, 404);
const route = matching.find((candidate) => candidate.method === req.method);
if (route) return route.handler(req);
const allow = [...new Set(matching.map((candidate) => candidate.method))].join(", ");
if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: { Allow: allow } });
return new Response(JSON.stringify({ message: "method not allowed" }), { status: 405, headers: { "Content-Type": "application/json", Allow: allow } });
};
}
`
