package gents

import (
	"fmt"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

// serverCodecNames returns the decode<Request>/encode<Response|Error>
// function names this file's routes need from "./types" - the reverse
// direction from referencedCodecNames (client.go), since a server decodes
// incoming requests and encodes outgoing responses.
func serverCodecNames(file *onkir.File, resolver PackageResolver) []string {
	seen := map[string]bool{}
	var names []string
	add := func(prefix string, m *onkir.Message) {
		if !isLocalMessage(resolver, m) {
			return
		}
		key := prefix + m.Name
		if !seen[key] {
			seen[key] = true
			names = append(names, key)
		}
	}
	for _, s := range file.Services {
		for _, m := range s.Methods {
			add("decode", m.Request)
			add("validate", m.Request)
			add("encode", m.Response)
		}
	}
	return names
}

// GenerateServer generates server.ts treating every message/enum type as
// local. Use GenerateServerWithResolver for a multi-package project where
// some referenced types live in a different generated module.
func GenerateServer(file *onkir.File) []byte {
	return GenerateServerWithResolver(file, nil)
}

func GenerateServerWithResolver(file *onkir.File, resolver PackageResolver) []byte {
	if len(file.Services) == 0 {
		return nil
	}

	p := newPrinter(resolver)
	p.P("// Code generated by onek. DO NOT EDIT.")
	if names := referencedTypeNames(file, resolver); len(names) > 0 {
		p.P(`import type { `, strings.Join(names, ", "), ` } from "./types";`)
	}
	if fns := serverCodecNames(file, resolver); len(fns) > 0 {
		p.P(`import { `, strings.Join(fns, ", "), ` } from "./types";`)
	}
	for _, ref := range collectServiceExternalRefs(file, resolver) {
		p.P(`import * as `, ref.Alias, ` from "`, ref.ImportPath, `";`)
	}
	p.P()

	writeServerRuntime(p)
	if fileHasStreamMethods(file) {
		writeSSEResponseHelper(p)
	}

	for _, s := range file.Services {
		writeHandlerInterface(p, s)
		writeRouteFactory(p, s)
	}

	return p.Bytes()
}

func writeServerRuntime(p *Printer) {
	p.P("export class HttpError extends Error {")
	p.P("status: number;")
	p.P("body: unknown;")
	p.P("constructor(status: number, body: unknown) {")
	p.P("super(`http error ${status}`);")
	p.P("this.status = status;")
	p.P("this.body = body;")
	p.P("}")
	p.P("}")
	p.P()
	p.P("export interface RequestContext {")
	p.P("request: Request;")
	p.P("headers: Headers;")
	p.P("}")
	p.P()

	p.P("export interface RouteDescriptor {")
	p.P("method: string;")
	p.P("path: string;")
	p.P("handler: (req: Request) => Promise<Response>;")
	p.P("}")
	p.P()

	p.P("function matchPath(pattern: string, pathname: string): Record<string, string> | null {")
	p.P("const patternParts = pattern.split(\"/\").filter((s) => s.length > 0);")
	p.P("const pathParts = pathname.split(\"/\").filter((s) => s.length > 0);")
	p.P("if (patternParts.length !== pathParts.length) return null;")
	p.P("const params: Record<string, string> = {};")
	p.P("for (let i = 0; i < patternParts.length; i++) {")
	p.P("const part = patternParts[i];")
	p.P("if (part.startsWith(\"{\") && part.endsWith(\"}\")) {")
	p.P("params[part.slice(1, -1)] = decodeURIComponent(pathParts[i]);")
	p.P("} else if (part !== pathParts[i]) {")
	p.P("return null;")
	p.P("}")
	p.P("}")
	p.P("return params;")
	p.P("}")
	p.P()

	p.P("function jsonResponse(body: unknown, status = 200): Response {")
	p.P(`return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } });`)
	p.P("}")
	p.P()
	p.P("const maxRequestBodyBytes = 8 * 1024 * 1024;")
	p.P("async function readJSONBody(req: Request): Promise<unknown> {")
	p.P("const declaredLength = req.headers.get(\"content-length\");")
	p.P("if (declaredLength !== null && Number.isFinite(Number(declaredLength)) && Number(declaredLength) > maxRequestBodyBytes) throw new Error(\"request body too large\");")
	p.P("if (!req.body) throw new Error(\"request body is missing\");")
	p.P("const reader = req.body.getReader();")
	p.P("const chunks: Uint8Array[] = []; let total = 0;")
	p.P("while (true) {")
	p.P("const { done, value } = await reader.read();")
	p.P("if (done) break;")
	p.P("if (value) { total += value.byteLength; if (total > maxRequestBodyBytes) { await reader.cancel(); throw new Error(\"request body too large\"); } chunks.push(value); }")
	p.P("}")
	p.P("const bytes = new Uint8Array(total); let offset = 0;")
	p.P("for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; }")
	p.P("return JSON.parse(new TextDecoder().decode(bytes));")
	p.P("}")
	p.P()

	p.P("function errorResponse(err: unknown): Response {")
	p.P("if (err instanceof HttpError) {")
	p.P("return jsonResponse(err.body, err.status);")
	p.P("}")
	p.P(`return jsonResponse({ message: "internal server error" }, 500);`)
	p.P("}")
	p.P()
	p.P("function parseScalar(value: string, kind: string, name: string): string | number | boolean {")
	p.P("if (kind === \"string\" || kind === \"bytes\" || kind === \"timestamp\") return value;")
	p.P("if (kind === \"bool\") {")
	p.P(`if (value === "true") return true;`)
	p.P(`if (value === "false") return false;`)
	p.P(`throw new HttpError(400, { message: "invalid " + name + ": must be true or false" });`)
	p.P("}")
	p.P("if (kind === \"int64\" || kind === \"uint64\") {")
	p.P("if (!/^-?(0|[1-9][0-9]*)$/.test(value) || (kind === \"uint64\" && value.startsWith(\"-\"))) throw new HttpError(400, { message: \"invalid \" + name });")
	p.P("try { const parsed = BigInt(value); const min = kind === \"int64\" ? -(2n ** 63n) : 0n; const max = kind === \"int64\" ? (2n ** 63n) - 1n : (2n ** 64n) - 1n; if (parsed < min || parsed > max) throw new Error(); } catch { throw new HttpError(400, { message: \"invalid \" + name }); }")
	p.P("return value;")
	p.P("}")
	p.P("const parsed = Number(value);")
	p.P("if (!Number.isFinite(parsed) || ((kind.startsWith(\"int\") || kind.startsWith(\"uint\")) && !Number.isInteger(parsed))) {")
	p.P(`throw new HttpError(400, { message: "invalid " + name });`)
	p.P("}")
	p.P(`if (kind === "int32" && (parsed < -2147483648 || parsed > 2147483647)) throw new HttpError(400, { message: "invalid " + name });`)
	p.P(`if (kind === "uint32" && (parsed < 0 || parsed > 4294967295)) throw new HttpError(400, { message: "invalid " + name });`)
	p.P(`if (kind.startsWith("uint") && parsed < 0) throw new HttpError(400, { message: "invalid " + name });`)
	p.P("return parsed;")
	p.P("}")
	p.P()
	p.P("function validHeaderFormat(value: string, format: string): boolean {")
	p.P(`if (format === "uuid") return /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/.test(value);`)
	p.P(`if (format === "email") return /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(value);`)
	p.P(`if (format === "uri") { try { new URL(value); return true; } catch { return false; } }`)
	p.P("return true;")
	p.P("}")
	p.P()
}

func writeHandlerInterface(p *Printer, s *onkir.Service) {
	p.P("export interface ", s.Name, "Handler {")
	for _, m := range s.Methods {
		if m.IsStream() {
			writeSSEHandlerMethod(p, m)
		} else {
			p.P(CamelCase(m.Name), "(req: ", p.MessageTypeName(m.Request),
				", context: RequestContext): Promise<", p.MessageTypeName(m.Response), ">;")
		}
	}
	p.P("}")
	p.P()
}

func writeRouteFactory(p *Printer, s *onkir.Service) {
	factoryName := "create" + s.Name + "Routes"
	p.P("export function ", factoryName, "(handler: ", s.Name, "Handler): RouteDescriptor[] {")
	p.P("return [")
	for _, m := range s.Methods {
		if m.IsStream() {
			writeSSERoute(p, s, m)
		} else {
			writeRoute(p, s, m)
		}
	}
	p.P("];")
	p.P("}")
	p.P()
}

func writeRoute(p *Printer, s *onkir.Service, m *onkir.Method) {
	verb, _ := m.Verb()
	path, _ := m.Path()
	fullPath := s.BasePath + path
	bodyBearing := isBodyBearingVerb(verb)
	hasPathParams := len(pathParamNames(path)) > 0

	p.P("{")
	p.P(fmt.Sprintf("method: %q,", strings.ToUpper(verb)))
	p.P(fmt.Sprintf("path: %q,", fullPath))
	p.P("handler: async (req: Request): Promise<Response> => {")

	if hasPathParams || !bodyBearing {
		p.P("const url = new URL(req.url);")
	}
	if hasPathParams {
		p.P(fmt.Sprintf("const match = matchPath(%q, url.pathname);", fullPath))
		p.P(`if (!match) return new Response("Not Found", { status: 404 });`)
	}

	p.P("try {")
	for _, header := range append(append([]*onkir.Header{}, s.Headers...), m.Headers...) {
		format, hasFormat := header.Format()
		p.P("{")
		p.P("const value = req.headers.get(", fmt.Sprintf("%q", header.Name), ");")
		if header.Required() {
			p.P("if (!value) throw new HttpError(400, { message: ", fmt.Sprintf("%q", "missing required header: "+header.Name), " });")
		}
		if hasFormat {
			p.P("if (value && !validHeaderFormat(value, ", fmt.Sprintf("%q", format), ")) throw new HttpError(400, { message: ", fmt.Sprintf("%q", "invalid header "+header.Name+": expected "+format), " });")
		}
		p.P("}")
	}
	p.P("let body: any = {};")
	if bodyBearing {
		p.P("try {")
		if bodyField, ok := m.BodyField(); ok {
			p.P("body[", fmt.Sprintf("%q", bodyField), "] = await readJSONBody(req);")
		} else {
			p.P("body = await readJSONBody(req);")
		}
		p.P("} catch {")
		p.P(`throw new HttpError(400, { message: "invalid request body" });`)
		p.P("}")
	} else {
		writeServerQueryParams(p, m.Request)
	}
	if hasPathParams {
		for _, paramName := range pathParamNames(path) {
			field := findField(m.Request, paramName)
			if field == nil {
				continue
			}
			if field.Type != nil && field.Type.Kind == onkir.KindScalar {
				p.P("body.", field.Name, " = parseScalar(match.", paramName, ", ", fmt.Sprintf("%q", field.Type.Scalar.String()), ", ", fmt.Sprintf("%q", "path parameter "+paramName), ");")
			} else {
				p.P("body.", field.Name, " = match.", paramName, ";")
			}
		}
	}

	p.P("const decoded = decode", m.Request.Name, "(body);")
	p.P("const violations = validate", m.Request.Name, "(decoded);")
	p.P("if (violations.length > 0) throw new HttpError(400, { message: violations.join(\"; \") });")
	p.P("const result = await handler.", CamelCase(m.Name), "(decoded, { request: req, headers: req.headers });")
	p.P("return jsonResponse(encode", m.Response.Name, "(result));")
	p.P("} catch (err) {")
	p.P("return errorResponse(err);")
	p.P("}")

	p.P("},")
	p.P("},")
}

func writeServerQueryParams(p *Printer, req *onkir.Message) {
	for _, field := range req.Fields {
		d, ok := field.Decorator("query")
		if !ok || field.Type == nil || field.Type.Kind != onkir.KindScalar {
			continue
		}
		queryName, _ := d.Value()
		if queryName == "" {
			queryName = field.Name
		}
		if field.Repeated {
			values := CamelCase(field.Name) + "Values"
			p.P(fmt.Sprintf("const %s = url.searchParams.getAll(%q);", values, queryName))
			p.P("if (", values, ".length > 0) {")
			p.P("body.", field.Name, " = ", values, ".map((value) => ", queryScalarConvert(field.Type.Scalar, "value", "query parameter "+queryName), ");")
			p.P("}")
			continue
		}
		p.P(fmt.Sprintf("const %s = url.searchParams.get(%q);", CamelCase(field.Name), queryName))
		p.P("if (", CamelCase(field.Name), " !== null) {")
		p.P("body.", field.Name, " = ", queryScalarConvert(field.Type.Scalar, CamelCase(field.Name), "query parameter "+queryName), ";")
		p.P("}")
	}
}

func queryScalarConvert(kind onkir.ScalarKind, expr, name string) string {
	return fmt.Sprintf("parseScalar(%s, %q, %q)", expr, kind.String(), name)
}
