package gents

import (
	"fmt"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

// GenerateTypes generates types.ts treating every message/enum type as
// local. Use GenerateTypesWithResolver for a multi-package project where some
// referenced types live in a different generated module.
func GenerateTypes(file *onkir.File) []byte {
	return GenerateTypesWithResolver(file, nil)
}

func GenerateTypesWithResolver(file *onkir.File, resolver PackageResolver) []byte {
	p := newPrinter(resolver)
	p.P("// Code generated by onek. DO NOT EDIT.")
	for _, ref := range collectExternalRefs(file, resolver) {
		p.P(`import * as `, ref.Alias, ` from "`, ref.ImportPath, `";`)
	}
	p.P()

	for _, e := range file.Enums {
		writeEnum(p, e)
	}
	for _, m := range file.Messages {
		writeMessage(p, m)
	}

	return p.Bytes()
}

func writeEnum(p *Printer, e *onkir.Enum) {
	var values []string
	for _, v := range e.Values {
		values = append(values, fmt.Sprintf("%q", v.JSONName()))
	}
	p.P("export type ", e.Name, " = ", strings.Join(values, " | "), ";")
	p.P()
}

// fieldWireTSType is the TypeScript type of a field's wire representation:
// this is what actually crosses the network, which for int64/enum/timestamp
// fields can differ from their "natural" TS type based on the @encode
// decorator (see jsonmapping.go).
func (p *Printer) fieldWireTSType(f *onkir.Field) string {
	if f.Type == nil {
		return tsTypeUnknown
	}
	switch f.Type.Kind {
	case onkir.KindScalar:
		return p.scalarWireTSType(f)
	case onkir.KindEnum:
		if needsEnumNumberEncoding(f) {
			return tsTypeNumber
		}
		return p.EnumTypeName(f.Type.Enum)
	case onkir.KindMessage, onkir.KindMap:
		return p.TSFieldType(f.Type)
	default:
		return p.TSFieldType(f.Type)
	}
}

func (p *Printer) scalarWireTSType(f *onkir.Field) string {
	switch f.Type.Scalar {
	case onkir.ScalarInt64, onkir.ScalarUint64:
		if needsInt64NumberEncoding(f) {
			return tsTypeNumber
		}
		return tsTypeString
	case onkir.ScalarTimestamp:
		switch timestampEncodingValue(f) {
		case timestampEncodeUnixSeconds, timestampEncodeUnixMillis:
			return tsTypeNumber
		default:
			return tsTypeString
		}
	case onkir.ScalarString, onkir.ScalarBool, onkir.ScalarInt32, onkir.ScalarUint32,
		onkir.ScalarFloat32, onkir.ScalarFloat64, onkir.ScalarBytes:
		return TSScalarType(f.Type.Scalar)
	default:
		return TSScalarType(f.Type.Scalar)
	}
}

func writeMessage(p *Printer, m *onkir.Message) {
	if field := rootUnwrapField(m); field != nil {
		tsType := p.fieldWireTSType(field)
		if field.Repeated {
			tsType = "(" + tsType + ")[]"
		}
		p.P("export type ", m.Name, " = ", tsType, ";")
		p.P()
		for _, nested := range m.Nested {
			writeMessage(p, nested)
		}
		for _, nested := range m.NestedEnums {
			writeEnum(p, nested)
		}
		return
	}

	p.P("export interface ", m.Name, " {")
	for _, f := range m.Fields {
		writeField(p, m, f, "")
	}
	p.P("}")
	p.P()

	writeDecodeFunc(p, m)
	writeEncodeFunc(p, m)

	for _, f := range m.Fields {
		if f.Oneof != nil {
			writeOneof(p, m, f)
		}
	}
	for _, nested := range m.Nested {
		writeMessage(p, nested)
	}
	for _, nested := range m.NestedEnums {
		writeEnum(p, nested)
	}
}

// writeField emits one TS interface property. wirePrefix is threaded through
// as raw snake_case (not yet camelCased) by writeFlattenedFields, since a
// flattened field's property name is
// CamelCase(prefix+field) as ONE identifier, not CamelCase(prefix) followed
// by CamelCase(field) concatenated - camelCasing each segment separately
// would wrongly lowercase the join point (e.g. "billingstreet" instead of
// "billingStreet"). Its wire key is the same prefix+field, just left in
// snake_case.
func writeField(p *Printer, m *onkir.Message, f *onkir.Field, wirePrefix string) {
	if f.Oneof != nil {
		p.P(CamelCase(wirePrefix+f.Name), "?: ", OneofTypeName(m, f), ";")
		return
	}
	if prefix, ok := flattenPrefix(f); ok {
		writeFlattenedFields(p, f.Type.Message, wirePrefix+prefix)
		return
	}

	tsType := p.fieldWireTSType(f)
	if f.Repeated {
		tsType = "(" + tsType + ")[]"
	}
	if emptyBehaviorValue(f) == emptyBehaviorNull {
		tsType += " | null"
	}
	p.P(CamelCase(wirePrefix+f.Name), "?: ", tsType, ";")
}

func writeFlattenedFields(p *Printer, child *onkir.Message, wirePrefix string) {
	for _, f := range child.Fields {
		writeField(p, child, f, wirePrefix)
	}
}

// wireKey returns a field's JSON wire key - always the raw snake_case name
// as declared in .onk (or, under a @flatten prefix, wirePrefix+name) -
// independent of its camelCase TS property name.
func wireKey(wirePrefix string, f *onkir.Field) string {
	return wirePrefix + f.Name
}

// tsKey returns a field's camelCase TS property name, computed by combining
// the (snake_case) wire prefix and field name into one string BEFORE
// camelCasing it - see the note on writeField for why this can't be done by
// camelCasing each segment separately and concatenating the results.
func tsKey(wirePrefix string, f *onkir.Field) string {
	return CamelCase(wirePrefix + f.Name)
}

// codecFieldPlan is one leaf field to encode/decode, with both of its names
// resolved - "leaf" in both the Go and @flatten senses, since a flattened
// child's own fields are inlined here directly, with combined names,
// matching the shape writeField/writeFlattenedFields already produce in the
// TS interface itself.
type codecFieldPlan struct {
	field *onkir.Field
	wire  string
	ts    string
}

func collectCodecFields(m *onkir.Message, wirePrefix string) []codecFieldPlan {
	var out []codecFieldPlan
	for _, f := range m.Fields {
		if f.Oneof != nil {
			out = append(
				out,
				codecFieldPlan{field: f, wire: wireKey(wirePrefix, f), ts: tsKey(wirePrefix, f)},
			)
			continue
		}
		if prefix, ok := flattenPrefix(f); ok {
			out = append(out, collectCodecFields(f.Type.Message, wirePrefix+prefix)...)
			continue
		}
		out = append(out, codecFieldPlan{field: f, wire: wireKey(wirePrefix, f), ts: tsKey(wirePrefix, f)})
	}
	return out
}

func writeDecodeFunc(p *Printer, m *onkir.Message) {
	p.P("export function decode", m.Name, "(v: any): ", m.Name, " {")
	p.P("if (v === null || v === undefined) return v;")
	p.P("return {")
	for _, cf := range collectCodecFields(m, "") {
		p.P(cf.ts, ": ", decodeExpr(p, cf.field, "v."+cf.wire), ",")
	}
	p.P("};")
	p.P("}")
	p.P()
}

func writeEncodeFunc(p *Printer, m *onkir.Message) {
	p.P("export function encode", m.Name, "(v: ", m.Name, "): Record<string, unknown> {")
	p.P("const out: Record<string, unknown> = {};")
	for _, cf := range collectCodecFields(m, "") {
		valueExpr := "v." + cf.ts
		behavior := emptyBehaviorValue(cf.field)
		if behavior != "" && behavior != emptyBehaviorPreserve {
			// Bound to a local const (rather than repeating the v.field
			// member expression) so TS's control-flow narrowing reliably
			// excludes null/undefined by the time encodeExpr's call is
			// type-checked - narrowing through a bare property access isn't
			// always as robust across a multi-branch condition.
			localVar := cf.ts + "Val"
			p.P("const ", localVar, " = ", valueExpr, ";")
			p.P("if (", localVar, " !== undefined) {")
			p.P("if (", localVar, " === null || JSON.stringify(", localVar, ") === \"{}\") {")
			if behavior == emptyBehaviorNull {
				p.P("out.", cf.wire, " = null;")
			}
			p.P("} else {")
			p.P("out.", cf.wire, " = ", encodeExpr(p, cf.field, localVar), ";")
			p.P("}")
			p.P("}")
			if behavior == emptyBehaviorNull {
				p.P("else { out.", cf.wire, " = null; }")
			}
			continue
		}
		p.P(
			"if (",
			valueExpr,
			" !== undefined) { out.",
			cf.wire,
			" = ",
			encodeExpr(p, cf.field, valueExpr),
			"; }",
		)
	}
	p.P("return out;")
	p.P("}")
	p.P()
}

// decodeExpr/encodeExpr return a TS expression converting one field's value
// between its wire shape (JSON, snake_case keys) and TS shape (camelCase
// keys), recursing into message/repeated/map fields. Scalars and enums never
// need a value transform - only their key changes, which the caller already
// handles - so they pass through unchanged.
func decodeExpr(p *Printer, f *onkir.Field, expr string) string {
	if f.Oneof != nil {
		return decodeOneofExpr(p, f)
	}
	if f.Type == nil {
		return expr
	}
	switch f.Type.Kind {
	case onkir.KindMessage:
		fn := p.MessageCodecName(f.Type.Message, "decode")
		if f.Repeated {
			return fmt.Sprintf("(%s !== undefined ? (%s as any[]).map(%s) : %s)", expr, expr, fn, expr)
		}
		return fmt.Sprintf("(%s !== undefined ? %s(%s) : %s)", expr, fn, expr, expr)
	case onkir.KindMap:
		if f.Type.MapValue.Kind == onkir.KindMessage {
			fn := p.MessageCodecName(f.Type.MapValue.Message, "decode")
			return fmt.Sprintf(
				"(%s !== undefined ? Object.fromEntries(Object.entries(%s as Record<string, any>).map(([k, val]) => [k, %s(val)])) : %s)",
				expr,
				expr,
				fn,
				expr,
			)
		}
		return expr
	case onkir.KindScalar, onkir.KindEnum:
		return expr
	default:
		return expr
	}
}

func encodeExpr(p *Printer, f *onkir.Field, expr string) string {
	if f.Oneof != nil {
		return encodeOneofExpr(p, f, expr)
	}
	if f.Type == nil {
		return expr
	}
	switch f.Type.Kind {
	case onkir.KindMessage:
		fn := p.MessageCodecName(f.Type.Message, "encode")
		if f.Repeated {
			return fmt.Sprintf("(%s as any[]).map(%s)", expr, fn)
		}
		return fmt.Sprintf("%s(%s)", fn, expr)
	case onkir.KindMap:
		if f.Type.MapValue.Kind == onkir.KindMessage {
			fn := p.MessageCodecName(f.Type.MapValue.Message, "encode")
			return fmt.Sprintf(
				"Object.fromEntries(Object.entries(%s as Record<string, any>).map(([k, val]) => [k, %s(val)]))",
				expr,
				fn,
			)
		}
		return expr
	case onkir.KindScalar, onkir.KindEnum:
		return expr
	default:
		return expr
	}
}

func oneofDiscriminatorKey(f *onkir.Field) string {
	disc, ok := f.Oneof.Discriminator()
	if !ok || disc == "" {
		disc = "type"
	}
	return disc
}

// decodeOneofExpr/encodeOneofExpr convert a oneof field's wire shape
// (discriminator field, then either a sibling field named after the variant
// or - if flattened - the variant's fields inlined alongside the
// discriminator) into/from the TS discriminated-union shape. A oneof's
// variant data lives as sibling keys of the enclosing wire object (not
// nested under the oneof field's own key), so both read directly off "v"
// rather than off a per-field wire expression.
func decodeOneofExpr(p *Printer, f *onkir.Field) string {
	disc := oneofDiscriminatorKey(f)
	flatten := f.Oneof.Flatten()
	var b strings.Builder
	fmt.Fprintf(&b, "((): %s | undefined => {\n", OneofTypeName(f.Message, f))
	fmt.Fprintf(&b, "switch (v.%s) {\n", disc)
	for _, variant := range f.Oneof.Variants {
		tag := variant.Tag()
		variantKey := variant.Name
		decoded := decodeExpr(
			p,
			&onkir.Field{Type: variant.Type, Message: f.Message},
			fmt.Sprintf("v.%s", variantKey),
		)
		if flatten {
			fmt.Fprintf(&b, "case %q: return { %s: v.%s, ...%s };\n", tag, disc, disc, decoded)
		} else {
			fmt.Fprintf(&b, "case %q: return { %s: v.%s, %s: %s };\n", tag, disc, disc, CamelCase(variantKey), decoded)
		}
	}
	b.WriteString("default: return undefined;\n")
	b.WriteString("}\n")
	b.WriteString("})()")
	return b.String()
}

func encodeOneofExpr(p *Printer, f *onkir.Field, expr string) string {
	disc := oneofDiscriminatorKey(f)
	flatten := f.Oneof.Flatten()
	var b strings.Builder
	b.WriteString("((): Record<string, unknown> => {\n")
	fmt.Fprintf(&b, "const ov: any = %s;\n", expr)
	b.WriteString("if (ov === undefined) return {};\n")
	fmt.Fprintf(&b, "switch (ov.%s) {\n", disc)
	for _, variant := range f.Oneof.Variants {
		tag := variant.Tag()
		variantKey := variant.Name
		var valueExpr string
		if flatten {
			valueExpr = "ov"
		} else {
			valueExpr = "ov." + CamelCase(variantKey)
		}
		encoded := encodeExpr(p, &onkir.Field{Type: variant.Type, Message: f.Message}, valueExpr)
		fmt.Fprintf(&b, "case %q: return { %s: %q, %s: %s };\n", tag, disc, tag, variantKey, encoded)
	}
	b.WriteString("default: return {};\n")
	b.WriteString("}\n")
	b.WriteString("})()")
	return b.String()
}

func writeOneof(p *Printer, m *onkir.Message, f *onkir.Field) {
	discriminator := oneofDiscriminatorKey(f)
	flatten := f.Oneof.Flatten()

	var variants []string
	for _, v := range f.Oneof.Variants {
		tag := v.Tag()
		tsType := p.TSFieldType(v.Type)
		if flatten {
			variants = append(variants, fmt.Sprintf("({ %s: %q } & %s)", discriminator, tag, tsType))
		} else {
			variantField := CamelCase(v.Name)
			variants = append(variants, fmt.Sprintf("{ %s: %q; %s: %s }", discriminator, tag, variantField, tsType))
		}
	}

	p.P("export type ", OneofTypeName(m, f), " =")
	p.P("  | ", strings.Join(variants, "\n  | "), ";")
	p.P()
}
