package gents

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

// GenerateZod generates schemas.ts treating every message/enum type as
// local. Use GenerateZodWithResolver for a multi-package project where some
// referenced types live in a different generated module.
//
// The emitted schemas mirror the exact wire representation and server-side
// validation rules (see the runtime checks in types.go): forms and API
// boundaries validate against the same contract the generated Go server
// enforces, from a single source of truth.
func GenerateZod(file *onkir.File) []byte {
	return GenerateZodWithResolver(file, nil)
}

func GenerateZodWithResolver(file *onkir.File, resolver PackageResolver) []byte {
	p := newPrinter(resolver)
	p.P("// Code generated by onek. DO NOT EDIT.")
	p.P(`import { z } from "zod";`)
	for _, ref := range collectZodExternalRefs(file, resolver) {
		p.P(`import * as `, ref.Alias, ` from "`, ref.ImportPath, `";`)
	}
	p.P()

	for _, e := range file.Enums {
		writeZodEnum(p, e)
	}
	for _, m := range file.Messages {
		writeZodMessage(p, m)
	}

	return p.Bytes()
}

// zodSchemaRef references another message's exported schema, qualifying it
// through the package resolver for cross-module generation.
func (p *Printer) zodSchemaRef(m *onkir.Message) string {
	if p.resolver != nil {
		if ref, ok := p.resolver.ResolveMessage(m); ok {
			return ref.Alias + "." + m.Name + "Schema"
		}
	}
	return m.Name + "Schema"
}

// zodEnumRef is zodSchemaRef's counterpart for enums.
func (p *Printer) zodEnumRef(e *onkir.Enum) string {
	if p.resolver != nil {
		if ref, ok := p.resolver.ResolveEnum(e); ok {
			return ref.Alias + "." + e.Name + "Schema"
		}
	}
	return e.Name + "Schema"
}

// zodNumberEnumSchema is the wire schema for @encode(number) enum fields:
// the value crosses the network as its declaration index.
func zodNumberEnumSchema(e *onkir.Enum) string {
	return fmt.Sprintf("z.number().int().gte(0).lte(%d)", len(e.Values)-1)
}

func writeZodEnum(p *Printer, e *onkir.Enum) {
	var values []string
	for _, v := range e.Values {
		values = append(values, fmt.Sprintf("%q", v.JSONName()))
	}
	p.P("export const ", e.Name, "Schema = z.enum([", strings.Join(values, ", "), "]);")
	p.P()
}

func writeZodMessage(p *Printer, m *onkir.Message) {
	if field := rootUnwrapField(m); field != nil {
		expr := zodValueSchema(p, field)
		if field.Repeated {
			expr = "z.array(" + expr + ")"
		}
		p.P("export const ", m.Name, "Schema = ", expr, ";")
		p.P()
		writeZodNested(p, m)
		return
	}

	p.P("export const ", m.Name, "Schema = z.object({")
	for _, plan := range collectCodecFields(m, "") {
		p.P(plan.ts, ": ", zodFieldSchema(p, plan.field), ",")
	}
	p.P("});")
	p.P()

	for _, f := range m.Fields {
		if f.Oneof != nil {
			writeZodOneof(p, m, f)
		}
	}
	writeZodNested(p, m)
}

func writeZodNested(p *Printer, m *onkir.Message) {
	for _, nested := range m.Nested {
		writeZodMessage(p, nested)
	}
	for _, nested := range m.NestedEnums {
		writeZodEnum(p, nested)
	}
}

// writeZodOneof mirrors the wire shape produced by writeOneof: a
// discriminator key holding the variant tag plus either a named payload
// property or, when flattened, the variant's fields inlined into the same
// object.
func writeZodOneof(p *Printer, m *onkir.Message, f *onkir.Field) {
	discriminator := oneofDiscriminatorKey(f)
	flatten := f.Oneof.Flatten()

	var variants []string
	for _, v := range f.Oneof.Variants {
		tag := v.Tag()
		payload := zodTypeRefSchema(p, v.Type)
		if flatten {
			variants = append(variants,
				fmt.Sprintf("z.object({ %s: z.literal(%q) }).and(%s)", discriminator, tag, payload))
			continue
		}
		variants = append(variants,
			fmt.Sprintf("z.object({ %s: z.literal(%q), %s: %s })",
				discriminator, tag, CamelCase(v.Name), payload))
	}

	joined := strings.Join(variants, ", ")
	name := OneofTypeName(m, f)
	if discriminator != "" {
		p.P("export const ", name, "Schema = z.discriminatedUnion(", strconv.Quote(discriminator), ", ", joined, ");")
	} else {
		p.P("export const ", name, "Schema = z.union([", joined, "]);")
	}
	p.P()
}

// zodFieldSchema composes one object property: the value schema wrapped for
// repetition (@min_items/@max_items), nullability (@empty(null)), presence
// (? -> .optional()), and required-string non-emptiness.
func zodFieldSchema(p *Printer, f *onkir.Field) string {
	inner := zodValueSchema(p, f)
	var expr string
	switch {
	case f.Repeated:
		expr = "z.array(" + inner + ")"
		if d, ok := f.Decorator("min_items"); ok {
			value, _ := d.Value()
			expr += ".min(" + value + ")"
		}
		if d, ok := f.Decorator("max_items"); ok {
			value, _ := d.Value()
			expr += ".max(" + value + ")"
		}
	default:
		expr = inner
	}
	if emptyBehaviorValue(f) == emptyBehaviorNull {
		expr += ".nullable()"
	}
	if f.Optional {
		expr += ".optional()"
	}
	return expr
}

// zodValueSchema maps one (non-repeated) field value to its Zod expression,
// honoring field-level @encode choices before delegating to the bare type.
func zodValueSchema(p *Printer, f *onkir.Field) string {
	switch {
	case f.Oneof != nil:
		return OneofTypeName(f.Message, f) + "Schema"
	case f.Type == nil:
		return zodUnknownSchema
	case f.Type.Kind == onkir.KindEnum && needsEnumNumberEncoding(f):
		return zodNumberEnumSchema(f.Type.Enum)
	case f.Type.Kind == onkir.KindScalar && f.Type.Scalar == onkir.ScalarInt64 && needsInt64NumberEncoding(f),
		f.Type.Kind == onkir.KindScalar && f.Type.Scalar == onkir.ScalarUint64 && needsInt64NumberEncoding(f):
		return "z.number().int().gte(Number.MIN_SAFE_INTEGER).lte(Number.MAX_SAFE_INTEGER)"
	case f.Type.Kind == onkir.KindScalar && f.Type.Scalar == onkir.ScalarTimestamp:
		switch timestampEncodingValue(f) {
		case timestampEncodeUnixSeconds, timestampEncodeUnixMillis:
			return "z.number()"
		}
	case f.Type.Kind == onkir.KindScalar && f.Type.Scalar == onkir.ScalarInt64,
		f.Type.Kind == onkir.KindScalar && f.Type.Scalar == onkir.ScalarUint64:
		// default string encoding falls through to the type-level mapping
	default:
		if prefix, ok := flattenPrefix(f); ok {
			// Flattened children are merged by collectCodecFields; this only
			// runs for hand-built plans that bypass that walker.
			_ = prefix
			return zodUnknownSchema
		}
	}
	if f.Type != nil && f.Type.Kind == onkir.KindScalar && f.Type.Scalar == onkir.ScalarString {
		return zodConstrainedString(f)
	}
	return zodTypeRefSchema(p, f.Type)
}

// zodConstrainedString builds a string schema from the validation
// decorators. @in replaces the base entirely because it pins the exact
// allowed values; the rest refine z.string().
func zodConstrainedString(f *onkir.Field) string {
	if d, ok := f.Decorator("in"); ok {
		values := make([]string, 0, len(d.Args))
		for _, arg := range d.Args {
			values = append(values, strconv.Quote(arg.Value))
		}
		// Membership already implies a non-empty value, so @required adds
		// nothing here.
		return "z.enum([" + strings.Join(values, ", ") + "])"
	}
	var rules strings.Builder
	rules.WriteString("z.string()")
	if f.HasDecorator("required") {
		rules.WriteString(".min(1)")
	}
	if f.HasDecorator("email") {
		rules.WriteString(".email()")
	}
	if f.HasDecorator("uuid") {
		rules.WriteString(".uuid()")
	}
	if f.HasDecorator("uri") {
		rules.WriteString(".url()")
	}
	if d, ok := f.Decorator("pattern"); ok {
		value, _ := d.Value()
		rules.WriteString(".regex(new RegExp(" + strconv.Quote(value) + "))")
	}
	if d, ok := f.Decorator("len"); ok && len(d.Args) == 2 {
		rules.WriteString(".min(" + d.Args[0].Value + ").max(" + d.Args[1].Value + ")")
	}
	return rules.String()
}

// zodTypeRefSchema resolves a bare TypeRef (map value, oneof variant) to its
// Zod expression.
// zodUnknownSchema is the shared fallback for types without a precise Zod
// representation.
const zodUnknownSchema = "z.unknown()"

func zodTypeRefSchema(p *Printer, t *onkir.Type) string {
	if t == nil {
		return zodUnknownSchema
	}
	switch t.Kind {
	case onkir.KindMessage:
		return p.zodSchemaRef(t.Message)
	case onkir.KindEnum:
		return p.zodEnumRef(t.Enum)
	case onkir.KindMap:
		return "z.record(z.string(), " + zodTypeRefSchema(p, t.MapValue) + ")"
	case onkir.KindScalar:
		return zodScalarSchema(t.Scalar)
	default:
		return zodUnknownSchema
	}
}

func zodScalarSchema(kind onkir.ScalarKind) string {
	switch kind {
	case onkir.ScalarString, onkir.ScalarBytes:
		return "z.string()"
	case onkir.ScalarBool:
		return "z.boolean()"
	case onkir.ScalarInt32:
		return "z.number().int().gte(-2147483648).lte(2147483647)"
	case onkir.ScalarUint32:
		return "z.number().int().gte(0).lte(4294967295)"
	case onkir.ScalarInt64:
		return `z.string().regex(/^-?(0|[1-9][0-9]*)$/)`
	case onkir.ScalarUint64:
		return `z.string().regex(/^(0|[1-9][0-9]*)$/)`
	case onkir.ScalarFloat32, onkir.ScalarFloat64:
		return "z.number()"
	case onkir.ScalarTimestamp:
		return "z.string()"
	case onkir.ScalarJSON:
		return zodUnknownSchema
	default:
		return zodUnknownSchema
	}
}

// collectZodExternalRefs collects cross-package imports for the schemas
// module. It mirrors the types-module collector but points every import at
// the sibling schemas.ts instead of types.ts.
func collectZodExternalRefs(file *onkir.File, resolver PackageResolver) []PackageRef {
	if resolver == nil {
		return nil
	}
	c := newRefCollector(resolver)
	for _, m := range file.Messages {
		c.addMessageFields(m)
	}
	refs := c.sorted()
	for i := range refs {
		refs[i].ImportPath = strings.TrimSuffix(refs[i].ImportPath, "/types") + "/schemas"
	}
	return refs
}
