package genrust

import (
	"strconv"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

func GenerateServer(file *onkir.File) []byte {
	return GenerateServerWithResolver(file, nil)
}

func GenerateServerWithResolver(file *onkir.File, resolver PackageResolver) []byte {
	if len(file.Services) == 0 {
		return nil
	}
	p := newPrinter(resolver)
	p.P("// Code generated by onek. DO NOT EDIT.")
	p.Blank()
	p.P("use super::types::*;")
	p.P("#[allow(unused_imports)]")
	p.P("use axum::extract::{Path, Query, State};")
	p.P("use axum::http::{HeaderMap, StatusCode};")
	p.P("use axum::response::{IntoResponse as _, Response};")
	p.P("use axum::{Json, Router};")
	if onkir.FileHasStreamMethods(file) {
		p.P("use axum::response::sse::{Event, Sse};")
		p.P("use futures_util::{Stream, StreamExt as _};")
		p.P("use std::convert::Infallible;")
		p.P("use std::pin::Pin;")
	}
	p.P("use std::sync::Arc;")
	p.Blank()
	writeServerContext(p)
	writePathParser(p)
	for _, service := range file.Services {
		writeServerService(p, service)
	}
	return p.Bytes()
}

func writeServerContext(p *Printer) {
	p.P("#[derive(Debug, Clone)]")
	p.P("pub struct RequestContext {")
	p.Indent()
	p.P("pub headers: HeaderMap,")
	p.Dedent()
	p.P("}")
	p.Blank()
}

func writePathParser(p *Printer) {
	p.P("#[allow(dead_code)]")
	p.P("fn parse_path<T: serde::de::DeserializeOwned>(value: &str) -> Result<T, String> {")
	p.Indent()
	p.P("serde_json::from_value(serde_json::Value::String(value.to_owned()))")
	p.Indent()
	p.P(".or_else(|_| serde_json::from_str(value))")
	p.P(".map_err(|error| error.to_string())")
	p.Dedent()
	p.Dedent()
	p.P("}")
	p.Blank()
	p.P("fn valid_header_format(value: &str, format: &str) -> bool {")
	p.Indent()
	p.P("match format {")
	p.Indent()
	p.P(strconv.Quote("uuid"), " => value.len() == 36 && value.char_indices().all(|(index, character)| matches!(index, 8 | 13 | 18 | 23) && character == '-' || !matches!(index, 8 | 13 | 18 | 23) && character.is_ascii_hexdigit()),")
	p.P(strconv.Quote("email"), " => value.split_once('@').is_some_and(|(_, domain)| domain.contains('.')), ")
	p.P(strconv.Quote("uri"), " => value.split_once(\"://\").is_some_and(|(scheme, rest)| !scheme.is_empty() && !rest.is_empty()),")
	p.P("_ => true,")
	p.Dedent()
	p.P("}")
	p.Dedent()
	p.P("}")
	p.Blank()
}

func writeServerService(p *Printer, service *onkir.Service) {
	traitName := PascalCase(service.Name)
	p.P("pub trait ", traitName, ": Send + Sync + 'static {")
	p.Indent()
	for _, method := range service.Methods {
		requestType := p.MessageTypeName(method.Request)
		responseType := p.MessageTypeName(method.Response)
		errorType := serverErrorName(service, method)
		switch {
		case method.IsWebSocket():
			p.P(
				"fn ", RustIdent(method.Name), "(&self, context: RequestContext, req: ", requestType,
				", out: WsSink<", responseType,
				">) -> impl std::future::Future<Output = Result<(), ", errorType, ">> + Send;",
			)
		case method.IsStream():
			p.P(
				"fn ", RustIdent(method.Name), "(&self, context: RequestContext, req: ", requestType,
				") -> impl std::future::Future<Output = Result<Pin<Box<dyn Stream<Item = Result<",
				responseType, ", ", errorType, ">> + Send>>, ", errorType, ">> + Send;",
			)
		default:
			p.P(
				"fn ", RustIdent(method.Name), "(&self, context: RequestContext, req: ", requestType,
				") -> impl std::future::Future<Output = Result<", responseType, ", ", errorType,
				">> + Send;",
			)
		}
	}
	p.Dedent()
	p.P("}")
	p.Blank()

	hasWS := false
	for _, m := range service.Methods {
		if m.IsWebSocket() {
			hasWS = true
			break
		}
	}
	if hasWS {
		WriteWSServerRuntime(p)
	}
	writeRouter(p, service)
	for _, method := range service.Methods {
		if method.IsWebSocket() {
			writeWSUpgradeHandler(p, service, method)
			continue
		}
		writeHandler(p, service, method)
		writeServerError(p, service, method)
	}
}

func writeRouter(p *Printer, service *onkir.Service) {
	traitName := PascalCase(service.Name)
	p.P("pub fn ", SnakeCase(service.Name), "_router<T: ", traitName, ">(service: Arc<T>) -> Router {")
	p.Indent()
	p.P("Router::new()")
	p.Indent()
	for _, method := range service.Methods {
		if method.IsWebSocket() {
			writeWSRouterEntry(p, service, method)
			continue
		}
		verb, _ := method.Verb()
		path, _ := method.Path()
		fullPath := service.BasePath + path
		// axum 0.8's MethodRouter only routes the fixed HTTP verb set, so a
		// literal QUERY route needs axum::routing::any plus an in-handler
		// method guard (see writeHandler) to keep the wire contract that the
		// Go/TS/Python backends implement.
		routeFn := rustAxumRouteFunction(verb)
		if verb == queryVerb {
			routeFn = "any"
		}
		p.P(
			".route(", strconv.Quote(fullPath), ", axum::routing::", routeFn,
			"(", handlerName(service, method), "::<T>))",
		)
	}
	p.P(".with_state(service)")
	p.Dedent()
	p.Dedent()
	p.P("}")
	p.Blank()
}

//nolint:nestif // Extractor and response branches directly mirror the schema HTTP binding matrix.
func writeHandler(
	p *Printer,
	service *onkir.Service,
	method *onkir.Method,
) {
	traitName := PascalCase(service.Name)
	requestType := p.MessageTypeName(method.Request)
	pathFields := pathFieldNames(mustMethodPath(method))
	verb := mustMethodVerb(method)
	bodyBearing := onkir.IsBodyBearingVerb(verb)

	p.P("async fn ", handlerName(service, method), "<T: ", traitName, ">(")
	p.Indent()
	if verb == queryVerb {
		p.P("method: axum::http::Method,")
	}
	p.P("State(service): State<Arc<T>>,")
	p.P("headers: HeaderMap,")
	if len(pathFields) > 0 {
		p.P("Path(path): Path<std::collections::HashMap<String, String>>,")
	}
	if bodyBearing {
		if bodyField, ok := method.BodyField(); ok {
			if field := onkir.FindField(method.Request, bodyField); field != nil {
				if bodyFieldNeedsCustomWire(field) {
					p.P("Json(body): Json<serde_json::Value>,")
				} else {
					p.P("Json(body): Json<", rustFieldType(p, field), ">,")
				}
			} else {
				p.P("Json(mut req): Json<", requestType, ">,")
			}
		} else {
			p.P("Json(mut req): Json<", requestType, ">,")
		}
	} else {
		p.P("Query(mut req): Query<", requestType, ">,")
	}
	p.Dedent()
	p.P(") -> Response {")
	p.Indent()

	errorName := serverErrorName(service, method)
	if verb == queryVerb {
		writeQueryMethodGuard(p)
	}
	if bodyField, ok := method.BodyField(); ok && bodyBearing {
		if field := onkir.FindField(method.Request, bodyField); field != nil {
			if bodyFieldNeedsCustomWire(field) {
				p.P("let mut body_object = serde_json::Map::new();")
				p.P("body_object.insert(", strconv.Quote(field.Name), ".into(), body);")
				p.P("let mut req: ", requestType, " = match serde_json::from_value(serde_json::Value::Object(body_object)) {")
				p.Indent()
				p.P("Ok(value) => value,")
				p.P("Err(error) => return ", errorName, "::InvalidRequest(error.to_string()).into_response(),")
				p.Dedent()
				p.P("};")
			} else {
				p.P("let mut req = ", requestType, "::default();")
				p.P("req.", RustIdent(field.Name), " = body;")
			}
		}
	}

	for _, name := range pathFields {
		field := onkir.FindField(method.Request, name)
		if field == nil {
			continue
		}
		p.P("let Some(value) = path.get(", strconv.Quote(name), ") else {")
		p.Indent()
		p.P(
			"return ", errorName, "::InvalidRequest(",
			strconv.Quote("missing path field "+name), ".into()).into_response();",
		)
		p.Dedent()
		p.P("};")
		if field.Optional {
			p.P("req.", RustIdent(field.Name), " = match parse_path(value) {")
			p.Indent()
			p.P("Ok(value) => Some(value),")
			writeInvalidPathArm(p, errorName, name)
			p.Dedent()
			p.P("};")
		} else {
			p.P("req.", RustIdent(field.Name), " = match parse_path(value) {")
			p.Indent()
			p.P("Ok(value) => value,")
			writeInvalidPathArm(p, errorName, name)
			p.Dedent()
			p.P("};")
		}
	}
	for _, header := range combinedHeaders(service, method) {
		format, hasFormat := header.Format()
		p.P("let header_value = headers.get(", strconv.Quote(header.Name), ").and_then(|value| value.to_str().ok());")
		if header.Required() {
			p.P("if header_value.is_none_or(|value| value.is_empty()) {")
			p.Indent()
			p.P(
				"return ", errorName, "::InvalidRequest(",
				strconv.Quote("missing required header "+header.Name),
				".into()).into_response();",
			)
			p.Dedent()
			p.P("}")
		}
		if hasFormat {
			p.P("if header_value.is_some_and(|value| !valid_header_format(value, ", strconv.Quote(format), ")) {")
			p.Indent()
			p.P("return ", errorName, "::InvalidRequest(", strconv.Quote("invalid header "+header.Name+": expected "+format), ".into()).into_response();")
			p.Dedent()
			p.P("}")
		}
	}
	p.P("if let Err(error) = req.validate() { return ", errorName, "::Validation(error).into_response(); }")
	p.P("let context = RequestContext { headers };")
	p.P("match service.", RustIdent(method.Name), "(context, req).await {")
	p.Indent()
	if method.IsStream() {
		p.P("Ok(stream) => {")
		p.Indent()
		p.P("let events = stream.map(|item| {")
		p.Indent()
		p.P("let event = match item {")
		p.Indent()
		p.P(
			"Ok(value) => Event::default().json_data(value).unwrap_or_else(",
			"|error| Event::default().event(\"error\").data(error.to_string())),",
		)
		p.P("Err(error) => Event::default().event(\"error\").data(error.to_string()),")
		p.Dedent()
		p.P("};")
		p.P("Ok::<Event, Infallible>(event)")
		p.Dedent()
		p.P("});")
		p.P("Sse::new(events).into_response()")
		p.Dedent()
		p.P("}")
	} else {
		p.P("Ok(value) => Json(value).into_response(),")
	}
	p.P("Err(error) => error.into_response(),")
	p.Dedent()
	p.P("}")
	p.Dedent()
	p.P("}")
	p.Blank()
}

func writeInvalidPathArm(p *Printer, errorName, fieldName string) {
	p.P(
		"Err(error) => return ", errorName, "::InvalidRequest(format!(",
		strconv.Quote("invalid path field "+fieldName+": {}"),
		", error)).into_response(),",
	)
}

func writeServerError(
	p *Printer,
	service *onkir.Service,
	method *onkir.Method,
) {
	name := serverErrorName(service, method)
	p.P("#[derive(Debug)]")
	p.P("pub enum ", name, " {")
	p.Indent()
	p.P("Validation(ValidationError),")
	p.P("InvalidRequest(String),")
	variants := ErrorVariantNames(method.ErrorTypes)
	for i, errorType := range method.ErrorTypes {
		p.P(variants[i], "(", p.MessageTypeName(errorType), "),")
	}
	p.P("Internal(String),")
	p.Dedent()
	p.P("}")
	p.Blank()
	p.P("impl std::fmt::Display for ", name, " {")
	p.Indent()
	p.P("fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {")
	p.Indent()
	p.P("match self {")
	p.Indent()
	p.P("Self::Validation(error) => write!(formatter, \"request validation failed: {error}\"),")
	p.P("Self::InvalidRequest(error) => write!(formatter, \"invalid request: {error}\"),")
	for i, errorType := range method.ErrorTypes {
		p.P("Self::", variants[i], "(error) => write!(formatter, \"", errorType.Name, ": {error}\"),")
	}
	p.P("Self::Internal(error) => write!(formatter, \"internal server error: {error}\"),")
	p.Dedent()
	p.P("}")
	p.Dedent()
	p.P("}")
	p.Dedent()
	p.P("}")
	p.P("impl std::error::Error for ", name, " {}")
	p.Blank()
	p.P("impl axum::response::IntoResponse for ", name, " {")
	p.Indent()
	p.P("fn into_response(self) -> Response {")
	p.Indent()
	p.P("match self {")
	p.Indent()
	p.P("Self::Validation(error) => (StatusCode::BAD_REQUEST, Json(serde_json::json!({ \"error\": error.to_string() }))).into_response(),")
	p.P("Self::InvalidRequest(error) => (StatusCode::BAD_REQUEST, Json(serde_json::json!({ \"error\": error }))).into_response(),")
	for i, errorType := range method.ErrorTypes {
		status := 500
		if code, ok := errorType.StatusCode(); ok {
			status = code
		}
		p.P("Self::", variants[i], "(error) => (StatusCode::from_u16(", status, ").unwrap_or(StatusCode::INTERNAL_SERVER_ERROR), Json(error)).into_response(),")
	}
	p.P("Self::Internal(_error) => (StatusCode::INTERNAL_SERVER_ERROR, Json(serde_json::json!({ \"error\": \"internal server error\" }))).into_response(),")
	p.Dedent()
	p.P("}")
	p.Dedent()
	p.P("}")
	p.Dedent()
	p.P("}")
	p.Blank()
}

func combinedHeaders(service *onkir.Service, method *onkir.Method) []*onkir.Header {
	headers := make([]*onkir.Header, 0, len(service.Headers)+len(method.Headers))
	headers = append(headers, service.Headers...)
	headers = append(headers, method.Headers...)
	return headers
}

func serverErrorName(service *onkir.Service, method *onkir.Method) string {
	return PascalCase(service.Name) + PascalCase(method.Name) + "ServerError"
}

func handlerName(service *onkir.Service, method *onkir.Method) string {
	return SnakeCase(service.Name) + "_" + SnakeCase(method.Name) + "_handler"
}

// writeQueryMethodGuard emits the axum-compatibility method check for
// literal-QUERY routes: the route is registered with axum::routing::any
// because MethodRouter cannot match the custom QUERY method, so the handler
// enforces the wire contract itself.
func writeQueryMethodGuard(p *Printer) {
	p.P(`if method.as_str() != "QUERY" {`)
	p.Indent()
	p.P("return (axum::http::StatusCode::METHOD_NOT_ALLOWED, \"method not allowed\").into_response();")
	p.Dedent()
	p.P("}")
}

func rustAxumRouteFunction(verb string) string {
	switch strings.ToLower(verb) {
	case "get":
		return "get"
	case "delete":
		return "delete"
	case rustVerbPut:
		return rustVerbPut
	case rustVerbPatch:
		return rustVerbPatch
	default:
		return rustVerbPost
	}
}

func mustMethodVerb(method *onkir.Method) string {
	verb, _ := method.Verb()
	return verb
}

func mustMethodPath(method *onkir.Method) string {
	path, _ := method.Path()
	return path
}
