package genrust

import (
	"strconv"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

type typeFeatures struct {
	bytes     bool
	intString bool
	email     bool
	empty     bool
}

func GenerateTypes(file *onkir.File) []byte {
	return GenerateTypesWithResolver(file, nil)
}

func GenerateTypesWithResolver(file *onkir.File, resolver PackageResolver) []byte {
	p := newPrinter(resolver)
	features := collectTypeFeatures(file)

	p.P("// Code generated by onek. DO NOT EDIT.")
	p.P("#![allow(clippy::derive_partial_eq_without_eq)]")
	p.Blank()
	p.P("#[allow(unused_imports)]")
	p.P("use serde::{Deserialize, Deserializer, Serialize, Serializer};")
	if features.bytes {
		p.P("use base64::Engine as _;")
	}
	if features.email {
		p.P("use validator::ValidateEmail as _;")
	}
	p.Blank()

	writeValidationError(p)
	writeSerdeHelpers(p, features)

	for _, enum := range file.Enums {
		writeEnum(p, enum)
	}
	for _, message := range file.Messages {
		writeMessageTree(p, message)
	}
	return p.Bytes()
}

func collectTypeFeatures(file *onkir.File) typeFeatures {
	var features typeFeatures
	var inspectMessage func(*onkir.Message)
	inspectMessage = func(message *onkir.Message) {
		for _, field := range message.Fields {
			if field.Type != nil && field.Type.Kind == onkir.KindScalar {
				if field.Type.Scalar == onkir.ScalarBytes {
					features.bytes = true
				}
				if (field.Type.Scalar == onkir.ScalarInt64 || field.Type.Scalar == onkir.ScalarUint64) &&
					fieldEncoding(field) != rustEncodeNumber {
					features.intString = true
				}
			}
			if field.Type != nil && field.Type.Kind == onkir.KindMap && field.Type.MapValue != nil &&
				field.Type.MapValue.Kind == onkir.KindScalar && field.Type.MapValue.Scalar == onkir.ScalarBytes {
				features.bytes = true
			}
			if emptyBehavior(field) != "" {
				features.empty = true
			}
			for _, decorator := range field.Decorators {
				if decorator.Name == decoratorEmail {
					features.email = true
				}
			}
		}
		for _, nested := range message.Nested {
			inspectMessage(nested)
		}
	}
	for _, message := range file.Messages {
		inspectMessage(message)
	}
	return features
}

func writeValidationError(p *Printer) {
	p.P("#[derive(Debug, Clone, PartialEq, Eq)]")
	p.P("pub struct ValidationError {")
	p.Indent()
	p.P("pub field: &'static str,")
	p.P("pub message: String,")
	p.Dedent()
	p.P("}")
	p.Blank()
	p.P("impl std::fmt::Display for ValidationError {")
	p.Indent()
	p.P("fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {")
	p.Indent()
	p.P("write!(formatter, \"{}: {}\", self.field, self.message)")
	p.Dedent()
	p.P("}")
	p.Dedent()
	p.P("}")
	p.Blank()
	p.P("impl std::error::Error for ValidationError {}")
	p.Blank()
}

func writeSerdeHelpers(p *Printer, features typeFeatures) {
	if features.intString {
		writeIntegerStringModules(p)
	}
	if features.bytes {
		writeBytesModules(p)
	}
	if features.empty {
		p.P("fn is_none_or_empty<T: Serialize>(value: &Option<Box<T>>) -> bool {")
		p.Indent()
		p.P("match value {")
		p.Indent()
		p.P("None => true,")
		p.P("Some(value) => serde_json::to_value(value)")
		p.Indent()
		p.P(".map(|value| value.as_object().is_some_and(|object| object.is_empty()))")
		p.P(".unwrap_or(false),")
		p.Dedent()
		p.Dedent()
		p.P("}")
		p.Dedent()
		p.P("}")
		p.Blank()
		p.P("fn serialize_empty_as_null<T: Serialize, S: Serializer>(")
		p.Indent()
		p.P("value: &Option<Box<T>>,")
		p.P("serializer: S,")
		p.Dedent()
		p.P(") -> Result<S::Ok, S::Error> {")
		p.Indent()
		p.P("match value {")
		p.Indent()
		p.P("None => serializer.serialize_none(),")
		p.P("Some(value) => {")
		p.Indent()
		p.P("let value = serde_json::to_value(value).map_err(serde::ser::Error::custom)?;")
		p.P("if value.as_object().is_some_and(|object| object.is_empty()) {")
		p.Indent()
		p.P("serializer.serialize_none()")
		p.Dedent()
		p.P("} else {")
		p.Indent()
		p.P("value.serialize(serializer)")
		p.Dedent()
		p.P("}")
		p.Dedent()
		p.P("}")
		p.Dedent()
		p.P("}")
		p.Dedent()
		p.P("}")
		p.Blank()
	}
}

func writeIntegerStringModules(p *Printer) {
	for _, spec := range []struct {
		name string
		typ  string
	}{
		{"i64_string", "i64"},
		{"u64_string", "u64"},
	} {
		p.P("#[allow(dead_code)]")
		p.P("mod serde_", spec.name, " {")
		p.Indent()
		p.P("use super::*;")
		p.P("pub fn serialize<S: Serializer>(value: &", spec.typ, ", serializer: S) -> Result<S::Ok, S::Error> {")
		p.Indent()
		p.P("serializer.serialize_str(&value.to_string())")
		p.Dedent()
		p.P("}")
		p.P("pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<", spec.typ, ", D::Error> {")
		p.Indent()
		p.P("let value = String::deserialize(deserializer)?;")
		p.P("value.parse().map_err(serde::de::Error::custom)")
		p.Dedent()
		p.P("}")
		p.Dedent()
		p.P("}")
		p.Blank()

		p.P("#[allow(dead_code)]")
		p.P("mod serde_option_", spec.name, " {")
		p.Indent()
		p.P("use super::*;")
		p.P(
			"pub fn serialize<S: Serializer>(value: &Option<",
			spec.typ,
			">, serializer: S) -> Result<S::Ok, S::Error> {",
		)
		p.Indent()
		p.P("value.map(|value| value.to_string()).serialize(serializer)")
		p.Dedent()
		p.P("}")
		p.P(
			"pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<Option<",
			spec.typ,
			">, D::Error> {",
		)
		p.Indent()
		p.P("Option::<String>::deserialize(deserializer)?")
		p.Indent()
		p.P(".map(|value| value.parse().map_err(serde::de::Error::custom))")
		p.P(".transpose()")
		p.Dedent()
		p.Dedent()
		p.P("}")
		p.Dedent()
		p.P("}")
		p.Blank()

		p.P("#[allow(dead_code)]")
		p.P("mod serde_vec_", spec.name, " {")
		p.Indent()
		p.P("use super::*;")
		p.P("pub fn serialize<S: Serializer>(value: &[", spec.typ, "], serializer: S) -> Result<S::Ok, S::Error> {")
		p.Indent()
		p.P("value.iter().map(ToString::to_string).collect::<Vec<_>>().serialize(serializer)")
		p.Dedent()
		p.P("}")
		p.P("pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<Vec<", spec.typ, ">, D::Error> {")
		p.Indent()
		p.P("Vec::<String>::deserialize(deserializer)?")
		p.Indent()
		p.P(".into_iter()")
		p.P(".map(|value| value.parse().map_err(serde::de::Error::custom))")
		p.P(".collect()")
		p.Dedent()
		p.Dedent()
		p.P("}")
		p.Dedent()
		p.P("}")
		p.Blank()
	}
}

func writeBytesModules(p *Printer) {
	encodings := []struct {
		name       string
		encodeExpr string
		decodeExpr string
	}{
		{
			"base64",
			"base64::engine::general_purpose::STANDARD.encode(value)",
			"base64::engine::general_purpose::STANDARD.decode(value)",
		},
		{
			"base64_raw",
			"base64::engine::general_purpose::STANDARD_NO_PAD.encode(value)",
			"base64::engine::general_purpose::STANDARD_NO_PAD.decode(value)",
		},
		{
			"base64_url",
			"base64::engine::general_purpose::URL_SAFE.encode(value)",
			"base64::engine::general_purpose::URL_SAFE.decode(value)",
		},
		{
			"base64_url_raw",
			"base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(value)",
			"base64::engine::general_purpose::URL_SAFE_NO_PAD.decode(value)",
		},
	}
	for _, encoding := range encodings {
		writeBytesModule(p, "serde_bytes_"+encoding.name, encoding.encodeExpr, encoding.decodeExpr)
		writeOptionalBytesModule(p, "serde_option_bytes_"+encoding.name, encoding.encodeExpr, encoding.decodeExpr)
		writeRepeatedBytesModule(p, "serde_vec_bytes_"+encoding.name, encoding.encodeExpr, encoding.decodeExpr)
	}
	hexEncode := `value.iter().map(|byte| format!("{byte:02x}")).collect::<String>()`
	hexDecode := `decode_hex(value)`
	writeHexDecodeHelper(p)
	writeBytesModule(p, "serde_bytes_hex", hexEncode, hexDecode)
	writeOptionalBytesModule(p, "serde_option_bytes_hex", hexEncode, hexDecode)
	writeRepeatedBytesModule(p, "serde_vec_bytes_hex", hexEncode, hexDecode)
}

func writeBytesModule(p *Printer, name, encodeExpr, decodeExpr string) {
	p.P("#[allow(dead_code)]")
	p.P("mod ", name, " {")
	p.Indent()
	p.P("use super::*;")
	p.P("pub fn serialize<S: Serializer>(value: &[u8], serializer: S) -> Result<S::Ok, S::Error> {")
	p.Indent()
	p.P(encodeExpr, ".serialize(serializer)")
	p.Dedent()
	p.P("}")
	p.P("pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<Vec<u8>, D::Error> {")
	p.Indent()
	p.P("let value = String::deserialize(deserializer)?;")
	p.P(decodeExpr, ".map_err(serde::de::Error::custom)")
	p.Dedent()
	p.P("}")
	p.Dedent()
	p.P("}")
	p.Blank()
}

func writeOptionalBytesModule(p *Printer, name, encodeExpr, decodeExpr string) {
	p.P("#[allow(dead_code)]")
	p.P("mod ", name, " {")
	p.Indent()
	p.P("use super::*;")
	p.P("pub fn serialize<S: Serializer>(value: &Option<Vec<u8>>, serializer: S) -> Result<S::Ok, S::Error> {")
	p.Indent()
	p.P("value.as_deref().map(|value| ", encodeExpr, ").serialize(serializer)")
	p.Dedent()
	p.P("}")
	p.P("pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<Option<Vec<u8>>, D::Error> {")
	p.Indent()
	p.P("Option::<String>::deserialize(deserializer)?")
	p.Indent()
	p.P(".map(|value| ", decodeExpr, ".map_err(serde::de::Error::custom))")
	p.P(".transpose()")
	p.Dedent()
	p.Dedent()
	p.P("}")
	p.Dedent()
	p.P("}")
	p.Blank()
}

func writeRepeatedBytesModule(p *Printer, name, encodeExpr, decodeExpr string) {
	p.P("#[allow(dead_code)]")
	p.P("mod ", name, " {")
	p.Indent()
	p.P("use super::*;")
	p.P("pub fn serialize<S: Serializer>(value: &[Vec<u8>], serializer: S) -> Result<S::Ok, S::Error> {")
	p.Indent()
	p.P("value.iter().map(|value| ", encodeExpr, ").collect::<Vec<_>>().serialize(serializer)")
	p.Dedent()
	p.P("}")
	p.P("pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<Vec<Vec<u8>>, D::Error> {")
	p.Indent()
	p.P("Vec::<String>::deserialize(deserializer)?")
	p.Indent()
	p.P(".into_iter()")
	p.P(".map(|value| ", decodeExpr, ".map_err(serde::de::Error::custom))")
	p.P(".collect()")
	p.Dedent()
	p.Dedent()
	p.P("}")
	p.Dedent()
	p.P("}")
	p.Blank()
}

func writeHexDecodeHelper(p *Printer) {
	p.P("#[allow(dead_code)]")
	p.P("fn decode_hex(value: String) -> Result<Vec<u8>, String> {")
	p.Indent()
	p.P("if !value.is_ascii() { return Err(\"hex value must contain only ASCII characters\".into()); }")
	p.P("let bytes = value.as_bytes();")
	p.P("if bytes.len() % 2 != 0 { return Err(\"hex value has odd length\".into()); }")
	p.P("(0..bytes.len()).step_by(2)")
	p.Indent()
	p.P(".map(|index| std::str::from_utf8(&bytes[index..index + 2]).map_err(|error| error.to_string()).and_then(|pair| u8::from_str_radix(pair, 16).map_err(|error| error.to_string())))")
	p.P(".collect()")
	p.Dedent()
	p.Dedent()
	p.P("}")
	p.Blank()
}

func writeEnum(p *Printer, enum *onkir.Enum) {
	p.P("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]")
	p.P("pub enum ", RustEnumName(enum), " {")
	p.Indent()
	for _, value := range enum.Values {
		p.P("#[serde(rename = ", strconv.Quote(value.JSONName()), ")]")
		p.P(PascalCase(value.Name), ",")
	}
	p.Dedent()
	p.P("}")
	if len(enum.Values) > 0 {
		p.Blank()
		p.P("impl Default for ", RustEnumName(enum), " {")
		p.Indent()
		p.P("fn default() -> Self { Self::", PascalCase(enum.Values[0].Name), " }")
		p.Dedent()
		p.P("}")
	}
	p.Blank()
}

func writeMessageTree(p *Printer, message *onkir.Message) {
	for _, enum := range message.NestedEnums {
		writeEnum(p, enum)
	}
	for _, nested := range message.Nested {
		writeMessageTree(p, nested)
	}
	for _, field := range message.Fields {
		if prefix, ok := flattenPrefix(field); ok {
			p.P("serde_with::with_prefix!(", prefixModuleName(field), " ", strconv.Quote(prefix), ");")
			p.Blank()
		}
		if field.Oneof != nil {
			writeOneof(p, message, field)
		}
		if mapValueIsBytes(field) {
			writeMapBytesModule(p, field)
		}
		if needsEnumNumberEncoding(field) {
			writeEnumNumberModule(p, field)
		}
	}
	writeMessage(p, message)
}

func writeMessage(p *Printer, message *onkir.Message) {
	if rootUnwrapField(message) != nil {
		p.P("#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]")
		p.P("#[serde(transparent)]")
	} else {
		p.P("#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]")
	}
	p.P("pub struct ", RustMessageName(message), " {")
	p.Indent()
	for _, field := range message.Fields {
		writeField(p, field)
	}
	p.Dedent()
	p.P("}")
	p.Blank()
	writeValidation(p, message)
	if message.IsError() {
		p.P("impl std::fmt::Display for ", RustMessageName(message), " {")
		p.Indent()
		p.P("fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {")
		p.Indent()
		p.P("write!(formatter, ", strconv.Quote(message.Name), ")")
		p.Dedent()
		p.P("}")
		p.Dedent()
		p.P("}")
		p.P("impl std::error::Error for ", RustMessageName(message), " {}")
		p.Blank()
	}
}

func writeField(p *Printer, field *onkir.Field) {
	defaultAttribute := "default, "
	if field.Message != nil && rootUnwrapField(field.Message) == field {
		defaultAttribute = ""
	}
	p.P("#[serde(", defaultAttribute, "rename = ", strconv.Quote(field.Name), fieldSerdeOptions(field), ")]")
	fieldType := rustFieldType(p, field)
	p.P("pub ", RustIdent(field.Name), ": ", fieldType, ",")
}

func rustFieldType(p *Printer, field *onkir.Field) string {
	if field.Oneof != nil {
		return "Option<" + OneofTypeName(field.Message, field) + ">"
	}
	base := p.RustType(field.Type)
	if field.Type != nil && field.Type.Kind == onkir.KindScalar && field.Type.Scalar == onkir.ScalarTimestamp {
		switch fieldEncoding(field) {
		case "unix_seconds", "unix_millis":
			base = "i64"
		}
	}
	if field.Repeated {
		return "Vec<" + base + ">"
	}
	if field.Type != nil && field.Type.Kind == onkir.KindMap {
		return base
	}
	if field.Type != nil && field.Type.Kind == onkir.KindMessage {
		base = "Box<" + base + ">"
	}
	if field.Optional || (field.Type != nil && field.Type.Kind == onkir.KindMessage) {
		return "Option<" + base + ">"
	}
	return base
}

func fieldSerdeOptions(field *onkir.Field) string {
	var options []string
	empty := emptyBehavior(field)
	rootUnwrap := field.Message != nil && rootUnwrapField(field.Message) == field
	if field.Oneof != nil {
		options = append(options, `skip_serializing_if = "Option::is_none"`)
	}
	if field.Optional && empty == "" && !rootUnwrap {
		options = append(options, `skip_serializing_if = "Option::is_none"`)
	}
	if field.Repeated && !rootUnwrap {
		options = append(options, `skip_serializing_if = "Vec::is_empty"`)
	}
	if field.Type != nil && field.Type.Kind == onkir.KindMap && !rootUnwrap {
		options = append(options, `skip_serializing_if = "std::collections::HashMap::is_empty"`)
	}
	if prefix, ok := flattenPrefix(field); ok {
		moduleName := prefixModuleName(field)
		options = append(options, "flatten", `with = "`+moduleName+`"`)
		_ = prefix
	}
	switch empty {
	case "omit":
		options = append(options, `skip_serializing_if = "is_none_or_empty"`)
	case "null":
		options = append(options, `serialize_with = "serialize_empty_as_null"`)
	}
	if module := serdeModuleForField(field); module != "" {
		options = append(options, `with = "`+module+`"`)
	}
	if len(options) == 0 {
		return ""
	}
	return ", " + strings.Join(options, ", ")
}

func prefixModuleName(field *onkir.Field) string {
	return "prefix_" + SnakeCase(field.Message.Name) + "_" + SnakeCase(field.Name)
}

func serdeModuleForField(field *onkir.Field) string {
	if field.Type == nil {
		return ""
	}
	if mapValueIsBytes(field) {
		return mapBytesModuleName(field)
	}
	if needsEnumNumberEncoding(field) {
		return enumNumberModuleName(field)
	}
	if field.Type.Kind != onkir.KindScalar {
		return ""
	}
	cardinality := ""
	if field.Repeated {
		cardinality = "vec_"
	} else if field.Optional {
		cardinality = "option_"
	}
	switch field.Type.Scalar {
	case onkir.ScalarInt64:
		if fieldEncoding(field) != rustEncodeNumber {
			return "serde_" + cardinality + "i64_string"
		}
	case onkir.ScalarUint64:
		if fieldEncoding(field) != rustEncodeNumber {
			return "serde_" + cardinality + "u64_string"
		}
	case onkir.ScalarBytes:
		encoding := fieldEncoding(field)
		switch encoding {
		case "hex":
			return "serde_" + cardinality + "bytes_hex"
		case "base64_raw":
			return "serde_" + cardinality + "bytes_base64_raw"
		case "base64url":
			return "serde_" + cardinality + "bytes_base64_url"
		case "base64url_raw":
			return "serde_" + cardinality + "bytes_base64_url_raw"
		default:
			return "serde_" + cardinality + "bytes_base64"
		}
	case onkir.ScalarString, onkir.ScalarBool, onkir.ScalarInt32, onkir.ScalarUint32,
		onkir.ScalarFloat32, onkir.ScalarFloat64, onkir.ScalarTimestamp:
		return ""
	}
	return ""
}

func mapValueIsBytes(field *onkir.Field) bool {
	return field.Type != nil && field.Type.Kind == onkir.KindMap && field.Type.MapValue != nil &&
		field.Type.MapValue.Kind == onkir.KindScalar && field.Type.MapValue.Scalar == onkir.ScalarBytes
}

func mapBytesModuleName(field *onkir.Field) string {
	owner := "message"
	if field.Message != nil {
		owner = RustMessageName(field.Message)
	}
	return "serde_map_bytes_" + SnakeCase(owner) + "_" + SnakeCase(field.Name)
}

func writeMapBytesModule(p *Printer, field *onkir.Field) {
	p.P("mod ", mapBytesModuleName(field), " {")
	p.Indent()
	p.P("use super::*;")
	p.P("use base64::Engine as _;")
	p.P("pub fn serialize<S: Serializer>(value: &std::collections::HashMap<String, Vec<u8>>, serializer: S) -> Result<S::Ok, S::Error> {")
	p.Indent()
	p.P("let encoded = value.iter().map(|(key, value)| (key, base64::engine::general_purpose::STANDARD.encode(value))).collect::<std::collections::HashMap<_, _>>();")
	p.P("encoded.serialize(serializer)")
	p.Dedent()
	p.P("}")
	p.P("pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<std::collections::HashMap<String, Vec<u8>>, D::Error> {")
	p.Indent()
	p.P("let encoded = std::collections::HashMap::<String, String>::deserialize(deserializer)?;")
	p.P("encoded.into_iter().map(|(key, value)| base64::engine::general_purpose::STANDARD.decode(value).map(|value| (key, value)).map_err(serde::de::Error::custom)).collect()")
	p.Dedent()
	p.P("}")
	p.Dedent()
	p.P("}")
	p.Blank()
}

func needsEnumNumberEncoding(field *onkir.Field) bool {
	return field.Type != nil && field.Type.Kind == onkir.KindEnum && !field.Repeated &&
		fieldEncoding(field) == rustEncodeNumber
}

func enumNumberModuleName(field *onkir.Field) string {
	return "serde_" + SnakeCase(field.Message.Name) + "_" + SnakeCase(field.Name) + "_enum_number"
}

func writeEnumNumberModule(p *Printer, field *onkir.Field) {
	enum := field.Type.Enum
	enumType := "super::" + p.EnumTypeName(enum)
	p.P("mod ", enumNumberModuleName(field), " {")
	p.Indent()
	p.P("use super::*;")
	if field.Optional {
		p.P(
			"pub fn serialize<S: Serializer>(value: &Option<", enumType,
			">, serializer: S) -> Result<S::Ok, S::Error> {",
		)
		p.Indent()
		p.P("value.map(|value| match value {")
		p.Indent()
		for _, value := range enum.Values {
			p.P(enumType, "::", PascalCase(value.Name), " => ", value.Index, ",")
		}
		p.Dedent()
		p.P("}).serialize(serializer)")
		p.Dedent()
		p.P("}")
		p.P(
			"pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) ",
			"-> Result<Option<", enumType, ">, D::Error> {",
		)
		p.Indent()
		p.P("Option::<i32>::deserialize(deserializer)?.map(|value| match value {")
		p.Indent()
		for _, value := range enum.Values {
			p.P(value.Index, " => Ok(", enumType, "::", PascalCase(value.Name), "),")
		}
		p.P("_ => Err(serde::de::Error::custom(\"unknown enum value\")),")
		p.Dedent()
		p.P("}).transpose()")
		p.Dedent()
		p.P("}")
	} else {
		p.P("pub fn serialize<S: Serializer>(value: &", enumType, ", serializer: S) -> Result<S::Ok, S::Error> {")
		p.Indent()
		p.P("let value = match value {")
		p.Indent()
		for _, value := range enum.Values {
			p.P(enumType, "::", PascalCase(value.Name), " => ", value.Index, ",")
		}
		p.Dedent()
		p.P("};")
		p.P("serializer.serialize_i32(value)")
		p.Dedent()
		p.P("}")
		p.P("pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<", enumType, ", D::Error> {")
		p.Indent()
		p.P("match i32::deserialize(deserializer)? {")
		p.Indent()
		for _, value := range enum.Values {
			p.P(value.Index, " => Ok(", enumType, "::", PascalCase(value.Name), "),")
		}
		p.P("_ => Err(serde::de::Error::custom(\"unknown enum value\")),")
		p.Dedent()
		p.P("}")
		p.Dedent()
		p.P("}")
	}
	p.Dedent()
	p.P("}")
	p.Blank()
}

func fieldEncoding(field *onkir.Field) string {
	decorator, ok := field.Decorator("encode")
	if !ok {
		return ""
	}
	value, _ := decorator.Value()
	return value
}

func needsInt64StringEncoding(field *onkir.Field) bool {
	if field.Type == nil || field.Type.Kind != onkir.KindScalar ||
		(field.Type.Scalar != onkir.ScalarInt64 && field.Type.Scalar != onkir.ScalarUint64) {
		return false
	}
	return fieldEncoding(field) != rustEncodeNumber
}

func flattenPrefix(field *onkir.Field) (string, bool) {
	if field.Type == nil || field.Type.Kind != onkir.KindMessage || field.Repeated {
		return "", false
	}
	decorator, ok := field.Decorator("flatten")
	if !ok {
		return "", false
	}
	prefix, _ := decorator.NamedArg("prefix")
	return prefix, true
}

func emptyBehavior(field *onkir.Field) string {
	decorator, ok := field.Decorator("empty")
	if !ok {
		return ""
	}
	value, _ := decorator.Value()
	return value
}

func rootUnwrapField(message *onkir.Message) *onkir.Field {
	if len(message.Fields) == 1 && message.Fields[0].HasDecorator("unwrap") {
		return message.Fields[0]
	}
	return nil
}

func writeOneof(p *Printer, message *onkir.Message, field *onkir.Field) {
	name := OneofTypeName(message, field)
	p.P("#[derive(Debug, Clone, PartialEq)]")
	p.P("pub enum ", name, " {")
	p.Indent()
	for _, variant := range field.Oneof.Variants {
		p.P(PascalCase(variant.Name), "(", p.RustType(variant.Type), "),")
	}
	p.Dedent()
	p.P("}")
	p.Blank()
	writeOneofSerialize(p, name, field)
	writeOneofDeserialize(p, name, field)
}

func writeOneofSerialize(p *Printer, name string, field *onkir.Field) {
	discriminator, _ := field.Oneof.Discriminator()
	if discriminator == "" {
		discriminator = "type"
	}
	p.P("impl Serialize for ", name, " {")
	p.Indent()
	p.P("fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {")
	p.Indent()
	p.P("let mut object = serde_json::Map::new();")
	p.P("match self {")
	p.Indent()
	for _, variant := range field.Oneof.Variants {
		p.P("Self::", PascalCase(variant.Name), "(value) => {")
		p.Indent()
		p.P("object.insert(", strconv.Quote(discriminator), ".into(), serde_json::Value::String(", strconv.Quote(variant.Tag()), ".into()));")
		if field.Oneof.Flatten() {
			p.P("let value = serde_json::to_value(value).map_err(serde::ser::Error::custom)?;")
			p.P("let fields = value.as_object().ok_or_else(|| serde::ser::Error::custom(\"flattened oneof variant must serialize as an object\"))?;")
			p.P("object.extend(fields.clone());")
		} else {
			p.P("object.insert(", strconv.Quote(variant.Name), ".into(), serde_json::to_value(value).map_err(serde::ser::Error::custom)?);")
		}
		p.Dedent()
		p.P("}")
	}
	p.Dedent()
	p.P("}")
	p.P("object.serialize(serializer)")
	p.Dedent()
	p.P("}")
	p.Dedent()
	p.P("}")
	p.Blank()
}

func writeOneofDeserialize(p *Printer, name string, field *onkir.Field) {
	discriminator, _ := field.Oneof.Discriminator()
	if discriminator == "" {
		discriminator = "type"
	}
	p.P("impl<'de> Deserialize<'de> for ", name, " {")
	p.Indent()
	p.P("fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {")
	p.Indent()
	p.P("let mut object = serde_json::Map::<String, serde_json::Value>::deserialize(deserializer)?;")
	p.P("let tag = object.remove(", strconv.Quote(discriminator), ")")
	p.Indent()
	p.P(".and_then(|value| value.as_str().map(str::to_owned))")
	p.P(".ok_or_else(|| serde::de::Error::custom(", strconv.Quote("missing oneof discriminator "+discriminator), "))?;")
	p.Dedent()
	p.P("match tag.as_str() {")
	p.Indent()
	for _, variant := range field.Oneof.Variants {
		p.P(strconv.Quote(variant.Tag()), " => {")
		p.Indent()
		if field.Oneof.Flatten() {
			p.P("let value = serde_json::from_value(serde_json::Value::Object(object)).map_err(serde::de::Error::custom)?;")
		} else {
			p.P("let raw = object.remove(", strconv.Quote(variant.Name), ").ok_or_else(|| serde::de::Error::custom(", strconv.Quote("missing oneof value "+variant.Name), "))?;")
			p.P("let value = serde_json::from_value(raw).map_err(serde::de::Error::custom)?;")
		}
		p.P("Ok(Self::", PascalCase(variant.Name), "(value))")
		p.Dedent()
		p.P("}")
	}
	p.P("_ => Err(serde::de::Error::custom(format!(\"unknown oneof tag {tag}\"))),")
	p.Dedent()
	p.P("}")
	p.Dedent()
	p.P("}")
	p.Dedent()
	p.P("}")
	p.Blank()
}

func writeValidation(p *Printer, message *onkir.Message) {
	p.P("impl ", RustMessageName(message), " {")
	p.Indent()
	p.P("pub fn validate(&self) -> Result<(), ValidationError> {")
	p.Indent()
	for _, field := range message.Fields {
		writeFieldValidation(p, field)
	}
	p.P("Ok(())")
	p.Dedent()
	p.P("}")
	p.Dedent()
	p.P("}")
	p.Blank()
}

func writeFieldValidation(p *Printer, field *onkir.Field) {
	access := "self." + RustIdent(field.Name)
	errorLine := func(message string) {
		p.P("return Err(ValidationError { field: ", strconv.Quote(field.Name), ", message: ", strconv.Quote(message), ".into() });")
	}
	if field.HasDecorator("required") {
		switch {
		case field.Optional || field.Oneof != nil || (field.Type != nil && field.Type.Kind == onkir.KindMessage):
			p.P("if ", access, ".is_none() {")
			p.Indent()
			errorLine("is required")
			p.Dedent()
			p.P("}")
		case field.Repeated || (field.Type != nil && field.Type.Kind == onkir.KindMap):
			p.P("if ", access, ".is_empty() {")
			p.Indent()
			errorLine("must not be empty")
			p.Dedent()
			p.P("}")
		case field.Type != nil && field.Type.Kind == onkir.KindScalar && field.Type.Scalar == onkir.ScalarString:
			p.P("if ", access, ".is_empty() {")
			p.Indent()
			errorLine("must not be empty")
			p.Dedent()
			p.P("}")
		}
	}
	if field.Oneof != nil {
		hasMessageVariant := false
		for _, variant := range field.Oneof.Variants {
			hasMessageVariant = hasMessageVariant || variant.Type.Kind == onkir.KindMessage
		}
		if hasMessageVariant {
			p.P("if let Some(value) = &", access, " {")
			p.Indent()
			p.P("match value {")
			p.Indent()
			for _, variant := range field.Oneof.Variants {
				if variant.Type.Kind == onkir.KindMessage {
					p.P(OneofTypeName(field.Message, field), "::", PascalCase(variant.Name), "(value) => {")
					p.Indent()
					p.P("value.validate().map_err(|error| ValidationError { field: ", strconv.Quote(field.Name), ", message: error.to_string() })?;")
					p.Dedent()
					p.P("}")
				} else {
					p.P(OneofTypeName(field.Message, field), "::", PascalCase(variant.Name), "(_) => {}")
				}
			}
			p.Dedent()
			p.P("}")
			p.Dedent()
			p.P("}")
		}
	}
	if fieldHasValueValidation(field) {
		valueExpr, guardStart, guardEnd := validationValue(field, access)
		if guardStart != "" {
			p.P(guardStart)
			p.Indent()
		}
		for _, decorator := range field.Decorators {
			switch decorator.Name {
			case decoratorEmail:
				p.P("if !", valueExpr, ".validate_email() {")
				p.Indent()
				errorLine("must be a valid email address")
				p.Dedent()
				p.P("}")
			case "uuid":
				p.P("if uuid::Uuid::parse_str(", valueExpr, ".as_str()).is_err() {")
				p.Indent()
				errorLine("must be a valid UUID")
				p.Dedent()
				p.P("}")
			case "uri":
				p.P("if url::Url::parse(", valueExpr, ".as_str()).is_err() {")
				p.Indent()
				errorLine("must be a valid URI")
				p.Dedent()
				p.P("}")
			case "pattern":
				if pattern, ok := decorator.Value(); ok {
					p.P("if !regex::Regex::new(", strconv.Quote(pattern), ").expect(\"schema pattern was validated\").is_match(", valueExpr, ".as_str()) {")
					p.Indent()
					errorLine("does not match the required pattern")
					p.Dedent()
					p.P("}")
				}
			case "len":
				writeLengthValidation(p, decorator, valueExpr, errorLine)
			case "min_items":
				writeMinMaxItemsValidation(p, decorator, valueExpr, true, errorLine)
			case "max_items":
				writeMinMaxItemsValidation(p, decorator, valueExpr, false, errorLine)
			case "gt", "gte", "lt", "lte":
				writeNumericValidation(p, decorator, valueExpr, errorLine)
			case "range":
				writeRangeValidation(p, decorator, valueExpr, errorLine)
			case "in":
				writeInValidation(p, decorator, valueExpr, errorLine)
			}
		}
		if guardEnd != "" {
			p.Dedent()
			p.P(guardEnd)
		}
	}
	if field.Type != nil && field.Type.Kind == onkir.KindMessage {
		if field.Repeated {
			p.P("for value in &", access, " {")
			p.Indent()
			p.P("value.validate().map_err(|error| ValidationError { field: ", strconv.Quote(field.Name), ", message: error.to_string() })?;")
			p.Dedent()
			p.P("}")
		} else {
			p.P("if let Some(value) = &", access, " {")
			p.Indent()
			p.P("value.validate().map_err(|error| ValidationError { field: ", strconv.Quote(field.Name), ", message: error.to_string() })?;")
			p.Dedent()
			p.P("}")
		}
	}
}

func fieldHasValueValidation(field *onkir.Field) bool {
	for _, decorator := range field.Decorators {
		switch decorator.Name {
		case decoratorEmail, "uuid", "uri", "pattern", "len", "min_items", "max_items",
			"gt", "gte", "lt", "lte", "range", "in":
			return true
		}
	}
	return false
}

func validationValue(field *onkir.Field, access string) (string, string, string) {
	if field.Optional {
		return validationValueVar, "if let Some(value) = &" + access + " {", "}"
	}
	return access, "", ""
}

func writeLengthValidation(p *Printer, decorator onkir.Decorator, value string, fail func(string)) {
	minimum, minOK := decorator.Arg(0)
	maximum, maxOK := decorator.Arg(1)
	if minOK {
		p.P("if ", value, ".len() < ", minimum, " {")
		p.Indent()
		fail("is shorter than the minimum length")
		p.Dedent()
		p.P("}")
	}
	if maxOK {
		p.P("if ", value, ".len() > ", maximum, " {")
		p.Indent()
		fail("is longer than the maximum length")
		p.Dedent()
		p.P("}")
	}
}

func writeMinMaxItemsValidation(p *Printer, decorator onkir.Decorator, value string, minimum bool, fail func(string)) {
	limit, ok := decorator.Value()
	if !ok {
		return
	}
	operator := "<"
	message := "has too few items"
	if !minimum {
		operator = ">"
		message = "has too many items"
	}
	p.P("if ", value, ".len() ", operator, " ", limit, " {")
	p.Indent()
	fail(message)
	p.Dedent()
	p.P("}")
}

func writeNumericValidation(p *Printer, decorator onkir.Decorator, value string, fail func(string)) {
	limit, ok := decorator.Value()
	if !ok {
		return
	}
	operator := map[string]string{"gt": "<=", "gte": "<", "lt": ">=", "lte": ">"}[decorator.Name]
	if value == validationValueVar {
		value = "*" + value
	}
	p.P("if ", value, " ", operator, " ", limit, " {")
	p.Indent()
	fail("is outside the allowed numeric bound")
	p.Dedent()
	p.P("}")
}

func writeRangeValidation(p *Printer, decorator onkir.Decorator, value string, fail func(string)) {
	minimum, minOK := decorator.Arg(0)
	maximum, maxOK := decorator.Arg(1)
	if !minOK || !maxOK {
		return
	}
	if value == validationValueVar {
		value = "*" + value
	}
	p.P("if ", value, " < ", minimum, " || ", value, " > ", maximum, " {")
	p.Indent()
	fail("is outside the allowed range")
	p.Dedent()
	p.P("}")
}

func writeInValidation(p *Printer, decorator onkir.Decorator, value string, fail func(string)) {
	if len(decorator.Args) == 0 {
		return
	}
	values := make([]string, 0, len(decorator.Args))
	for _, arg := range decorator.Args {
		values = append(values, strconv.Quote(arg.Value))
	}
	p.P("if ![", strings.Join(values, ", "), "].contains(&", value, ".as_str()) {")
	p.Indent()
	fail("is not one of the allowed values")
	p.Dedent()
	p.P("}")
}
