package gendart

import (
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

func GenerateTypes(file *onkir.File) []byte {
	return GenerateTypesWithResolver(file, nil, "onekit.dart")
}

func GenerateTypesWithResolver(file *onkir.File, resolver PackageResolver, runtimeImport string) []byte {
	body := newPrinter(resolver)
	body.prepareRules(file)
	for _, e := range fileEnumsDeep(file) {
		writeEnum(body, e)
	}
	for _, m := range fileMessagesDeep(file) {
		writeMessage(body, m)
	}
	body.writeRuleSupport()
	code := string(body.Bytes())
	p := newPrinter(resolver)
	writeFileHeader(p, code)
	var dartImports []string
	if strings.Contains(code, "Uint8List") {
		dartImports = append(dartImports, "dart:typed_data")
	}
	var local []string
	if strings.Contains(code, "onekit") {
		local = append(local, "import '"+runtimeImport+"';")
	}
	for _, ref := range collectExternalRefs(file, resolver) {
		local = append(local, "import '"+ref.ImportPath+"' as "+ref.Alias+";")
	}
	writeImports(p, dartImports, nil, local)
	p.b.WriteString(code)
	return p.Bytes()
}

func writeFileHeader(p *Printer, code string) {
	p.P("// Code generated by onek. DO NOT EDIT.")
	if strings.Contains(code, "@Deprecated(") {
		p.P("// ignore_for_file: deprecated_member_use_from_same_package")
	}
	p.P()
}

func writeImports(p *Printer, dartImports, packageImports, local []string) {
	var lines []string
	for _, path := range dartImports {
		lines = append(lines, "import '"+path+"';")
	}
	for _, group := range [][]string{lines, packageImports, local} {
		if len(group) == 0 {
			continue
		}
		for _, line := range group {
			p.P(line)
		}
		p.P()
	}
}

func writeDoc(p *Printer, doc string) {
	if doc = strings.TrimSpace(doc); doc == "" {
		return
	}
	for line := range strings.SplitSeq(doc, "\n") {
		if line = strings.TrimRight(line, " \t"); line == "" {
			p.P("///")
		} else {
			p.P("/// ", line)
		}
	}
}

func writeDeprecated(p *Printer, deprecated func() (string, bool)) {
	reason, ok := deprecated()
	if !ok {
		return
	}
	if reason == "" {
		reason = "no longer supported"
	}
	p.P("@Deprecated(", dartString(reason), ")")
}

func dartString(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `'`, `\'`, "$", `\$`, "\n", `\n`, "\r", `\r`, "\t", `\t`)
	return "'" + r.Replace(s) + "'"
}

func writeEnum(p *Printer, e *onkir.Enum) {
	name := EnumName(e)
	writeDoc(p, e.Doc)
	p.P("enum ", name, " {")
	p.Indent()
	for i, v := range e.Values {
		writeDoc(p, v.Doc)
		sep := ","
		if i == len(e.Values)-1 {
			sep = ";"
		}
		p.P(EnumValueName(v), "(", dartString(v.JSONName()), ")", sep)
	}
	p.P()
	p.P("const ", name, "(this.wire);")
	p.P()
	p.P("final String wire;")
	p.P()
	p.P("static ", name, " fromWire(Object? value) => values.firstWhere(")
	p.Indent()
	p.P("(v) => v.wire == value,")
	p.P("orElse: () => throw FormatException(", dartString("unknown "+e.Name+" value: "), " + '$value'),")
	p.Dedent()
	p.P(");")
	p.Dedent()
	p.P("}")
	p.P()
}

func (p *Printer) elemType(t *onkir.Type) string {
	switch t.Kind {
	case onkir.KindMessage:
		return p.MessageTypeName(t.Message)
	case onkir.KindEnum:
		return p.EnumTypeName(t.Enum)
	case onkir.KindMap:
		return "Map<String, " + p.elemType(t.MapValue) + ">"
	case onkir.KindScalar:
		switch t.Scalar {
		case onkir.ScalarString:
			return "String"
		case onkir.ScalarBool:
			return "bool"
		case onkir.ScalarInt32, onkir.ScalarUint32, onkir.ScalarInt64:
			return "int"
		case onkir.ScalarUint64:
			return "BigInt"
		case onkir.ScalarFloat32, onkir.ScalarFloat64:
			return "double"
		case onkir.ScalarBytes:
			return "Uint8List"
		case onkir.ScalarTimestamp:
			return "DateTime"
		case onkir.ScalarJSON:
			return "Object?"
		}
	}
	return "Object?"
}

func isNullableKind(f *onkir.Field) bool {
	if f.Oneof != nil {
		return true
	}
	if f.Repeated || f.Type.Kind == onkir.KindMap {
		return false
	}
	if f.Optional || f.Type.Kind == onkir.KindMessage {
		return true
	}
	return f.Type.Kind == onkir.KindScalar && (f.Type.Scalar == onkir.ScalarTimestamp || f.Type.Scalar == onkir.ScalarJSON)
}

func (p *Printer) fieldType(m *onkir.Message, f *onkir.Field) string {
	if f.Oneof != nil {
		return OneofTypeName(m, f) + "?"
	}
	elem := p.elemType(f.Type)
	switch {
	case f.Repeated:
		return "List<" + elem + ">"
	case f.Type.Kind == onkir.KindMap:
		return elem
	case isNullableKind(f) && !strings.HasSuffix(elem, "?"):
		return elem + "?"
	}
	return elem
}

func (p *Printer) defaultValue(t *onkir.Type) string {
	switch t.Kind {
	case onkir.KindEnum:
		return p.EnumTypeName(t.Enum) + ".values.first"
	case onkir.KindMessage:
		return p.MessageTypeName(t.Message) + ".fromJson(const <String, dynamic>{})"
	case onkir.KindMap:
		return "{}"
	case onkir.KindScalar:
		switch t.Scalar {
		case onkir.ScalarString:
			return "''"
		case onkir.ScalarBool:
			return "false"
		case onkir.ScalarInt32, onkir.ScalarUint32, onkir.ScalarInt64:
			return "0"
		case onkir.ScalarUint64:
			return "BigInt.zero"
		case onkir.ScalarFloat32, onkir.ScalarFloat64:
			return "0.0"
		case onkir.ScalarBytes:
			return "Uint8List(0)"
		case onkir.ScalarTimestamp:
			return "DateTime.fromMillisecondsSinceEpoch(0, isUtc: true)"
		}
	}
	return "null"
}

func constDefault(t *onkir.Type) (string, bool) {
	if t.Kind != onkir.KindScalar {
		return "", false
	}
	switch t.Scalar {
	case onkir.ScalarString:
		return "''", true
	case onkir.ScalarBool:
		return "false", true
	case onkir.ScalarInt32, onkir.ScalarUint32, onkir.ScalarInt64:
		return "0", true
	case onkir.ScalarFloat32, onkir.ScalarFloat64:
		return "0.0", true
	}
	return "", false
}

func (p *Printer) encodeValue(t *onkir.Type, f *onkir.Field, expr string, inMap bool) string {
	switch t.Kind {
	case onkir.KindMessage:
		return expr + ".toJson()"
	case onkir.KindEnum:
		if !inMap && enumAsNumber(f) {
			return expr + ".index"
		}
		return expr + ".wire"
	case onkir.KindMap:
		inner := p.encodeValue(t.MapValue, nil, "v", true)
		if inner == "v" {
			return expr
		}
		return expr + ".map((k, v) => MapEntry(k, " + inner + "))"
	case onkir.KindScalar:
		switch t.Scalar {
		case onkir.ScalarInt64:
			if !inMap && (f == nil || int64AsString(f)) {
				return expr + ".toString()"
			}
		case onkir.ScalarUint64:
			if !inMap && (f == nil || int64AsString(f)) {
				return expr + ".toString()"
			}
			return expr + ".toInt()"
		case onkir.ScalarBytes:
			enc := ""
			if !inMap {
				enc = bytesEncoding(f)
			}
			return "onekitBytesEncode(" + expr + ", " + dartString(enc) + ")"
		case onkir.ScalarTimestamp:
			enc := ""
			if !inMap {
				enc = timestampEncoding(f)
			}
			return "onekitTimeEncode(" + expr + ", " + dartString(enc) + ")"
		}
	}
	return expr
}

func (p *Printer) decodeValue(t *onkir.Type, f *onkir.Field, expr string, inMap bool) string {
	switch t.Kind {
	case onkir.KindMessage:
		return p.MessageTypeName(t.Message) + ".fromJson(" + expr + ")"
	case onkir.KindEnum:
		if !inMap && enumAsNumber(f) {
			return "onekitEnumByIndex(" + p.EnumTypeName(t.Enum) + ".values, " + expr + ")"
		}
		return p.EnumTypeName(t.Enum) + ".fromWire(" + expr + ")"
	case onkir.KindMap:
		return "onekitMap(" + expr + ", (v) => " + p.decodeValue(t.MapValue, nil, "v", true) + ")"
	case onkir.KindScalar:
		switch t.Scalar {
		case onkir.ScalarString:
			return "onekitString(" + expr + ")"
		case onkir.ScalarBool:
			return "onekitBool(" + expr + ")"
		case onkir.ScalarInt32, onkir.ScalarUint32, onkir.ScalarInt64:
			return "onekitInt(" + expr + ")"
		case onkir.ScalarUint64:
			return "onekitBigInt(" + expr + ")"
		case onkir.ScalarFloat32, onkir.ScalarFloat64:
			return "onekitDouble(" + expr + ")"
		case onkir.ScalarBytes:
			enc := ""
			if !inMap {
				enc = bytesEncoding(f)
			}
			return "onekitBytesDecode(" + expr + ", " + dartString(enc) + ")"
		case onkir.ScalarTimestamp:
			enc := ""
			if !inMap {
				enc = timestampEncoding(f)
			}
			return "onekitTimeDecode(" + expr + ", " + dartString(enc) + ")"
		}
	}
	return expr
}

func (p *Printer) fieldWireValue(f *onkir.Field, expr string) string {
	if f.Repeated {
		inner := p.encodeValue(f.Type, f, "v", false)
		if inner == "v" {
			return expr
		}
		return expr + ".map((v) => " + inner + ").toList()"
	}
	return p.encodeValue(f.Type, f, expr, false)
}

func (p *Printer) fieldFromWire(f *onkir.Field, expr string) string {
	if f.Repeated {
		return "onekitList(" + expr + ", (v) => " + p.decodeValue(f.Type, f, "v", false) + ")"
	}
	return p.decodeValue(f.Type, f, expr, false)
}

func writeMessage(p *Printer, m *onkir.Message) {
	name := MessageName(m)
	root := rootUnwrapField(m)
	writeDoc(p, m.Doc)
	if m.IsError() {
		p.P("class ", name, " implements Exception {")
	} else {
		p.P("class ", name, " {")
	}
	p.Indent()
	writeConstructor(p, m)
	for _, f := range m.Fields {
		writeDoc(p, f.Doc)
		writeDeprecated(p, f.Deprecated)
		p.P(p.fieldType(m, f), " ", Ident(f.Name), ";")
		p.P()
	}
	if root != nil {
		writeRootUnwrapCodec(p, m, root)
	} else {
		writeToJSON(p, m)
		writeFromJSON(p, m)
	}
	writeValidate(p, m)
	p.P("@override")
	p.P("bool operator ==(Object other) => other is ", name, " && onekitJsonEquals(toJson(), other.toJson());")
	p.P()
	p.P("@override")
	p.P("int get hashCode => onekitJsonHash(toJson());")
	p.P()
	p.P("@override")
	p.P("String toString() => ", dartString(name), " + '(${toJson()})';")
	p.Dedent()
	p.P("}")
	p.P()
	for _, f := range m.Fields {
		if f.Oneof != nil {
			writeOneof(p, m, f)
		}
	}
}

func writeConstructor(p *Printer, m *onkir.Message) {
	name := MessageName(m)
	if len(m.Fields) == 0 {
		p.P(name, "();")
		p.P()
		return
	}
	var params, inits []string
	for _, f := range m.Fields {
		id := Ident(f.Name)
		switch {
		case isNullableKind(f):
			params = append(params, "this."+id)
		case f.Repeated:
			params = append(params, "List<"+p.elemType(f.Type)+">? "+id)
			inits = append(inits, id+" = "+id+" ?? []")
		case f.Type.Kind == onkir.KindMap:
			params = append(params, p.elemType(f.Type)+"? "+id)
			inits = append(inits, id+" = "+id+" ?? {}")
		case f.Type.Kind == onkir.KindEnum:
			params = append(params, "this."+id+" = "+p.EnumTypeName(f.Type.Enum)+"."+EnumValueName(f.Type.Enum.Values[0]))
		default:
			if value, ok := constDefault(f.Type); ok {
				params = append(params, "this."+id+" = "+value)
			} else {
				params = append(params, p.elemType(f.Type)+"? "+id)
				inits = append(inits, id+" = "+id+" ?? "+p.defaultValue(f.Type))
			}
		}
	}
	p.P(name, "({")
	p.Indent()
	for _, param := range params {
		p.P(param, ",")
	}
	p.Dedent()
	if len(inits) == 0 {
		p.P("});")
		p.P()
		return
	}
	for i, init := range inits {
		prefix, suffix := "    ", ","
		if i == 0 {
			prefix = "}) : "
		}
		if i == len(inits)-1 {
			suffix = ";"
		}
		p.P(prefix, init, suffix)
	}
	p.P()
}

func writeToJSON(p *Printer, m *onkir.Message) {
	p.P("Map<String, dynamic> toJson() {")
	p.Indent()
	p.P("final json = <String, dynamic>{};")
	for _, f := range m.Fields {
		writeToJSONField(p, f)
	}
	p.P("return json;")
	p.Dedent()
	p.P("}")
	p.P()
}

func writeToJSONField(p *Printer, f *onkir.Field) {
	id := Ident(f.Name)
	key := dartString(f.Name)
	if f.Oneof != nil {
		p.P("if (", id, " != null) json[", key, "] = ", id, "!.toJson();")
		return
	}
	value := p.fieldWireValue(f, id)
	switch {
	case f.Repeated:
		p.P("if (", id, ".isNotEmpty) json[", key, "] = ", value, ";")
	case f.Type.Kind == onkir.KindMap:
		p.P("if (", id, ".isNotEmpty) json[", key, "] = ", value, ";")
	case f.Type.Kind == onkir.KindMessage:
		writeMessageFieldToJSON(p, f)
	case f.Optional, f.Type.Kind == onkir.KindEnum, int64AsString(f):
		if isNullableKind(f) {
			p.P("if (", id, " != null) json[", key, "] = ", p.encodeValue(f.Type, f, id+"!", false), ";")
		} else {
			p.P("json[", key, "] = ", value, ";")
		}
	case f.Type.Kind == onkir.KindScalar && (f.Type.Scalar == onkir.ScalarTimestamp || f.Type.Scalar == onkir.ScalarJSON):
		p.P("if (", id, " != null) json[", key, "] = ", p.encodeValue(f.Type, f, id+"!", false), ";")
	case f.Type.Kind == onkir.KindScalar && f.Type.Scalar == onkir.ScalarBytes:
		p.P("if (", id, ".isNotEmpty) json[", key, "] = ", value, ";")
	case f.Type.Kind == onkir.KindScalar && f.Type.Scalar == onkir.ScalarUint64:
		p.P("if (", id, " != BigInt.zero) json[", key, "] = ", value, ";")
	default:
		zero, _ := constDefault(f.Type)
		p.P("if (", id, " != ", zero, ") json[", key, "] = ", value, ";")
	}
}

func writeMessageFieldToJSON(p *Printer, f *onkir.Field) {
	id := Ident(f.Name)
	key := dartString(f.Name)
	if prefix, ok := flattenPrefix(f); ok {
		p.P("if (", id, " != null) {")
		p.Indent()
		p.P("for (final entry in ", id, "!.toJson().entries) {")
		p.Indent()
		p.P("json[", dartString(prefix), " + entry.key] = entry.value;")
		p.Dedent()
		p.P("}")
		p.Dedent()
		p.P("}")
		return
	}
	switch emptyBehavior(f) {
	case emptyBehaviorNull:
		p.P("final ", id, "Json = ", id, "?.toJson();")
		p.P("json[", key, "] = ", id, "Json == null || ", id, "Json.isEmpty ? null : ", id, "Json;")
	case "omit":
		p.P("final ", id, "Json = ", id, "?.toJson();")
		p.P("if (", id, "Json != null && ", id, "Json.isNotEmpty) json[", key, "] = ", id, "Json;")
	default:
		p.P("if (", id, " != null) json[", key, "] = ", id, "!.toJson();")
	}
}

func writeFromJSON(p *Printer, m *onkir.Message) {
	name := MessageName(m)
	p.P("factory ", name, ".fromJson(Object? value) {")
	p.Indent()
	if len(m.Fields) == 0 {
		p.P("onekitObject(value);")
		p.P("return ", name, "();")
		p.Dedent()
		p.P("}")
		p.P()
		return
	}
	p.P("final json = onekitObject(value);")
	p.P("return ", name, "(")
	p.Indent()
	for _, f := range m.Fields {
		p.P(Ident(f.Name), ": ", p.fromJSONExpr(m, f), ",")
	}
	p.Dedent()
	p.P(");")
	p.Dedent()
	p.P("}")
	p.P()
}

func (p *Printer) fromJSONExpr(m *onkir.Message, f *onkir.Field) string {
	raw := "json[" + dartString(f.Name) + "]"
	if f.Oneof != nil {
		return OneofTypeName(m, f) + ".fromJson(" + raw + ")"
	}
	if prefix, ok := flattenPrefix(f); ok {
		return "onekitHasPrefix(json, " + dartString(prefix) + ") ? " + p.MessageTypeName(f.Type.Message) +
			".fromJson(onekitStripPrefix(json, " + dartString(prefix) + ")) : null"
	}
	decoded := p.fieldFromWire(f, raw)
	if decoded == raw {
		return raw
	}
	if isNullableKind(f) {
		return raw + " == null ? null : " + decoded
	}
	if f.Repeated || f.Type.Kind == onkir.KindMap {
		return raw + " == null ? null : " + decoded
	}
	return raw + " == null ? " + p.defaultValue(f.Type) + " : " + decoded
}

func writeRootUnwrapCodec(p *Printer, m *onkir.Message, f *onkir.Field) {
	name := MessageName(m)
	id := Ident(f.Name)
	value := p.fieldWireValue(f, id)
	if isNullableKind(f) {
		value = id + " == null ? null : " + p.encodeValue(f.Type, f, id+"!", false)
	}
	p.P("Object? toJson() => ", value, ";")
	p.P()
	decoded := p.fieldFromWire(f, "value")
	p.P("factory ", name, ".fromJson(Object? value) => ", name, "(", id, ": value == null ? null : ", decoded, ");")
	p.P()
}

func writeOneof(p *Printer, m *onkir.Message, f *onkir.Field) {
	base := OneofTypeName(m, f)
	disc := dartString(oneofDiscriminator(f))
	p.P("sealed class ", base, " {")
	p.Indent()
	p.P("const ", base, "();")
	p.P()
	p.P("Map<String, dynamic> toJson();")
	p.P()
	p.P("static ", base, "? fromJson(Object? value) {")
	p.Indent()
	p.P("if (value is! Map) return null;")
	p.P("final json = onekitObject(value);")
	p.P("switch (json[", disc, "]) {")
	p.Indent()
	for _, v := range f.Oneof.Variants {
		p.P("case ", dartString(v.Tag()), ":")
		p.Indent()
		p.P("return ", OneofVariantClassName(m, f, v), ".fromJson(json);")
		p.Dedent()
	}
	p.Dedent()
	p.P("}")
	p.P("return null;")
	p.Dedent()
	p.P("}")
	p.Dedent()
	p.P("}")
	p.P()
	for _, v := range f.Oneof.Variants {
		writeOneofVariant(p, m, f, v)
	}
}

func writeOneofVariant(p *Printer, m *onkir.Message, f *onkir.Field, v *onkir.OneofVariant) {
	name := OneofVariantClassName(m, f, v)
	id := Ident(v.Name)
	disc := dartString(oneofDiscriminator(f))
	tag := dartString(v.Tag())
	synthetic := &onkir.Field{Name: v.Name, Type: v.Type}
	valueType := p.elemType(v.Type)
	p.P("final class ", name, " extends ", OneofTypeName(m, f), " {")
	p.Indent()
	p.P(name, "(this.", id, ");")
	p.P()
	p.P("final ", valueType, " ", id, ";")
	p.P()
	p.P("@override")
	if f.Oneof.Flatten() {
		p.P("Map<String, dynamic> toJson() => {...", id, ".toJson(), ", disc, ": ", tag, "};")
	} else {
		p.P("Map<String, dynamic> toJson() => {", disc, ": ", tag, ", ", dartString(v.Name), ": ", p.encodeValue(v.Type, synthetic, id, false), "};")
	}
	p.P()
	if f.Oneof.Flatten() {
		p.P("factory ", name, ".fromJson(Map<String, dynamic> json) => ", name, "(", p.MessageTypeName(v.Type.Message), ".fromJson(json));")
	} else {
		raw := "json[" + dartString(v.Name) + "]"
		missing := p.defaultValue(v.Type)
		if v.Type.Kind == onkir.KindScalar && v.Type.Scalar == onkir.ScalarJSON {
			missing = "null"
		}
		p.P("factory ", name, ".fromJson(Map<String, dynamic> json) => ", name, "(", raw, " == null ? ", missing, " : ", p.decodeValue(v.Type, synthetic, raw, false), ");")
	}
	p.P()
	p.P("@override")
	p.P("bool operator ==(Object other) => other is ", name, " && onekitJsonEquals(toJson(), other.toJson());")
	p.P()
	p.P("@override")
	p.P("int get hashCode => onekitJsonHash(toJson());")
	p.P()
	p.P("@override")
	p.P("String toString() => ", dartString(name), " + '(${toJson()})';")
	p.Dedent()
	p.P("}")
	p.P()
}

var dartIntegerBounds = map[onkir.ScalarKind][2]string{
	onkir.ScalarInt32:  {"-2147483648", "2147483647"},
	onkir.ScalarUint32: {"0", "4294967295"},
}

func writeValidate(p *Printer, m *onkir.Message) {
	p.P("List<String> validate() {")
	p.Indent()
	p.P("final violations = <String>[];")
	for _, f := range m.Fields {
		id := Ident(f.Name)
		nested := func(expr string) {
			p.P("for (final e in ", expr, ".validate()) {")
			p.Indent()
			p.P("violations.add(", dartString(f.Name+": "), " + e);")
			p.Dedent()
			p.P("}")
		}
		if f.Oneof != nil {
			for _, v := range f.Oneof.Variants {
				if v.Type.Kind != onkir.KindMessage {
					continue
				}
				local := id + PascalCase(v.Name)
				p.P("final ", local, " = ", id, ";")
				p.P("if (", local, " is ", OneofVariantClassName(m, f, v), ") {")
				p.Indent()
				nested(local + "." + Ident(v.Name))
				p.Dedent()
				p.P("}")
			}
		}
		if f.HasDecorator("required") {
			switch {
			case f.Repeated || f.Type != nil && f.Type.Kind == onkir.KindMap:
				p.P("if (", id, ".isEmpty) violations.add(", dartString(f.Name+" is required"), ");")
			case f.Oneof == nil && f.Type.Kind == onkir.KindScalar && f.Type.Scalar == onkir.ScalarString && !isNullableKind(f):
				p.P("if (", id, ".isEmpty) violations.add(", dartString(f.Name+" is required"), ");")
			case f.Oneof == nil && f.Type.Kind == onkir.KindScalar && f.Type.Scalar == onkir.ScalarString:
				p.P("if (", id, " == null || ", id, "!.isEmpty) violations.add(", dartString(f.Name+" is required"), ");")
			case isNullableKind(f):
				p.P("if (", id, " == null) violations.add(", dartString(f.Name+" is required"), ");")
			}
		}
		if f.Oneof != nil {
			continue
		}
		if f.Repeated {
			if d, ok := f.Decorator("min_items"); ok {
				value, _ := d.Value()
				p.P("if (", id, ".length < ", value, ") violations.add(", dartString(f.Name+" must contain at least "+value+" items"), ");")
			}
			if d, ok := f.Decorator("max_items"); ok {
				value, _ := d.Value()
				p.P("if (", id, ".length > ", value, ") violations.add(", dartString(f.Name+" must contain at most "+value+" items"), ");")
			}
			if f.Type.Kind == onkir.KindMessage {
				p.P("for (final item in ", id, ") {")
				p.Indent()
				nested("item")
				p.Dedent()
				p.P("}")
			}
			continue
		}
		switch f.Type.Kind {
		case onkir.KindMessage:
			local := id + "Value"
			p.P("final ", local, " = ", id, ";")
			p.P("if (", local, " != null) {")
			p.Indent()
			nested(local)
			p.Dedent()
			p.P("}")
			continue
		case onkir.KindMap:
			if f.Type.MapValue != nil && f.Type.MapValue.Kind == onkir.KindMessage {
				p.P("for (final item in ", id, ".values) {")
				p.Indent()
				nested("item")
				p.Dedent()
				p.P("}")
			}
			continue
		case onkir.KindScalar:
		default:
			continue
		}
		value := id
		if isNullableKind(f) {
			value = id + "Value"
			p.P("final ", value, " = ", id, ";")
			p.P("if (", value, " != null) {")
			p.Indent()
		}
		writeScalarRules(p, f, value)
		if isNullableKind(f) {
			p.Dedent()
			p.P("}")
		}
	}
	p.writeRuleValidateHook(m)
	p.P("return violations;")
	p.Dedent()
	p.P("}")
	p.P()
}

func writeScalarRules(p *Printer, f *onkir.Field, v string) {
	add := func(cond, msg string) {
		p.P("if (", cond, ") violations.add(", dartString(msg), ");")
	}
	if bounds, ok := dartIntegerBounds[f.Type.Scalar]; ok {
		add(v+" < "+bounds[0]+" || "+v+" > "+bounds[1], f.Name+" must be a "+f.Type.Scalar.String())
	}
	if f.Type.Scalar == onkir.ScalarUint64 {
		add(v+" < BigInt.zero || "+v+" > onekitMaxUint64", f.Name+" must be a uint64")
	}
	if f.Type.Scalar == onkir.ScalarString {
		if f.HasDecorator("email") {
			add(v+".isNotEmpty && !onekitEmailPattern.hasMatch("+v+")", f.Name+" must be a valid email")
		}
		if f.HasDecorator("uuid") {
			add(v+".isNotEmpty && !onekitUuidPattern.hasMatch("+v+")", f.Name+" must be a valid UUID")
		}
		if f.HasDecorator("uri") {
			add(v+".isNotEmpty && !onekitUriPattern.hasMatch("+v+")", f.Name+" must be a valid URI")
		}
		if d, ok := f.Decorator("pattern"); ok {
			pattern, _ := d.Value()
			add(v+".isNotEmpty && !RegExp("+dartString(pattern)+").hasMatch("+v+")", f.Name+" has invalid format")
		}
		if d, ok := f.Decorator("len"); ok && len(d.Args) == 2 {
			add(v+".runes.length < "+d.Args[0].Value+" || "+v+".runes.length > "+d.Args[1].Value, f.Name+" has invalid length")
		}
		if d, ok := f.Decorator("in"); ok {
			values := make([]string, 0, len(d.Args))
			for _, arg := range d.Args {
				values = append(values, dartString(arg.Value))
			}
			add("!const ["+strings.Join(values, ", ")+"].contains("+v+")", f.Name+" must be one of the allowed values")
		}
		return
	}
	if !isNumeric(f.Type.Scalar) {
		return
	}
	lit := func(value string) string {
		if f.Type.Scalar == onkir.ScalarUint64 {
			return "BigInt.parse(" + dartString(value) + ")"
		}
		if (f.Type.Scalar == onkir.ScalarFloat32 || f.Type.Scalar == onkir.ScalarFloat64) && !strings.ContainsAny(value, ".eE") {
			return value + ".0"
		}
		return value
	}
	if d, ok := f.Decorator("in"); ok {
		values := make([]string, 0, len(d.Args))
		for _, arg := range d.Args {
			values = append(values, lit(arg.Value))
		}
		prefix := "const "
		if f.Type.Scalar == onkir.ScalarUint64 {
			prefix = ""
		}
		add("!"+prefix+"["+strings.Join(values, ", ")+"].contains("+v+")", f.Name+" must be one of the allowed values")
	}
	if d, ok := f.Decorator("range"); ok && len(d.Args) == 2 {
		add(v+" < "+lit(d.Args[0].Value)+" || "+v+" > "+lit(d.Args[1].Value), f.Name+" violates @range")
	}
	for _, rule := range []struct{ name, op string }{{"gt", "<="}, {"gte", "<"}, {"lt", ">="}, {"lte", ">"}} {
		if d, ok := f.Decorator(rule.name); ok {
			value, _ := d.Value()
			add(v+" "+rule.op+" "+lit(value), f.Name+" violates @"+rule.name)
		}
	}
}

func isNumeric(kind onkir.ScalarKind) bool {
	switch kind {
	case onkir.ScalarInt32, onkir.ScalarInt64, onkir.ScalarUint32, onkir.ScalarUint64, onkir.ScalarFloat32, onkir.ScalarFloat64:
		return true
	}
	return false
}
