package genpy

import (
	"fmt"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

// GenerateClient generates client.py treating every message/enum type as
// local. Use GenerateClientWithResolver for a multi-package project where
// some referenced types live in a different generated module.
func GenerateClient(file *onkir.File, typesModule string) []byte {
	return GenerateClientWithResolver(file, typesModule, nil)
}

func GenerateClientWithResolver(file *onkir.File, typesModule string, resolver PackageResolver) []byte {
	if len(file.Services) == 0 {
		return nil
	}

	p := newPrinter(resolver)
	p.P("# Code generated by onek. DO NOT EDIT.")
	p.P("from __future__ import annotations")
	p.P()
	p.P("import builtins as _builtins")
	p.P("import json")
	p.P("import urllib.error")
	p.P("import urllib.parse")
	p.P("import urllib.request")
	if onkir.FileHasStreamMethods(file) {
		p.P("from typing import Iterator")
	}
	p.P()
	if names := localReferencedTypeNames(file, resolver); len(names) > 0 {
		p.P("try:")
		p.Indent()
		p.P("from .models import ", strings.Join(names, ", "))
		p.Dedent()
		p.P("except ImportError:")
		p.Indent()
		p.P("from ", typesModule, " import ", strings.Join(names, ", "))
		p.Dedent()
	}
	for _, ref := range collectServiceExternalRefs(file, resolver) {
		writePyModuleImport(p, ref)
	}
	p.P()

	writeResponseBodyRuntime(p)
	if onkir.FileHasWSMethods(file) {
		writePyWSRuntime(p)
		writePyWSCodecs(p, file)
	}

	for _, s := range file.Services {
		writeClientClass(p, s)
	}

	return p.Bytes()
}

// localReferencedTypeNames returns the request/response/error type names that
// belong to this same generated module - the ones the caller should import
// via `from {typesModule} import ...`. Types resolved to a different module
// get their own qualified import instead (see collectServiceExternalRefs).
func localReferencedTypeNames(file *onkir.File, resolver PackageResolver) []string {
	seen := map[string]bool{}
	var names []string
	add := func(m *onkir.Message) {
		if resolver != nil {
			if _, ok := resolver.ResolveMessage(m); ok {
				return
			}
		}
		if !seen[m.Name] {
			seen[m.Name] = true
			names = append(names, m.Name)
		}
	}
	for _, s := range file.Services {
		for _, m := range s.Methods {
			add(m.Request)
			add(m.Response)
			for _, errType := range m.ErrorTypes {
				add(errType)
			}
		}
	}
	return names
}

func writeClientClass(p *Printer, s *onkir.Service) {
	p.P("class ", s.Name, "Client:")
	p.Indent()
	writePyDoc(p, s.Doc)
	hasWS := false
	for _, m := range s.Methods {
		hasWS = hasWS || m.IsWebSocket()
	}
	wsParams := ""
	if hasWS {
		wsParams = ", max_ws_frame_bytes: int = DEFAULT_MAX_WS_FRAME_BYTES, max_ws_message_bytes: int = DEFAULT_MAX_WS_MESSAGE_BYTES, ws_ping_interval: float = 30.0"
	}
	p.P("def __init__(self, base_url: str, headers: dict | None = None, max_response_body_bytes: int = DEFAULT_MAX_RESPONSE_BODY_BYTES, max_sse_line_bytes: int = DEFAULT_MAX_SSE_LINE_BYTES, timeout: float | None = 30.0", wsParams, ") -> None:")
	p.Indent()
	if hasWS {
		p.P("self.max_ws_frame_bytes = max_ws_frame_bytes")
		p.P("self.max_ws_message_bytes = max_ws_message_bytes if max_ws_message_bytes != 0 else DEFAULT_MAX_WS_MESSAGE_BYTES")
		p.P("self.ws_ping_interval = ws_ping_interval")
	}
	p.P("self.base_url = base_url.rstrip(\"/\")")
	p.P("self.headers = headers or {}")
	p.P("self.timeout = timeout")
	p.P("self.max_response_body_bytes = max_response_body_bytes if max_response_body_bytes > 0 else DEFAULT_MAX_RESPONSE_BODY_BYTES")
	p.P("self.max_sse_line_bytes = max_sse_line_bytes if max_sse_line_bytes > 0 else DEFAULT_MAX_SSE_LINE_BYTES")
	p.Dedent()
	p.Blank()

	for _, m := range s.Methods {
		switch {
		case m.IsWebSocket():
			writePyWSClientMethod(p, s, m)
		case m.IsStream():
			writeSSEClientMethod(p, s, m)
		default:
			writeClientMethod(p, s, m)
		}
	}
	p.Dedent()
	p.Blank()
}

func writeSSEClientMethod(p *Printer, s *onkir.Service, m *onkir.Method) {
	verb, _ := m.Verb()
	path, _ := m.Path()
	fullPath := s.BasePath + path
	p.P("def ", SnakeCase(m.Name), "(self, req: ", p.MessageTypeName(m.Request), ") -> Iterator[", p.MessageTypeName(m.Response), "]:")
	p.Indent()
	writePyDoc(p, m.Doc)
	p.P("if hasattr(req, \"validate\"): req.validate()")
	p.P(fmt.Sprintf("path = %q", fullPath))
	writePyPathParams(p, path, m.Request)
	writeClientQueryParams(p, m.Request)
	p.P(fmt.Sprintf("request = urllib.request.Request(self.base_url + path, method=%q)", strings.ToUpper(verb)))
	p.P(`request.add_header("Accept", "text/event-stream")`)
	p.P("for k, v in self.headers.items():")
	p.Indent()
	p.P("request.add_header(k, v)")
	p.Dedent()
	p.P("try:")
	p.Indent()
	p.P("with urllib.request.urlopen(request) as resp:")
	p.Indent()
	p.P("event = \"\"")
	p.P("data_lines: list[str] = []")
	p.P("while True:")
	p.Indent()
	p.P("raw_line = resp.readline(self.max_sse_line_bytes + 1)")
	p.P("if not raw_line: break")
	p.P("if len(raw_line) > self.max_sse_line_bytes: raise ValueError(\"SSE line exceeds configured limit\")")
	p.P("line = raw_line.decode(\"utf-8\").rstrip(\"\\r\\n\")")
	p.P(`if line == "":`)
	p.Indent()
	p.P("if data_lines:")
	p.Indent()
	p.P(`payload = json.loads("\n".join(data_lines))`)
	p.P(`if event == "error": raise StreamError(payload)`)
	p.P("yield ", p.MessageTypeName(m.Response), ".from_dict(payload)")
	p.Dedent()
	p.P(`event, data_lines = "", []`)
	p.P("continue")
	p.Dedent()
	p.P(`if line.startswith(":"): continue`)
	p.P(`name, _, value = line.partition(":")`)
	p.P(`if value.startswith(" "): value = value[1:]`)
	p.P(`if name == "event": event = value`)
	p.P(`elif name == "data": data_lines.append(value)`)
	p.Dedent()
	p.Dedent()
	p.Dedent()
	p.P("except urllib.error.HTTPError as e:")
	p.Indent()
	p.P("error_body = _read_bounded(e, self.max_response_body_bytes)")
	writePyTypedErrorHandling(p, m)
	p.P(`raise UnexpectedStatusError(e.code, error_body, dict(e.headers.items()) if e.headers else {}) from None`)
	p.Dedent()
	p.Dedent()
	p.Blank()
}

func writeClientMethod(p *Printer, s *onkir.Service, m *onkir.Method) {
	verb, _ := m.Verb()
	path, _ := m.Path()
	fullPath := s.BasePath + path
	bodyBearing := onkir.IsBodyBearingVerb(verb)

	p.P("def ", SnakeCase(m.Name), "(self, req: ", p.MessageTypeName(m.Request),
		") -> ", p.MessageTypeName(m.Response), ":")
	p.Indent()
	writePyDoc(p, m.Doc)
	p.P("if hasattr(req, \"validate\"): req.validate()")

	p.P(fmt.Sprintf("path = %q", fullPath))
	writePyPathParams(p, path, m.Request)

	if !bodyBearing {
		writeClientQueryParams(p, m.Request)
	}

	if bodyBearing {
		if bodyField, ok := m.BodyField(); ok {
			if field := onkir.FindField(m.Request, bodyField); field != nil {
				p.P("body = json.dumps(", p.bodyValueExpr(field, "req."+field.Name), ").encode(\"utf-8\")")
			} else {
				p.P("body = json.dumps(req.to_dict()[", fmt.Sprintf("%q", bodyField), "]).encode(\"utf-8\")")
			}
		} else {
			p.P("body = json.dumps(req.to_dict()).encode(\"utf-8\")")
		}
		p.P(fmt.Sprintf(
			"request = urllib.request.Request(self.base_url + path, data=body, method=%q)",
			strings.ToUpper(verb),
		))
		p.P(`request.add_header("Content-Type", "application/json")`)
	} else {
		p.P(fmt.Sprintf("request = urllib.request.Request(self.base_url + path, method=%q)", strings.ToUpper(verb)))
	}
	p.P("for k, v in self.headers.items():")
	p.Indent()
	p.P("request.add_header(k, v)")
	p.Dedent()
	p.Blank()

	p.P("try:")
	p.Indent()
	p.P("with urllib.request.urlopen(request, timeout=self.timeout) as resp:")
	p.Indent()
	p.P("return ", p.MessageTypeName(m.Response), ".from_dict(json.loads(_read_bounded(resp, self.max_response_body_bytes)))")
	p.Dedent()
	p.Dedent()
	p.P("except urllib.error.HTTPError as e:")
	p.Indent()
	p.P("error_body = _read_bounded(e, self.max_response_body_bytes)")
	writePyTypedErrorHandling(p, m)
	p.P(`raise UnexpectedStatusError(e.code, error_body, dict(e.headers.items()) if e.headers else {}) from None`)
	p.Dedent()
	p.Dedent()
	p.Blank()
}

// writePyTypedErrorHandling emits the status-matching ladder shared by the
// streaming and non-streaming client methods. A non-JSON error body must fall
// through to the generic exception instead of masking the HTTPError with an
// uncaught JSONDecodeError.
func writePyTypedErrorHandling(p *Printer, m *onkir.Method) {
	for _, errType := range m.ErrorTypes {
		status := 500
		if code, ok := errType.StatusCode(); ok {
			status = code
		}
		p.P(fmt.Sprintf("if e.code == %d:", status))
		p.Indent()
		p.P("try:")
		p.Indent()
		p.P("payload = json.loads(error_body)")
		p.Dedent()
		p.P("except ValueError:")
		p.Indent()
		p.P("payload = None")
		p.Dedent()
		p.P("if payload is not None:")
		p.Indent()
		p.P("raise ", p.MessageTypeName(errType), ".from_dict(payload) from None")
		p.Dedent()
		p.Dedent()
	}
}

func writeResponseBodyRuntime(p *Printer) {
	p.P("class UnexpectedStatusError(Exception):")
	p.Indent()
	p.P("def __init__(self, status: int, body: bytes, headers: dict[str, str]) -> None:")
	p.Indent()
	p.P(`super().__init__(f"unexpected status {status}: {body.decode('utf-8', 'replace')}")`)
	p.P("self.status = status")
	p.P("self.body = body")
	p.P("self.headers = headers")
	p.Dedent()
	p.Dedent()
	p.P()
	p.P("class StreamError(Exception):")
	p.Indent()
	p.P("def __init__(self, payload) -> None:")
	p.Indent()
	p.P("super().__init__(str(payload))")
	p.P("self.payload = payload")
	p.Dedent()
	p.Dedent()
	p.P()
	p.P("DEFAULT_MAX_RESPONSE_BODY_BYTES = 8 * 1024 * 1024")
	p.P("DEFAULT_MAX_SSE_LINE_BYTES = 1024 * 1024")
	p.P()
	p.P("def _read_bounded(stream, limit: int) -> bytes:")
	p.Indent()
	p.P("limit = limit if limit > 0 else DEFAULT_MAX_RESPONSE_BODY_BYTES")
	p.P("data = stream.read(limit + 1)")
	p.P("if len(data) > limit: raise ValueError(\"response body exceeds configured limit\")")
	p.P("return data")
	p.Dedent()
	p.P()
}

func writeClientQueryParams(p *Printer, req *onkir.Message) {
	p.P("query = []")
	for _, field := range req.Fields {
		d, ok := field.Decorator("query")
		if !ok || field.Type == nil || field.Type.Kind != onkir.KindScalar {
			continue
		}
		queryName, _ := d.Value()
		if queryName == "" {
			queryName = field.Name
		}
		p.P("if req.", field.Name, " is not None:")
		p.Indent()
		if field.Repeated {
			p.P("for value in req.", field.Name, ":")
			p.Indent()
			p.P(fmt.Sprintf("query.append((%q, %s))", queryName, pyQueryValueExpr(field.Type.Scalar, "value")))
			p.Dedent()
		} else {
			p.P(fmt.Sprintf("query.append((%q, %s))", queryName, pyQueryValueExpr(field.Type.Scalar, "req."+field.Name)))
		}
		p.Dedent()
	}
	p.P("if query:")
	p.Indent()
	p.P(`path += "?" + urllib.parse.urlencode(query, doseq=True)`)
	p.Dedent()
}

func writePyPathParams(p *Printer, route string, req *onkir.Message) {
	for _, paramName := range onkir.PathParamNames(route) {
		field := onkir.FindField(req, paramName)
		if field == nil {
			continue
		}
		p.P(fmt.Sprintf(
			"path = path.replace(%q, urllib.parse.quote(%s, safe=\"\"))",
			"{"+paramName+"}", pyQueryValueExpr(field.Type.Scalar, "req."+field.Name),
		))
	}
}

func pyQueryValueExpr(kind onkir.ScalarKind, expr string) string {
	if kind == onkir.ScalarBool {
		return fmt.Sprintf(`("true" if %s else "false")`, expr)
	}
	return "str(" + expr + ")"
}
