package genpy

import (
	"fmt"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

func fileHasStreamMethods(file *onkir.File) bool {
	for _, service := range file.Services {
		for _, method := range service.Methods {
			if method.IsStream() {
				return true
			}
		}
	}
	return false
}

// GenerateClient generates client.py treating every message/enum type as
// local. Use GenerateClientWithResolver for a multi-package project where
// some referenced types live in a different generated module.
func GenerateClient(file *onkir.File, typesModule string) []byte {
	return GenerateClientWithResolver(file, typesModule, nil)
}

func GenerateClientWithResolver(file *onkir.File, typesModule string, resolver PackageResolver) []byte {
	if len(file.Services) == 0 {
		return nil
	}

	p := newPrinter(resolver)
	p.P("# Code generated by onek. DO NOT EDIT.")
	p.P("from __future__ import annotations")
	p.P()
	p.P("import json")
	p.P("import urllib.error")
	p.P("import urllib.parse")
	p.P("import urllib.request")
	if fileHasStreamMethods(file) {
		p.P("from typing import Iterator")
	}
	p.P()
	if names := localReferencedTypeNames(file, resolver); len(names) > 0 {
		p.P("from ", typesModule, " import ", strings.Join(names, ", "))
	}
	for _, ref := range collectServiceExternalRefs(file, resolver) {
		p.P("import ", ref.ModulePath, " as ", ref.Alias)
	}
	p.P()

	writeResponseBodyRuntime(p)

	for _, s := range file.Services {
		writeClientClass(p, s)
	}

	return p.Bytes()
}

// localReferencedTypeNames returns the request/response/error type names that
// belong to this same generated module - the ones the caller should import
// via `from {typesModule} import ...`. Types resolved to a different module
// get their own qualified import instead (see collectServiceExternalRefs).
func localReferencedTypeNames(file *onkir.File, resolver PackageResolver) []string {
	seen := map[string]bool{}
	var names []string
	add := func(m *onkir.Message) {
		if resolver != nil {
			if _, ok := resolver.ResolveMessage(m); ok {
				return
			}
		}
		if !seen[m.Name] {
			seen[m.Name] = true
			names = append(names, m.Name)
		}
	}
	for _, s := range file.Services {
		for _, m := range s.Methods {
			add(m.Request)
			add(m.Response)
			for _, errType := range m.ErrorTypes {
				add(errType)
			}
		}
	}
	return names
}

func writeClientClass(p *Printer, s *onkir.Service) {
	p.P("class ", s.Name, "Client:")
	p.Indent()
	p.P("def __init__(self, base_url: str, headers: dict | None = None, max_response_body_bytes: int = DEFAULT_MAX_RESPONSE_BODY_BYTES, max_sse_line_bytes: int = DEFAULT_MAX_SSE_LINE_BYTES) -> None:")
	p.Indent()
	p.P("self.base_url = base_url")
	p.P("self.headers = headers or {}")
	p.P("self.max_response_body_bytes = max_response_body_bytes if max_response_body_bytes > 0 else DEFAULT_MAX_RESPONSE_BODY_BYTES")
	p.P("self.max_sse_line_bytes = max_sse_line_bytes if max_sse_line_bytes > 0 else DEFAULT_MAX_SSE_LINE_BYTES")
	p.Dedent()
	p.Blank()

	for _, m := range s.Methods {
		if m.IsStream() {
			writeSSEClientMethod(p, s, m)
		} else {
			writeClientMethod(p, s, m)
		}
	}
	p.Dedent()
	p.Blank()
}

func writeSSEClientMethod(p *Printer, s *onkir.Service, m *onkir.Method) {
	verb, _ := m.Verb()
	path, _ := m.Path()
	fullPath := s.BasePath + path
	p.P("def ", SnakeCase(m.Name), "(self, req: ", p.MessageTypeName(m.Request), ") -> Iterator[", p.MessageTypeName(m.Response), "]:")
	p.Indent()
	p.P("if hasattr(req, \"validate\"): req.validate()")
	p.P(fmt.Sprintf("path = %q", fullPath))
	for _, paramName := range pathParamNames(path) {
		field := findField(m.Request, paramName)
		if field != nil {
			p.P(fmt.Sprintf("path = path.replace(%q, urllib.parse.quote(str(req.%s), safe=\"\"))", "{"+paramName+"}", field.Name))
		}
	}
	writeClientQueryParams(p, m.Request)
	p.P(fmt.Sprintf("request = urllib.request.Request(self.base_url + path, method=%q)", strings.ToUpper(verb)))
	p.P(`request.add_header("Accept", "text/event-stream")`)
	p.P("for k, v in self.headers.items():")
	p.Indent()
	p.P("request.add_header(k, v)")
	p.Dedent()
	p.P("try:")
	p.Indent()
	p.P("with urllib.request.urlopen(request) as resp:")
	p.Indent()
	p.P("event = \"\"")
	p.P("while True:")
	p.Indent()
	p.P("raw_line = resp.readline(self.max_sse_line_bytes + 1)")
	p.P("if not raw_line: break")
	p.P("if len(raw_line) > self.max_sse_line_bytes: raise ValueError(\"SSE line exceeds configured limit\")")
	p.P("line = raw_line.decode(\"utf-8\").rstrip(\"\\r\\n\")")
	p.P("if line.startswith(\"event: \"):")
	p.Indent()
	p.P("event = line[7:]")
	p.P("continue")
	p.Dedent()
	p.P("if not line.startswith(\"data: \"):")
	p.Indent()
	p.P("continue")
	p.Dedent()
	p.P("payload = json.loads(line[6:])")
	p.P("if event == \"error\":")
	p.Indent()
	p.P("raise Exception(str(payload))")
	p.Dedent()
	p.P("yield ", p.MessageTypeName(m.Response), ".from_dict(payload)")
	p.P("event = \"\"")
	p.Dedent()
	p.Dedent()
	p.Dedent()
	p.P("except urllib.error.HTTPError as e:")
	p.Indent()
	p.P("error_body = _read_bounded(e, self.max_response_body_bytes)")
	for _, errType := range m.ErrorTypes {
		status := 500
		if code, ok := errType.StatusCode(); ok {
			status = code
		}
		p.P(fmt.Sprintf("if e.code == %d:", status))
		p.Indent()
		p.P("raise ", p.MessageTypeName(errType), ".from_dict(json.loads(error_body)) from None")
		p.Dedent()
	}
	p.P(`raise Exception(f"unexpected status {e.code}: {error_body.decode()}") from None`)
	p.Dedent()
	p.Dedent()
	p.Blank()
}

func writeClientMethod(p *Printer, s *onkir.Service, m *onkir.Method) {
	verb, _ := m.Verb()
	path, _ := m.Path()
	fullPath := s.BasePath + path
	bodyBearing := isBodyBearingVerb(verb)

	p.P("def ", SnakeCase(m.Name), "(self, req: ", p.MessageTypeName(m.Request),
		") -> ", p.MessageTypeName(m.Response), ":")
	p.Indent()
	p.P("if hasattr(req, \"validate\"): req.validate()")

	p.P(fmt.Sprintf("path = %q", fullPath))
	for _, paramName := range pathParamNames(path) {
		field := findField(m.Request, paramName)
		if field == nil {
			continue
		}
		valueExpr := pyQueryValueExpr(field.Type.Scalar, "req."+field.Name)
		p.P(fmt.Sprintf(
			"path = path.replace(%q, urllib.parse.quote(%s, safe=\"\"))",
			"{"+paramName+"}", valueExpr,
		))
	}

	if !bodyBearing {
		writeClientQueryParams(p, m.Request)
	}

	if bodyBearing {
		if bodyField, ok := m.BodyField(); ok {
			if field := findField(m.Request, bodyField); field != nil {
				p.P("body = json.dumps(", p.bodyValueExpr(field, "req."+field.Name), ").encode(\"utf-8\")")
			} else {
				p.P("body = json.dumps(req.to_dict()[", fmt.Sprintf("%q", bodyField), "]).encode(\"utf-8\")")
			}
		} else {
			p.P("body = json.dumps(req.to_dict()).encode(\"utf-8\")")
		}
		p.P(fmt.Sprintf(
			"request = urllib.request.Request(self.base_url + path, data=body, method=%q)",
			strings.ToUpper(verb),
		))
		p.P(`request.add_header("Content-Type", "application/json")`)
	} else {
		p.P(fmt.Sprintf("request = urllib.request.Request(self.base_url + path, method=%q)", strings.ToUpper(verb)))
	}
	p.P("for k, v in self.headers.items():")
	p.Indent()
	p.P("request.add_header(k, v)")
	p.Dedent()
	p.Blank()

	p.P("try:")
	p.Indent()
	p.P("with urllib.request.urlopen(request) as resp:")
	p.Indent()
	p.P("return ", p.MessageTypeName(m.Response), ".from_dict(json.loads(_read_bounded(resp, self.max_response_body_bytes)))")
	p.Dedent()
	p.Dedent()
	p.P("except urllib.error.HTTPError as e:")
	p.Indent()
	p.P("error_body = _read_bounded(e, self.max_response_body_bytes)")
	for _, errType := range m.ErrorTypes {
		status := 500
		if code, ok := errType.StatusCode(); ok {
			status = code
		}
		p.P(fmt.Sprintf("if e.code == %d:", status))
		p.Indent()
		p.P("raise ", p.MessageTypeName(errType), ".from_dict(json.loads(error_body)) from None")
		p.Dedent()
	}
	p.P(`raise Exception(f"unexpected status {e.code}: {error_body.decode()}") from None`)
	p.Dedent()
	p.Dedent()
	p.Blank()
}

func writeResponseBodyRuntime(p *Printer) {
	p.P("DEFAULT_MAX_RESPONSE_BODY_BYTES = 8 * 1024 * 1024")
	p.P("DEFAULT_MAX_SSE_LINE_BYTES = 1024 * 1024")
	p.P()
	p.P("def _read_bounded(stream, limit: int) -> bytes:")
	p.Indent()
	p.P("limit = limit if limit > 0 else DEFAULT_MAX_RESPONSE_BODY_BYTES")
	p.P("data = stream.read(limit + 1)")
	p.P("if len(data) > limit: raise ValueError(\"response body exceeds configured limit\")")
	p.P("return data")
	p.Dedent()
	p.P()
}

func findField(msg *onkir.Message, name string) *onkir.Field {
	for _, f := range msg.Fields {
		if f.Name == name {
			return f
		}
	}
	return nil
}

func pathParamNames(path string) []string {
	var names []string
	start := -1
	for i, c := range path {
		if c == '{' {
			start = i + 1
		} else if c == '}' && start >= 0 {
			names = append(names, path[start:i])
			start = -1
		}
	}
	return names
}

func isBodyBearingVerb(verb string) bool {
	return verb == "post" || verb == "put" || verb == "patch" || verb == "query"
}

func writeClientQueryParams(p *Printer, req *onkir.Message) {
	p.P("query = []")
	for _, field := range req.Fields {
		d, ok := field.Decorator("query")
		if !ok || field.Type == nil || field.Type.Kind != onkir.KindScalar {
			continue
		}
		queryName, _ := d.Value()
		if queryName == "" {
			queryName = field.Name
		}
		p.P("if req.", field.Name, " is not None:")
		p.Indent()
		if field.Repeated {
			p.P("for value in req.", field.Name, ":")
			p.Indent()
			p.P(fmt.Sprintf("query.append((%q, %s))", queryName, pyQueryValueExpr(field.Type.Scalar, "value")))
			p.Dedent()
		} else {
			p.P(fmt.Sprintf("query.append((%q, %s))", queryName, pyQueryValueExpr(field.Type.Scalar, "req."+field.Name)))
		}
		p.Dedent()
	}
	p.P("if query:")
	p.Indent()
	p.P(`path += "?" + urllib.parse.urlencode(query, doseq=True)`)
	p.Dedent()
}

func pyQueryValueExpr(kind onkir.ScalarKind, expr string) string {
	if kind == onkir.ScalarBool {
		return fmt.Sprintf(`("true" if %s else "false")`, expr)
	}
	return "str(" + expr + ")"
}
