package gengo

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

var pathParamPattern = regexp.MustCompile(`\{(\w+)\}`)

func pathParamNames(path string) []string {
	var names []string
	for _, m := range pathParamPattern.FindAllStringSubmatch(path, -1) {
		names = append(names, m[1])
	}
	return names
}

func findField(msg *onkir.Message, name string) *onkir.Field {
	for _, f := range msg.Fields {
		if f.Name == name {
			return f
		}
	}
	return nil
}

func scalarParseCall(kind onkir.ScalarKind, strExpr string) (string, bool) {
	switch kind {
	case onkir.ScalarInt32:
		return fmt.Sprintf("parseInt32(%s)", strExpr), true
	case onkir.ScalarInt64:
		return fmt.Sprintf("parseInt64(%s)", strExpr), true
	case onkir.ScalarUint32:
		return fmt.Sprintf("parseUint32(%s)", strExpr), true
	case onkir.ScalarUint64:
		return fmt.Sprintf("parseUint64(%s)", strExpr), true
	case onkir.ScalarFloat32:
		return fmt.Sprintf("parseFloat32(%s)", strExpr), true
	case onkir.ScalarFloat64:
		return fmt.Sprintf("parseFloat64(%s)", strExpr), true
	case onkir.ScalarBool:
		return fmt.Sprintf("parseBool(%s)", strExpr), true
	case onkir.ScalarBytes, onkir.ScalarTimestamp:
		return "", false
	default:
		return "", false
	}
}

// GenerateServer generates server.gen.go treating every message/enum type as
// local. Use GenerateServerWithResolver for a multi-package project where some
// referenced types live in a different generated package.
func GenerateServer(file *onkir.File) ([]byte, error) {
	return GenerateServerWithResolver(file, nil)
}

func GenerateServerWithResolver(file *onkir.File, resolver PackageResolver) ([]byte, error) {
	if len(file.Services) == 0 {
		return nil, nil
	}

	hasStream := fileHasStreamMethods(file)
	externalRefs := collectServiceExternalRefs(file, resolver)

	p := newPrinter(resolver)
	p.P("// Code generated by onek. DO NOT EDIT.")
	p.P("package ", GoPackageName(file))
	p.P()
	p.P("import (")
	p.P(`"crypto/rand"`)
	p.P(`"context"`)
	p.P(`"encoding/hex"`)
	p.P(`"encoding/json"`)
	p.P(`"fmt"`)
	p.P(`"net/http"`)
	p.P(`"regexp"`)
	p.P(`"strconv"`)
	p.P(`"time"`)
	for _, ref := range externalRefs {
		p.P(ref.Alias, " ", fmt.Sprintf("%q", ref.ImportPath))
	}
	p.P(")")
	p.P()

	writeRuntimeHelpers(p)
	writeServerOptions(p)
	if hasStream {
		writeSSEServerRuntime(p)
	}

	for _, s := range file.Services {
		writeServiceInterface(p, s)
		writeRegisterFunc(p, s)
	}

	return p.Format()
}

// writeServerOptions emits runtime hooks shared by every generated server.
func writeServerOptions(p *Printer) {
	p.P(`// RequestMetadata identifies the generated route handling a request.`)
	p.P(`type RequestMetadata struct {`)
	p.P(`Service string`)
	p.P(`Method string`)
	p.P(`HTTPMethod string`)
	p.P(`Route string`)
	p.P(`AuthSchemes []string`)
	p.P(`}`)
	p.P()
	p.P(`type requestMetadataContextKey struct{}`)
	p.P(`type requestIDContextKey struct{}`)
	p.P()
	p.P(`func RequestMetadataFromContext(ctx context.Context) (RequestMetadata, bool) {`)
	p.P(`metadata, ok := ctx.Value(requestMetadataContextKey{}).(RequestMetadata)`)
	p.P(`return metadata, ok`)
	p.P(`}`)
	p.P()
	p.P(`func RequestIDFromContext(ctx context.Context) (string, bool) {`)
	p.P(`requestID, ok := ctx.Value(requestIDContextKey{}).(string)`)
	p.P(`return requestID, ok && requestID != ""`)
	p.P(`}`)
	p.P()
	p.P(`type Middleware func(http.Handler) http.Handler`)
	p.P(`type RequestIDGenerator func() string`)
	p.P(`type Authorizer func(context.Context, RequestMetadata, *http.Request) error`)
	p.P(`type RequestResult struct { StatusCode int; Duration time.Duration }`)
	p.P(`type RequestObserver interface {`)
	p.P(`RequestStarted(context.Context, RequestMetadata) context.Context`)
	p.P(`RequestFinished(context.Context, RequestMetadata, RequestResult)`)
	p.P(`}`)
	p.P()
	p.P(`type ServerOption func(*serverOptions)`)
	p.P()
	p.P(`type serverOptions struct {`)
	p.P(`mux *http.ServeMux`)
	p.P(`middlewares []Middleware`)
	p.P(`requestIDHeader string`)
	p.P(`requestIDGenerator RequestIDGenerator`)
	p.P(`authorizer Authorizer`)
	p.P(`observer RequestObserver`)
	p.P(`}`)
	p.P()
	p.P(`// WithMux supports the options-first registration form.`)
	p.P(`func WithMux(mux *http.ServeMux) ServerOption { return func(o *serverOptions) { o.mux = mux } }`)
	p.P()
	p.P(`func WithMiddleware(middleware ...Middleware) ServerOption {`)
	p.P(`return func(o *serverOptions) { o.middlewares = append(o.middlewares, middleware...) }`)
	p.P(`}`)
	p.P()
	p.P(`func WithRequestID(headerName string) ServerOption { return WithRequestIDGenerator(headerName, defaultRequestIDGenerator) }`)
	p.P(`func WithRequestIDGenerator(headerName string, generate RequestIDGenerator) ServerOption {`)
	p.P(`return func(o *serverOptions) {`)
	p.P(`if headerName == "" { headerName = "X-Request-ID" }`)
	p.P(`o.requestIDHeader, o.requestIDGenerator = headerName, generate`)
	p.P(`}`)
	p.P(`}`)
	p.P()
	p.P(`func WithAuthorizer(authorizer Authorizer) ServerOption { return func(o *serverOptions) { o.authorizer = authorizer } }`)
	p.P(`func WithRequestObserver(observer RequestObserver) ServerOption { return func(o *serverOptions) { o.observer = observer } }`)
	p.P()
	p.P(`func defaultRequestIDGenerator() string {`)
	p.P(`var value [16]byte`)
	p.P(`if _, err := rand.Read(value[:]); err != nil { return "" }`)
	p.P(`return hex.EncodeToString(value[:])`)
	p.P(`}`)
	p.P()
	p.P(`func (o serverOptions) wrapHandler(handler http.Handler, metadata RequestMetadata) http.Handler {`)
	p.P(`for i := len(o.middlewares)-1; i >= 0; i-- { if o.middlewares[i] != nil { handler = o.middlewares[i](handler) } }`)
	p.P(`return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {`)
	p.P(`ctx := context.WithValue(r.Context(), requestMetadataContextKey{}, metadata)`)
	p.P(`if o.requestIDHeader != "" {`)
	p.P(`requestID := r.Header.Get(o.requestIDHeader)`)
	p.P(`if requestID == "" && o.requestIDGenerator != nil { requestID = o.requestIDGenerator() }`)
	p.P(`if requestID != "" { w.Header().Set(o.requestIDHeader, requestID); ctx = context.WithValue(ctx, requestIDContextKey{}, requestID) }`)
	p.P(`}`)
	p.P(`if o.authorizer != nil {`)
	p.P(`if err := o.authorizer(ctx, metadata, r); err != nil { writeJSONError(w, http.StatusUnauthorized, err.Error()); return }`)
	p.P(`}`)
	p.P(`if o.observer == nil { handler.ServeHTTP(w, r.WithContext(ctx)); return }`)
	p.P(`started := time.Now()`)
	p.P(`ctx = o.observer.RequestStarted(ctx, metadata)`)
	p.P(`rw := &statusResponseWriter{ResponseWriter: w, statusCode: http.StatusOK}`)
	p.P(`defer func() { o.observer.RequestFinished(ctx, metadata, RequestResult{StatusCode: rw.statusCode, Duration: time.Since(started)}) }()`)
	p.P(`handler.ServeHTTP(rw, r.WithContext(ctx))`)
	p.P(`})`)
	p.P(`}`)
	p.P()
	p.P(`type statusResponseWriter struct { http.ResponseWriter; statusCode int }`)
	p.P(`func (w *statusResponseWriter) WriteHeader(statusCode int) { w.statusCode = statusCode; w.ResponseWriter.WriteHeader(statusCode) }`)
	p.P(`func (w *statusResponseWriter) Flush() { if flusher, ok := w.ResponseWriter.(http.Flusher); ok { flusher.Flush() } }`)
	p.P()
}

func writeRuntimeHelpers(p *Printer) {
	p.P(`func writeJSONError(w http.ResponseWriter, status int, message string) {`)
	p.P(`w.Header().Set("Content-Type", "application/json")`)
	p.P(`w.WriteHeader(status)`)
	p.P(`_ = json.NewEncoder(w).Encode(map[string]string{"message": message})`)
	p.P(`}`)
	p.P()
	p.P(`func parseInt32(s string) (int32, error) { v, err := strconv.ParseInt(s, 10, 32); return int32(v), err }`)
	p.P(`func parseInt64(s string) (int64, error) { return strconv.ParseInt(s, 10, 64) }`)
	p.P(`func parseUint32(s string) (uint32, error) { v, err := strconv.ParseUint(s, 10, 32); return uint32(v), err }`)
	p.P(`func parseUint64(s string) (uint64, error) { return strconv.ParseUint(s, 10, 64) }`)
	p.P(`func parseFloat32(s string) (float32, error) { v, err := strconv.ParseFloat(s, 32); return float32(v), err }`)
	p.P(`func parseFloat64(s string) (float64, error) { return strconv.ParseFloat(s, 64) }`)
	p.P(`func parseBool(s string) (bool, error) {`)
	p.P(`if s == "true" { return true, nil }`)
	p.P(`if s == "false" { return false, nil }`)
	p.P(`return false, fmt.Errorf("must be true or false")`)
	p.P(`}`)
	p.P()
	p.P(`func validHeaderFormat(value, format string) bool {`)
	p.P(`switch format {`)
	p.P(`case "uuid": return regexp.MustCompile(` + "`" + `^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$` + "`" + `).MatchString(value)`)
	p.P(`case "email": return regexp.MustCompile(` + "`" + `^[^@\s]+@[^@\s]+\.[^@\s]+$` + "`" + `).MatchString(value)`)
	p.P(`case "uri": return regexp.MustCompile(` + "`" + `^[a-zA-Z][a-zA-Z0-9+.-]*://[^\s]+$` + "`" + `).MatchString(value)`)
	p.P(`default: return true`)
	p.P(`}`)
	p.P(`}`)
	p.P()
}

func writeServiceInterface(p *Printer, s *onkir.Service) {
	p.P("type ", s.Name, "Server interface {")
	for _, m := range s.Methods {
		if m.IsStream() {
			p.P(PascalCase(m.Name), "(ctx context.Context, req *",
				p.MessageTypeName(m.Request), ", sender SSESender) error")
		} else {
			p.P(PascalCase(m.Name), "(ctx context.Context, req *", p.MessageTypeName(m.Request),
				") (*", p.MessageTypeName(m.Response), ", error)")
		}
	}
	p.P("}")
	p.P()
}

func writeRegisterFunc(p *Printer, s *onkir.Service) {
	p.P("func Register", s.Name, "Server(first any, rest ...any) error {")
	p.P("var o serverOptions")
	p.P("var srv ", s.Name, "Server")
	p.P("if mux, ok := first.(*http.ServeMux); ok {")
	p.P("o.mux = mux")
	p.P("if len(rest) == 0 { return fmt.Errorf(\"Register", s.Name, "Server: implementation is required\") }")
	p.P("var ok bool")
	p.P("srv, ok = rest[0].(", s.Name, "Server)")
	p.P("if !ok { return fmt.Errorf(\"Register", s.Name, "Server: invalid implementation\") }")
	p.P("rest = rest[1:]")
	p.P("} else {")
	p.P("var ok bool")
	p.P("srv, ok = first.(", s.Name, "Server)")
	p.P("if !ok { return fmt.Errorf(\"Register", s.Name, "Server: invalid implementation\") }")
	p.P("}")
	p.P("for _, value := range rest {")
	p.P("opt, ok := value.(ServerOption)")
	p.P("if !ok { return fmt.Errorf(\"Register", s.Name, "Server: options must be ServerOption values\") }")
	p.P("opt(&o)")
	p.P("}")
	p.P("if o.mux == nil { return fmt.Errorf(\"Register", s.Name, "Server: mux is required\") }")
	p.P("mux := o.mux")
	for _, m := range s.Methods {
		if m.IsStream() {
			writeSSERoute(p, s, m)
		} else {
			writeRoute(p, s, m)
		}
	}
	p.P("return nil")
	p.P("}")
	p.P()
}

func isBodyBearingVerb(verb string) bool {
	return verb == "post" || verb == "put" || verb == "patch" || verb == "query"
}

func writeBodyBinding(p *Printer, method *onkir.Method) {
	target := "req"
	if bodyField, ok := method.BodyField(); ok {
		if field := findField(method.Request, bodyField); field != nil {
			target = "&req." + PascalCase(field.Name)
		}
	}
	p.P("if r.Body != nil {")
	p.P("if err := json.NewDecoder(r.Body).Decode(", target, "); err != nil && err.Error() != \"EOF\" {")
	p.P(`writeJSONError(w, http.StatusBadRequest, "invalid request body: "+err.Error())`)
	p.P("return")
	p.P("}")
	p.P("}")
}

func writePathParamBinding(p *Printer, path string, req *onkir.Message) {
	for _, paramName := range pathParamNames(path) {
		field := findField(req, paramName)
		if field == nil || field.Type == nil || field.Type.Kind != onkir.KindScalar {
			continue
		}
		raw := fmt.Sprintf("r.PathValue(%q)", paramName)
		if field.Type.Scalar == onkir.ScalarString {
			writeBoundFieldAssignment(p, field, raw)
			continue
		}
		call, ok := scalarParseCall(field.Type.Scalar, raw)
		if !ok {
			continue
		}
		writeParsedFieldAssignment(p, field, call, "path parameter "+paramName)
	}
}

func writeQueryParamBinding(p *Printer, req *onkir.Message) {
	for _, field := range req.Fields {
		d, ok := field.Decorator("query")
		if !ok || field.Type == nil || field.Type.Kind != onkir.KindScalar {
			continue
		}
		queryName, _ := d.Value()
		if queryName == "" {
			queryName = field.Name
		}
		strExpr := fmt.Sprintf("r.URL.Query().Get(%q)", queryName)
		p.P("if ", strExpr, " != \"\" {")
		if field.Type.Scalar == onkir.ScalarString {
			writeBoundFieldAssignment(p, field, strExpr)
		} else {
			call, ok := scalarParseCall(field.Type.Scalar, strExpr)
			if ok {
				writeParsedFieldAssignment(p, field, call, "query parameter "+queryName)
			}
		}
		p.P("}")
	}
}

func writeBoundFieldAssignment(p *Printer, field *onkir.Field, expr string) {
	if field.Optional {
		varName := CamelCase(field.Name) + "Val"
		p.P(varName, " := ", expr)
		p.P("req.", PascalCase(field.Name), " = &", varName)
		return
	}
	p.P("req.", PascalCase(field.Name), " = ", expr)
}

func writeParsedFieldAssignment(p *Printer, field *onkir.Field, call, location string) {
	varName := "parsed" + PascalCase(field.Name)
	p.P(varName, ", err := ", call)
	p.P("if err != nil {")
	p.P(`writeJSONError(w, http.StatusBadRequest, "invalid `, location, `: "+err.Error())`)
	p.P("return")
	p.P("}")
	if field.Optional {
		p.P("req.", PascalCase(field.Name), " = &", varName)
		return
	}
	p.P("req.", PascalCase(field.Name), " = ", varName)
}

func writeValidateCall(p *Printer) {
	p.P("if v, ok := any(req).(interface{ Validate() error }); ok {")
	p.P("if err := v.Validate(); err != nil {")
	p.P(`writeJSONError(w, http.StatusBadRequest, err.Error())`)
	p.P("return")
	p.P("}")
	p.P("}")
}

func writeRoute(p *Printer, s *onkir.Service, m *onkir.Method) {
	verb, _ := m.Verb()
	path, _ := m.Path()
	fullPath := s.BasePath + path
	bodyBearing := isBodyBearingVerb(verb)

	p.P(`mux.Handle("`, strings.ToUpper(verb), " ", fullPath, `", o.wrapHandler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {`)
	p.P("req := new(", p.MessageTypeName(m.Request), ")")

	if bodyBearing {
		writeBodyBinding(p, m)
	}
	writePathParamBinding(p, path, m.Request)
	if !bodyBearing {
		writeQueryParamBinding(p, m.Request)
	}

	for _, h := range m.Service.Headers {
		writeHeaderCheck(p, h)
	}
	for _, h := range m.Headers {
		writeHeaderCheck(p, h)
	}

	writeValidateCall(p)

	p.P("resp, err := srv.", PascalCase(m.Name), "(r.Context(), req)")
	p.P("if err != nil {")
	writeErrorHandling(p, m)
	p.P("return")
	p.P("}")
	p.P(`w.Header().Set("Content-Type", "application/json")`)
	p.P("_ = json.NewEncoder(w).Encode(resp)")
	p.P("}), RequestMetadata{Service: ", fmt.Sprintf("%q", s.Name), ", Method: ", fmt.Sprintf("%q", m.Name), ", HTTPMethod: ", fmt.Sprintf("%q", strings.ToUpper(verb)), ", Route: ", fmt.Sprintf("%q", fullPath), ", AuthSchemes: ", authSchemesLiteral(s, m), "}))")
}

func authSchemesLiteral(s *onkir.Service, m *onkir.Method) string {
	var names []string
	for _, h := range append(append([]*onkir.Header{}, s.Headers...), m.Headers...) {
		if _, ok := h.AuthType(); !ok {
			continue
		}
		if name, ok := h.AuthSchemeName(); ok && name != "" {
			names = append(names, name)
			continue
		}
		name := regexp.MustCompile(`[^A-Za-z0-9_.-]+`).ReplaceAllString(h.Name, "")
		if name == "" {
			name = "Header"
		}
		names = append(names, name+"Auth")
	}
	if len(names) == 0 {
		return "nil"
	}
	quoted := make([]string, 0, len(names))
	for _, name := range names {
		quoted = append(quoted, fmt.Sprintf("%q", name))
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

func writeHeaderCheck(p *Printer, h *onkir.Header) {
	format, hasFormat := h.Format()
	if !h.Required() && !hasFormat {
		return
	}
	p.P("{")
	p.P(`value := r.Header.Get("`, h.Name, `")`)
	if h.Required() {
		p.P(`if value == "" {`)
		p.P(`writeJSONError(w, http.StatusBadRequest, "missing required header: `, h.Name, `")`)
		p.P("return")
		p.P("}")
	}
	if hasFormat {
		p.P(`if value != "" && !validHeaderFormat(value, `, fmt.Sprintf("%q", format), `) {`)
		p.P(`writeJSONError(w, http.StatusBadRequest, "invalid header `, h.Name, `: expected `, format, `")`)
		p.P("return")
		p.P("}")
	}
	p.P("}")
}

func writeErrorHandling(p *Printer, m *onkir.Method) {
	if len(m.ErrorTypes) == 0 {
		p.P(`writeJSONError(w, http.StatusInternalServerError, err.Error())`)
		return
	}
	p.P("switch e := err.(type) {")
	for _, errType := range m.ErrorTypes {
		status := 500
		if code, ok := errType.StatusCode(); ok {
			status = code
		}
		p.P("case *", p.MessageTypeName(errType), ":")
		p.P(`w.Header().Set("Content-Type", "application/json")`)
		p.P(fmt.Sprintf("w.WriteHeader(%d)", status))
		p.P("_ = json.NewEncoder(w).Encode(e)")
	}
	p.P("default:")
	p.P(`writeJSONError(w, http.StatusInternalServerError, err.Error())`)
	p.P("}")
}
