package gengo

import (
	_ "embed"
	"fmt"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

func scalarParseCall(kind onkir.ScalarKind, strExpr string) (string, bool) {
	switch kind {
	case onkir.ScalarInt32:
		return fmt.Sprintf("parseInt32(%s)", strExpr), true
	case onkir.ScalarInt64:
		return fmt.Sprintf("parseInt64(%s)", strExpr), true
	case onkir.ScalarUint32:
		return fmt.Sprintf("parseUint32(%s)", strExpr), true
	case onkir.ScalarUint64:
		return fmt.Sprintf("parseUint64(%s)", strExpr), true
	case onkir.ScalarFloat32:
		return fmt.Sprintf("parseFloat32(%s)", strExpr), true
	case onkir.ScalarFloat64:
		return fmt.Sprintf("parseFloat64(%s)", strExpr), true
	case onkir.ScalarBool:
		return fmt.Sprintf("parseBool(%s)", strExpr), true
	case onkir.ScalarBytes, onkir.ScalarTimestamp:
		return "", false
	default:
		return "", false
	}
}

// GenerateServer generates server.gen.go treating every message/enum type as
// local. Use GenerateServerWithResolver for a multi-package project where some
// referenced types live in a different generated package.
func GenerateServer(file *onkir.File) ([]byte, error) {
	return GenerateServerWithResolver(file, nil)
}

func GenerateServerWithResolver(file *onkir.File, resolver PackageResolver) ([]byte, error) {
	return GenerateServerWithOptions(file, resolver, Options{})
}

// Options tunes the generated Go.
type Options struct {
	// SharedRuntime, when set, makes the server import its core from one
	// shared package instead of carrying a copy.
	SharedRuntime *SharedRuntime
	// JSONContentType is the Content-Type the server writes on JSON
	// responses. It defaults to application/json.
	JSONContentType string
}

const defaultJSONContentType = "application/json"

func jsonContentTypeLiteral(contentType string) string {
	if contentType == "" {
		contentType = defaultJSONContentType
	}
	return strconv.Quote(contentType)
}

func GenerateServerWithOptions(file *onkir.File, resolver PackageResolver, opts Options) ([]byte, error) {
	if len(file.Services) == 0 {
		return nil, nil
	}

	hasStream := onkir.FileHasStreamMethods(file)
	hasWS := onkir.FileHasWSMethods(file)
	hasWSCorrelation := onkir.FileHasWSCorrelation(file)
	hasRequestBody := fileHasRequestBodyBinding(file)
	externalRefs := collectServiceExternalRefs(file, resolver)

	p := newPrinter(resolver)
	if principal := filePrincipal(file); principal != nil {
		p.principalType = p.MessageTypeName(principal)
	}
	p.P("// Code generated by onek. DO NOT EDIT.")
	p.P("package ", GoPackageName(file))
	p.P()
	p.P("import (")
	p.P(`"bytes"`)
	p.P(`"crypto/rand"`)
	p.P(`"context"`)
	p.P(`"encoding/hex"`)
	p.P(`"encoding/json"`)
	p.P(`"errors"`)
	p.P(`"fmt"`)
	if hasRequestBody || hasWS {
		p.P(`"io"`)
	}
	p.P(`"math"`)
	p.P(`"net/http"`)
	p.P(`"regexp"`)
	p.P(`"strconv"`)
	p.P(`"strings"`)
	p.P(`"time"`)
	if hasWS {
		p.P(`"net"`)
	}
	if hasWS || hasStream {
		p.P(`"sync"`)
	}
	if hasWS {
		p.P(`"github.com/coder/websocket"`)
	}
	for _, ref := range externalRefs {
		p.P(ref.Alias, " ", fmt.Sprintf("%q", ref.ImportPath))
	}
	if opts.SharedRuntime != nil {
		p.P(opts.SharedRuntime.Package, " ", fmt.Sprintf("%q", opts.SharedRuntime.ImportPath))
	}
	p.P(")")
	p.P()

	writeRuntimeHelpers(p, opts.JSONContentType)
	writeHeaderFormatPatterns(p)
	writeServerOptions(p, hasWS, opts.SharedRuntime)
	if hasWS {
		writeWSOutType(p)
	}
	if hasWSCorrelation {
		writeWSPendingType(p, wsServerPendingType, wsServerPendingConstructor, wsServerClosedError)
	}
	if hasStream {
		writeSSEServerRuntime(p)
	}

	for _, s := range file.Services {
		for _, m := range s.Methods {
			if !m.IsWebSocket() {
				continue
			}
			if idField, ok := m.WSIDField(); ok {
				writeWSCorrelatedOutType(p, s, m, idField)
			}
		}
		writeServiceInterface(p, s)
		writeRegisterFunc(p, s)
	}

	out, err := p.Format()
	if err != nil {
		return nil, err
	}
	return pruneUnusedImports(out)
}

// fileHasRequestBodyBinding reports whether any route decodes a request body,
// which is what pulls io.EOF handling (and therefore the io import) into the
// generated server.
func fileHasRequestBodyBinding(file *onkir.File) bool {
	for _, service := range file.Services {
		for _, method := range service.Methods {
			if verb, ok := method.Verb(); ok && onkir.IsBodyBearingVerb(verb) {
				return true
			}
		}
	}
	return false
}

//go:embed runtime/server_core.go.tmpl
var serverCoreSource string

//go:embed runtime/server_ws_options.go.tmpl
var serverWSOptionsSource string

// withoutMarkedBlock returns source with the lines between a "//onek:name"
// marker and its "//onek:end" removed, or only the markers removed when keep
// is true.
func withoutMarkedBlock(source, name string, keep bool) string {
	lines := strings.Split(source, "\n")
	out := make([]string, 0, len(lines))
	skipping := false
	for _, line := range lines {
		switch strings.TrimSpace(line) {
		case "//onek:" + name:
			skipping = !keep
			continue
		case "//onek:end":
			skipping = false
			continue
		}
		if !skipping {
			out = append(out, line)
		}
	}
	return strings.Join(out, "\n")
}

func writeServerCore(p *Printer, hasWS bool) {
	p.P(withoutMarkedBlock(serverCoreSource, "ws", hasWS))
	if hasWS {
		p.P(serverWSOptionsSource)
	}
}

func writeWSServerHelpers(p *Printer) {
	p.P()
	p.P(`// wsCloseReason fits message into a close frame's 123-byte reason, cutting`)
	p.P(`// on a UTF-8 boundary; a longer reason would be replaced by a bare 1011.`)
	p.P(`func wsCloseReason(message string) string {`)
	p.P(`if len(message) <= 123 { return message }`)
	p.P(`cut := 123`)
	p.P(`for cut > 0 && message[cut]&0xC0 == 0x80 { cut-- }`)
	p.P(`return message[:cut]`)
	p.P(`}`)
	p.P()
	p.P(`func wsServerReadLimit(limit int64) int64 {`)
	p.P(`if limit == 0 { return `, defaultMaxWSFrameBytes, ` }`)
	p.P(`if limit < 0 { return -1 }`)
	p.P(`return limit`)
	p.P(`}`)
}

// writeServerOptions emits the server core (hooks, options, error writer,
// request wrapper) either inline or, with a shared runtime, as aliases of the
// shared package, then the pieces that depend on this package's own types.
func writeServerOptions(p *Printer, hasWS bool, shared *SharedRuntime) {
	if shared != nil {
		writeSharedRuntimeAliases(p, hasWS, shared)
	} else {
		writeServerCore(p, hasWS)
	}
	writePrincipalOption(p)
	if hasWS {
		writeWSServerHelpers(p)
	}
}

func writeRuntimeHelpers(p *Printer, contentType string) {
	p.P(`func writeJSON(w http.ResponseWriter, status int, value any) {`)
	p.P(`data, err := json.Marshal(value)`)
	p.P(`if err != nil {`)
	p.P(`writeJSONError(w, http.StatusInternalServerError, "internal server error")`)
	p.P(`return`)
	p.P(`}`)
	p.P(`w.Header().Set("Content-Type", `, jsonContentTypeLiteral(contentType), `)`)
	p.P(`w.WriteHeader(status)`)
	p.P(`_, _ = w.Write(append(data, '\n'))`)
	p.P(`}`)
	p.P()
	p.P(`func writeJSONError(w http.ResponseWriter, status int, message string) {`)
	p.P(`w.Header().Set("Content-Type", `, jsonContentTypeLiteral(contentType), `)`)
	p.P(`w.WriteHeader(status)`)
	p.P(`_ = json.NewEncoder(w).Encode(map[string]string{"message": message})`)
	p.P(`}`)
	p.P()
	p.P(`func requestBodyLimit(limit int64) int64 {`)
	p.P(`if limit <= 0 { return 8 << 20 }`)
	p.P(`return limit`)
	p.P(`}`)
	p.P()
	p.P(`func parseInt32(s string) (int32, error) { v, err := strconv.ParseInt(s, 10, 32); if err != nil { return 0, errors.New("must be a 32-bit integer") }; return int32(v), nil }`)
	p.P(`func parseInt64(s string) (int64, error) { v, err := strconv.ParseInt(s, 10, 64); if err != nil { return 0, errors.New("must be an integer") }; return v, nil }`)
	p.P(`func parseUint32(s string) (uint32, error) { v, err := strconv.ParseUint(s, 10, 32); if err != nil { return 0, errors.New("must be a non-negative 32-bit integer") }; return uint32(v), nil }`)
	p.P(`func parseUint64(s string) (uint64, error) { v, err := strconv.ParseUint(s, 10, 64); if err != nil { return 0, errors.New("must be a non-negative integer") }; return v, nil }`)
	p.P(`func parseFloat32(s string) (float32, error) { v, err := strconv.ParseFloat(s, 32); if err != nil || math.IsNaN(v) || math.IsInf(v, 0) { return 0, fmt.Errorf("must be a finite number") }; return float32(v), nil }`)
	p.P(`func parseFloat64(s string) (float64, error) { v, err := strconv.ParseFloat(s, 64); if err != nil || math.IsNaN(v) || math.IsInf(v, 0) { return 0, fmt.Errorf("must be a finite number") }; return v, nil }`)
	p.P(`func parseBool(s string) (bool, error) {`)
	p.P(`if s == "true" { return true, nil }`)
	p.P(`if s == "false" { return false, nil }`)
	p.P(`return false, fmt.Errorf("must be true or false")`)
	p.P(`}`)
	p.P()
	p.P(`func hasAuthScheme(value, scheme string) bool {`)
	p.P(`if len(value) <= len(scheme)+1 || value[len(scheme)] != ' ' { return false }`)
	p.P(`for i := 0; i < len(scheme); i++ {`)
	p.P(`a, b := value[i], scheme[i]`)
	p.P(`if a >= 'A' && a <= 'Z' { a += 'a' - 'A' }`)
	p.P(`if b >= 'A' && b <= 'Z' { b += 'a' - 'A' }`)
	p.P(`if a != b { return false }`)
	p.P(`}`)
	p.P(`return true`)
	p.P(`}`)
	p.P()
	p.P(`func validHeaderFormat(value, format string) bool {`)
	p.P(`switch format {`)
	p.P(`case "uuid": return validHeaderUUID.MatchString(value)`)
	p.P(`case "email": return validHeaderEmail.MatchString(value)`)
	p.P(`case "uri": return validHeaderURI.MatchString(value)`)
	p.P(`default: return true`)
	p.P(`}`)
	p.P(`}`)
	p.P()
}

// writeHeaderFormatPatterns emits the package-level regexps backing
// validHeaderFormat. Compiling them once instead of per request avoids a
// regexp.MustCompile on every header validation call.
func writeHeaderFormatPatterns(p *Printer) {
	uuid := `^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`
	email := `^[^@\s]+@[^@\s]+\.[^@\s]+$`
	uri := `^[a-zA-Z][a-zA-Z0-9+.-]*://[^\s]+$`
	p.P(`var (`)
	p.P("validHeaderUUID = regexp.MustCompile(`" + uuid + "`)")
	p.P("validHeaderEmail = regexp.MustCompile(`" + email + "`)")
	p.P("validHeaderURI = regexp.MustCompile(`" + uri + "`)")
	p.P(`)`)
	p.P()
}

func writeServiceInterface(p *Printer, s *onkir.Service) {
	writeDoc(p, s.Doc)
	p.P("type ", s.Name, "Server interface {")
	for _, m := range s.Methods {
		writeDoc(p, deprecatedDoc(m.Doc, m.Deprecated))
		switch {
		case m.IsWebSocket():
			outType := "WSOut[" + p.MessageTypeName(m.Response) + "]"
			if _, ok := m.WSIDField(); ok {
				outType = "*" + wsOutName(s, m)
			}
			p.P(PascalCase(m.Name), "(ctx context.Context, req *",
				p.MessageTypeName(m.Request), ", out ", outType, ") error")
		case m.IsStream():
			p.P(PascalCase(m.Name), "(ctx context.Context, req *",
				p.MessageTypeName(m.Request), ", sender SSESender) error")
		default:
			p.P(PascalCase(m.Name), "(ctx context.Context, req *", p.MessageTypeName(m.Request),
				") (*", p.MessageTypeName(m.Response), ", error)")
		}
	}
	p.P("}")
	p.P()
}

func writeRegisterFunc(p *Printer, s *onkir.Service) {
	p.P("func Register", s.Name, "Server(first any, rest ...any) error {")
	p.P("var o ServerOptions")
	p.P("var srv ", s.Name, "Server")
	p.P("if mux, ok := first.(*http.ServeMux); ok {")
	p.P("o.Mux = mux")
	p.P("if len(rest) == 0 { return fmt.Errorf(\"Register", s.Name, "Server: implementation is required\") }")
	p.P("var ok bool")
	p.P("srv, ok = rest[0].(", s.Name, "Server)")
	p.P("if !ok { return fmt.Errorf(\"Register", s.Name, "Server: invalid implementation\") }")
	p.P("rest = rest[1:]")
	p.P("} else {")
	p.P("var ok bool")
	p.P("srv, ok = first.(", s.Name, "Server)")
	p.P("if !ok { return fmt.Errorf(\"Register", s.Name, "Server: invalid implementation\") }")
	p.P("}")
	p.P("for _, value := range rest {")
	p.P("opt, ok := value.(ServerOption)")
	p.P("if !ok { return fmt.Errorf(\"Register", s.Name, "Server: options must be ServerOption values\") }")
	p.P("opt(&o)")
	p.P("}")
	p.P("if o.Mux == nil { return fmt.Errorf(\"Register", s.Name, "Server: mux is required\") }")
	p.P("mux := o.Mux")
	for _, m := range s.Methods {
		switch {
		case m.IsWebSocket():
			writeWSRoute(p, s, m)
		case m.IsStream():
			writeSSERoute(p, s, m)
		default:
			writeRoute(p, s, m)
		}
	}
	p.P("return nil")
	p.P("}")
	p.P()
}

func writeBodyBinding(p *Printer, method *onkir.Method) {
	target := "req"
	var bodyField *onkir.Field
	if bodyName, ok := method.BodyField(); ok {
		if field := onkir.FindField(method.Request, bodyName); field != nil {
			target = "&req." + GoFieldName(field)
			bodyField = field
		}
	}
	p.P("if r.Body != nil {")
	if limit, ok := method.MaxBodyBytes(); ok {
		p.P("r.Body = http.MaxBytesReader(w, r.Body, ", limit, ")")
	} else {
		p.P("r.Body = http.MaxBytesReader(w, r.Body, requestBodyLimit(o.MaxRequestBodyBytes))")
	}
	if bodyField != nil && bodyFieldNeedsCustomJSON(bodyField) {
		p.P("var bodyValue json.RawMessage")
		p.P("if err := json.NewDecoder(r.Body).Decode(&bodyValue); err != nil && !errors.Is(err, io.EOF) {")
		p.P(`o.WriteBodyError(w, r, err)`)
		p.P("return")
		p.P("}")
		p.P("var bodyObject struct { Value json.RawMessage `json:\"", bodyField.Name, "\"` }")
		p.P("bodyObject.Value = bodyValue")
		p.P("bodyData, err := json.Marshal(bodyObject)")
		p.P("if err != nil {")
		p.P(`o.Fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "invalid_request_body", Message: "invalid request body", Cause: err})`)
		p.P("return")
		p.P("}")
		p.P("if err := json.Unmarshal(bodyData, req); err != nil {")
	} else {
		p.P("if err := json.NewDecoder(r.Body).Decode(", target, "); err != nil && !errors.Is(err, io.EOF) {")
		p.P(`o.WriteBodyError(w, r, err)`)
		p.P("return")
		p.P("}")
		p.P("}")
		return
	}
	p.P(`o.Fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "invalid_request_body", Message: "invalid request body", Cause: err})`)
	p.P("return")
	p.P("}")
	p.P("}")
}

func writePathParamBinding(p *Printer, path string, req *onkir.Message) {
	for _, paramName := range onkir.PathParamNames(path) {
		field := onkir.FindField(req, paramName)
		if field == nil || field.Type == nil || field.Type.Kind != onkir.KindScalar {
			continue
		}
		raw := fmt.Sprintf("r.PathValue(%q)", paramName)
		if field.Type.Scalar == onkir.ScalarString {
			writeBoundFieldAssignment(p, field, raw)
			continue
		}
		call, ok := scalarParseCall(field.Type.Scalar, raw)
		if !ok {
			continue
		}
		writeParsedFieldAssignment(p, field, call, "path parameter "+paramName)
	}
}

func writeQueryParamBinding(p *Printer, req *onkir.Message) {
	for _, field := range req.Fields {
		d, ok := field.Decorator("query")
		if !ok || field.Type == nil || field.Type.Kind != onkir.KindScalar {
			continue
		}
		queryName, _ := d.Value()
		if queryName == "" {
			queryName = field.Name
		}
		if field.Repeated {
			valuesExpr := fmt.Sprintf("r.URL.Query()[%q]", queryName)
			p.P("if values := ", valuesExpr, "; len(values) > 0 {")
			p.P("req.", GoFieldName(field), " = make([]", p.GoFieldType(field.Type), ", 0, len(values))")
			p.P("for _, value := range values {")
			if field.Type.Scalar == onkir.ScalarString {
				p.P("req.", GoFieldName(field), " = append(req.", GoFieldName(field), ", value)")
			} else if call, ok := scalarParseCall(field.Type.Scalar, "value"); ok {
				parsed := "parsed" + GoFieldName(field)
				p.P(parsed, ", err := ", call)
				p.P("if err != nil {")
				p.P(`o.Fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "invalid_query_parameter", Field: `, fmt.Sprintf("%q", queryName), `, Message: "invalid query parameter `, queryName, `: "+err.Error(), Cause: err})`)
				p.P("return")
				p.P("}")
				p.P("req.", GoFieldName(field), " = append(req.", GoFieldName(field), ", ", parsed, ")")
			}
			p.P("}")
			p.P("}")
			continue
		}
		p.P("if values := r.URL.Query()[", fmt.Sprintf("%q", queryName), "]; len(values) > 0 {")
		p.P("value := values[0]")
		if field.Type.Scalar == onkir.ScalarString {
			writeBoundFieldAssignment(p, field, "value")
		} else {
			call, ok := scalarParseCall(field.Type.Scalar, "value")
			if ok {
				writeParsedFieldAssignment(p, field, call, "query parameter "+queryName)
			}
		}
		p.P("}")
	}
}

func writeBoundFieldAssignment(p *Printer, field *onkir.Field, expr string) {
	if field.Optional {
		varName := CamelCase(field.Name) + "Val"
		p.P(varName, " := ", expr)
		p.P("req.", GoFieldName(field), " = &", varName)
		return
	}
	p.P("req.", GoFieldName(field), " = ", expr)
}

func writeParsedFieldAssignment(p *Printer, field *onkir.Field, call, location string) {
	code, fieldName := "invalid_query_parameter", field.Name
	if strings.HasPrefix(location, "path parameter ") {
		code, fieldName = "invalid_path_parameter", strings.TrimPrefix(location, "path parameter ")
	} else if strings.HasPrefix(location, "query parameter ") {
		fieldName = strings.TrimPrefix(location, "query parameter ")
	}
	varName := "parsed" + GoFieldName(field)
	p.P(varName, ", err := ", call)
	p.P("if err != nil {")
	p.P(`o.Fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "`, code, `", Field: `, fmt.Sprintf("%q", fieldName), `, Message: "invalid `, location, `: "+err.Error(), Cause: err})`)
	p.P("return")
	p.P("}")
	if field.Optional {
		p.P("req.", GoFieldName(field), " = &", varName)
		return
	}
	p.P("req.", GoFieldName(field), " = ", varName)
}

func writeValidateCall(p *Printer) {
	p.P("if v, ok := any(req).(interface{ Validate() error }); ok {")
	p.P("if err := v.Validate(); err != nil {")
	p.P(`var list interface{ ViolationList() []string }`)
	p.P(`if errors.As(err, &list) {`)
	p.P(`o.Fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "validation_failed", Message: err.Error(), Violations: list.ViolationList(), Cause: err})`)
	p.P("return")
	p.P("}")
	p.P(`o.Fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "validation_failed", Message: err.Error(), Cause: err})`)
	p.P("return")
	p.P("}")
	p.P("}")
}

func writeRoute(p *Printer, s *onkir.Service, m *onkir.Method) {
	verb, _ := m.Verb()
	path, _ := m.Path()
	fullPath := s.BasePath + path
	bodyBearing := onkir.IsBodyBearingVerb(verb)

	p.P("mux.Handle(", fmt.Sprintf("%q", strings.ToUpper(verb)+" "+fullPath), ", o.WrapHandler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {")
	writePrincipalLookup(p, m)
	p.P("req := new(", p.MessageTypeName(m.Request), ")")

	if bodyBearing {
		writeBodyBinding(p, m)
	}
	writePathParamBinding(p, path, m.Request)
	writeQueryParamBinding(p, m.Request)

	for _, h := range m.Service.Headers {
		writeHeaderCheck(p, h)
	}
	for _, h := range m.Headers {
		writeHeaderCheck(p, h)
	}

	writeValidateCall(p)
	writeAuthorizeCall(p, m)

	p.P("routeCtx, control := RouteContext(w, r)")
	p.P("resp, err := srv.", PascalCase(m.Name), "(routeCtx, req)")
	p.P("if err != nil {")
	writeErrorHandling(p, m)
	p.P("return")
	p.P("}")
	p.P("writeJSON(w, control.Status(), resp)")
	p.P("}), RequestMetadata{Service: ", fmt.Sprintf("%q", s.Name), ", Method: ", fmt.Sprintf("%q", m.Name), ", HTTPMethod: ", fmt.Sprintf("%q", strings.ToUpper(verb)), ", Route: ", fmt.Sprintf("%q", fullPath), ", AuthSchemes: ", authSchemesLiteral(s, m), ", Scopes: ", scopesLiteral(m), ", Meta: ", metaLiteral(m), ", Guards: ", guardsLiteral(m), "}))")
}

const goNilLiteral = "nil"

func metaLiteral(m *onkir.Method) string {
	meta := m.Meta()
	if len(meta) == 0 {
		return goNilLiteral
	}
	entries := make([]string, 0, len(meta))
	for _, entry := range meta {
		entries = append(entries, fmt.Sprintf("%q: %q", entry.Key, entry.Value))
	}
	return "map[string]string{" + strings.Join(entries, ", ") + "}"
}

func guardsLiteral(m *onkir.Method) string {
	guards := m.Guards()
	if len(guards) == 0 {
		return goNilLiteral
	}
	quoted := make([]string, 0, len(guards))
	for _, guard := range guards {
		quoted = append(quoted, fmt.Sprintf("%q", guard))
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

func scopesLiteral(m *onkir.Method) string {
	scopes := m.RequiredScopes()
	if len(scopes) == 0 {
		return goNilLiteral
	}
	quoted := make([]string, 0, len(scopes))
	for _, scope := range scopes {
		quoted = append(quoted, fmt.Sprintf("%q", scope))
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

// authSchemeNamePattern strips characters that are unsafe in generated
// security-scheme identifiers.
var authSchemeNamePattern = regexp.MustCompile(`[^A-Za-z0-9_.-]+`)

func authSchemesLiteral(s *onkir.Service, m *onkir.Method) string {
	var names []string
	for _, h := range slices.Concat(s.Headers, m.Headers) {
		if _, ok := h.AuthType(); !ok {
			continue
		}
		if name, ok := h.AuthSchemeName(); ok && name != "" {
			names = append(names, name)
			continue
		}
		name := authSchemeNamePattern.ReplaceAllString(h.Name, "")
		if name == "" {
			name = "Header"
		}
		names = append(names, name+"Auth")
	}
	if len(names) == 0 {
		return goNilLiteral
	}
	quoted := make([]string, 0, len(names))
	for _, name := range names {
		quoted = append(quoted, fmt.Sprintf("%q", name))
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

func writeHeaderCheck(p *Printer, h *onkir.Header) {
	format, hasFormat := h.Format()
	if !h.Required() && !hasFormat {
		return
	}
	p.P("{")
	p.P("value := r.Header.Get(", fmt.Sprintf("%q", h.Name), ")")
	if h.Required() {
		p.P(`if value == "" {`)
		p.P("o.Fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: \"missing_header\", Field: ", fmt.Sprintf("%q", h.Name), ", Message: ", fmt.Sprintf("%q", "missing required header: "+h.Name), "})")
		p.P("return")
		p.P("}")
	}
	if hasFormat {
		p.P(`if value != "" && !validHeaderFormat(value, `, fmt.Sprintf("%q", format), `) {`)
		p.P("o.Fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: \"invalid_header\", Field: ", fmt.Sprintf("%q", h.Name), ", Message: ", fmt.Sprintf("%q", "invalid header "+h.Name+": expected "+format), "})")
		p.P("return")
		p.P("}")
	}
	if authType, ok := h.AuthType(); ok && (authType == "bearer" || authType == "basic") {
		scheme := "Bearer"
		if authType == "basic" {
			scheme = "Basic"
		}
		p.P(`if value != "" && !hasAuthScheme(value, `, fmt.Sprintf("%q", scheme), `) {`)
		p.P("o.Fail(w, r, &ServerError{Status: http.StatusUnauthorized, Code: \"invalid_credentials\", Field: ", fmt.Sprintf("%q", h.Name), ", Message: ", fmt.Sprintf("%q", "invalid "+h.Name+" header: expected "+scheme+" credentials"), "})")
		p.P("return")
		p.P("}")
	}
	p.P("}")
}

func writeErrorHandling(p *Printer, m *onkir.Method) {
	if len(m.ErrorTypes) == 0 {
		p.P(`o.WriteHandlerError(w, r, err)`)
		return
	}
	// errors.As unwraps wrapped errors (fmt.Errorf("%w", ...)), so typed
	// error responses still match when handlers wrap their error values.
	for index, errType := range m.ErrorTypes {
		status := 500
		if code, ok := errType.StatusCode(); ok {
			status = code
		}
		target := fmt.Sprintf("typedErr%d", index)
		p.P("var ", target, " *", p.MessageTypeName(errType))
		p.P("if errors.As(err, &", target, ") {")
		p.P(fmt.Sprintf("writeJSON(w, %d, ", status), target, ")")
		p.P("return")
		p.P("}")
	}
	p.P(`o.WriteHandlerError(w, r, err)`)
}
