package gengo

import (
	_ "embed"
	"fmt"
	"regexp"
	"slices"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

func scalarParseCall(kind onkir.ScalarKind, strExpr string) (string, bool) {
	switch kind {
	case onkir.ScalarInt32:
		return fmt.Sprintf("parseInt32(%s)", strExpr), true
	case onkir.ScalarInt64:
		return fmt.Sprintf("parseInt64(%s)", strExpr), true
	case onkir.ScalarUint32:
		return fmt.Sprintf("parseUint32(%s)", strExpr), true
	case onkir.ScalarUint64:
		return fmt.Sprintf("parseUint64(%s)", strExpr), true
	case onkir.ScalarFloat32:
		return fmt.Sprintf("parseFloat32(%s)", strExpr), true
	case onkir.ScalarFloat64:
		return fmt.Sprintf("parseFloat64(%s)", strExpr), true
	case onkir.ScalarBool:
		return fmt.Sprintf("parseBool(%s)", strExpr), true
	case onkir.ScalarBytes, onkir.ScalarTimestamp:
		return "", false
	default:
		return "", false
	}
}

// GenerateServer generates server.gen.go treating every message/enum type as
// local. Use GenerateServerWithResolver for a multi-package project where some
// referenced types live in a different generated package.
func GenerateServer(file *onkir.File) ([]byte, error) {
	return GenerateServerWithResolver(file, nil)
}

func GenerateServerWithResolver(file *onkir.File, resolver PackageResolver) ([]byte, error) {
	if len(file.Services) == 0 {
		return nil, nil
	}

	hasStream := onkir.FileHasStreamMethods(file)
	hasWS := onkir.FileHasWSMethods(file)
	hasWSCorrelation := onkir.FileHasWSCorrelation(file)
	hasRequestBody := fileHasRequestBodyBinding(file)
	externalRefs := collectServiceExternalRefs(file, resolver)

	p := newPrinter(resolver)
	if principal := filePrincipal(file); principal != nil {
		p.principalType = p.MessageTypeName(principal)
	}
	p.P("// Code generated by onek. DO NOT EDIT.")
	p.P("package ", GoPackageName(file))
	p.P()
	p.P("import (")
	if hasStream {
		p.P(`"bytes"`)
	}
	p.P(`"crypto/rand"`)
	p.P(`"context"`)
	p.P(`"encoding/hex"`)
	p.P(`"encoding/json"`)
	p.P(`"errors"`)
	p.P(`"fmt"`)
	if hasRequestBody || hasWS {
		p.P(`"io"`)
	}
	p.P(`"math"`)
	p.P(`"net/http"`)
	p.P(`"regexp"`)
	p.P(`"strconv"`)
	p.P(`"time"`)
	if hasWS {
		p.P(`"net"`)
	}
	if hasWS || hasStream {
		p.P(`"sync"`)
	}
	if hasWS {
		p.P(`"github.com/coder/websocket"`)
	}
	for _, ref := range externalRefs {
		p.P(ref.Alias, " ", fmt.Sprintf("%q", ref.ImportPath))
	}
	p.P(")")
	p.P()

	writeRuntimeHelpers(p)
	writeHeaderFormatPatterns(p)
	writeServerOptions(p, hasWS)
	if hasWS {
		writeWSOutType(p)
	}
	if hasWSCorrelation {
		writeWSPendingType(p, wsServerPendingType, wsServerPendingConstructor, wsServerClosedError)
	}
	if hasStream {
		writeSSEServerRuntime(p)
	}

	for _, s := range file.Services {
		for _, m := range s.Methods {
			if !m.IsWebSocket() {
				continue
			}
			if idField, ok := m.WSIDField(); ok {
				writeWSCorrelatedOutType(p, s, m, idField)
			}
		}
		writeServiceInterface(p, s)
		writeRegisterFunc(p, s)
	}

	return p.Format()
}

// fileHasRequestBodyBinding reports whether any route decodes a request body,
// which is what pulls io.EOF handling (and therefore the io import) into the
// generated server.
func fileHasRequestBodyBinding(file *onkir.File) bool {
	for _, service := range file.Services {
		for _, method := range service.Methods {
			if verb, ok := method.Verb(); ok && onkir.IsBodyBearingVerb(verb) {
				return true
			}
		}
	}
	return false
}

func writeServerContextAccessors(p *Printer) {
	p.P(`func RequestMetadataFromContext(ctx context.Context) (RequestMetadata, bool) {`)
	p.P(`metadata, ok := ctx.Value(requestMetadataContextKey{}).(RequestMetadata)`)
	p.P(`return metadata, ok`)
	p.P(`}`)
	p.P()
	p.P(`type httpRequestContextKey struct{}`)
	p.P()
	p.P(`func withHTTPRequest(r *http.Request) context.Context {`)
	p.P(`return context.WithValue(r.Context(), httpRequestContextKey{}, r)`)
	p.P(`}`)
	p.P()
	p.P(`type responseControl struct {`)
	p.P(`status int`)
	p.P(`header http.Header`)
	p.P(`}`)
	p.P()
	p.P(`type responseControlKey struct{}`)
	p.P()
	p.P(`func SetResponseStatus(ctx context.Context, status int) {`)
	p.P(`if control, ok := ctx.Value(responseControlKey{}).(*responseControl); ok && status >= 200 && status <= 299 {`)
	p.P(`control.status = status`)
	p.P(`}`)
	p.P(`}`)
	p.P()
	p.P(`func ResponseHeader(ctx context.Context) http.Header {`)
	p.P(`if control, ok := ctx.Value(responseControlKey{}).(*responseControl); ok {`)
	p.P(`return control.header`)
	p.P(`}`)
	p.P(`return http.Header{}`)
	p.P(`}`)
	p.P()
	p.P(`func HTTPRequestFromContext(ctx context.Context) (*http.Request, bool) {`)
	p.P(`r, ok := ctx.Value(httpRequestContextKey{}).(*http.Request)`)
	p.P(`return r, ok`)
	p.P(`}`)
	p.P()
	p.P(`func RequestIDFromContext(ctx context.Context) (string, bool) {`)
	p.P(`requestID, ok := ctx.Value(requestIDContextKey{}).(string)`)
	p.P(`return requestID, ok && requestID != ""`)
	p.P(`}`)
	p.P()
}

func writeWSServerOption(p *Printer) {
	p.P()
	p.P(`// WithMaxWSFrameBytes caps one inbound WebSocket message (default 16 MiB).`)
	p.P(`// A larger message closes the connection with status 1009 (message too`)
	p.P(`// big). A negative limit disables the check.`)
	p.P(`func WithMaxWSFrameBytes(limit int64) ServerOption { return func(o *serverOptions) { o.maxWSFrameBytes = limit } }`)
	p.P()
	p.P(`// wsCloseReason fits message into a close frame's 123-byte reason, cutting`)
	p.P(`// on a UTF-8 boundary; a longer reason would be replaced by a bare 1011.`)
	p.P(`func wsCloseReason(message string) string {`)
	p.P(`if len(message) <= 123 { return message }`)
	p.P(`cut := 123`)
	p.P(`for cut > 0 && message[cut]&0xC0 == 0x80 { cut-- }`)
	p.P(`return message[:cut]`)
	p.P(`}`)
	p.P()
	p.P(`func WithWSPingInterval(interval time.Duration) ServerOption { return func(o *serverOptions) { o.wsPingInterval = interval } }`)
	p.P()
	p.P(`func WithMaxWSMessageBytes(limit int64) ServerOption { return func(o *serverOptions) { o.maxWSMessageBytes = limit } }`)
	p.P()
	p.P(`func WithWSAcceptOptions(options *websocket.AcceptOptions) ServerOption { return func(o *serverOptions) { o.wsAcceptOptions = options } }`)
	p.P()
	p.P(`func wsServerReadLimit(limit int64) int64 {`)
	p.P(`if limit == 0 { return `, defaultMaxWSFrameBytes, ` }`)
	p.P(`if limit < 0 { return -1 }`)
	p.P(`return limit`)
	p.P(`}`)
}

// writeServerOptions emits runtime hooks shared by every generated server.
//
//go:embed runtime/server_hooks.go.tmpl
var serverHookTypesSource string

//go:embed runtime/server_middleware.go.tmpl
var serverMiddlewareTypesSource string

func writeServerOptions(p *Printer, hasWS bool) {
	p.P(serverHookTypesSource)
	writeServerContextAccessors(p)
	p.P(serverMiddlewareTypesSource)
	p.P(`type ServerOption func(*serverOptions)`)
	p.P()
	p.P(`type serverOptions struct {`)
	p.P(`mux *http.ServeMux`)
	p.P(`middlewares []Middleware`)
	p.P(`requestIDHeader string`)
	p.P(`requestIDGenerator RequestIDGenerator`)
	p.P(`authorizer Authorizer`)
	p.P(`errorWriter ErrorWriter`)
	if p.principalType != "" {
		p.P(`principal func(context.Context, *http.Request) (*`, p.principalType, `, error)`)
	}
	p.P(`observer RequestObserver`)
	p.P(`maxRequestBodyBytes int64`)
	p.P(`sseHeartbeat time.Duration`)
	p.P(`sseHeartbeatSet bool`)
	if hasWS {
		p.P(`maxWSFrameBytes int64`)
		p.P(`maxWSMessageBytes int64`)
		p.P(`wsPingInterval time.Duration`)
		p.P(`wsAcceptOptions *websocket.AcceptOptions`)
	}
	p.P(`}`)
	p.P()
	p.P(`// WithMux supports the options-first registration form.`)
	p.P(`func WithMux(mux *http.ServeMux) ServerOption { return func(o *serverOptions) { o.mux = mux } }`)
	p.P()
	p.P(`func WithMiddleware(middleware ...Middleware) ServerOption {`)
	p.P(`return func(o *serverOptions) { o.middlewares = append(o.middlewares, middleware...) }`)
	p.P(`}`)
	p.P()
	p.P(`func WithRequestID(headerName string) ServerOption { return WithRequestIDGenerator(headerName, defaultRequestIDGenerator) }`)
	p.P(`func WithRequestIDGenerator(headerName string, generate RequestIDGenerator) ServerOption {`)
	p.P(`return func(o *serverOptions) {`)
	p.P(`if headerName == "" { headerName = "X-Request-ID" }`)
	p.P(`o.requestIDHeader, o.requestIDGenerator = headerName, generate`)
	p.P(`}`)
	p.P(`}`)
	p.P()
	p.P(`func WithAuthorizer(authorizer Authorizer) ServerOption { return func(o *serverOptions) { o.authorizer = authorizer } }`)
	writeScopesOption(p)
	writePrincipalOption(p)
	p.P(serverErrorSource)
	p.P(`func WithRequestObserver(observer RequestObserver) ServerOption { return func(o *serverOptions) { o.observer = observer } }`)
	p.P(`func WithMaxRequestBodyBytes(limit int64) ServerOption { return func(o *serverOptions) { o.maxRequestBodyBytes = limit } }`)
	p.P(`func WithSSEHeartbeat(interval time.Duration) ServerOption { return func(o *serverOptions) { o.sseHeartbeat, o.sseHeartbeatSet = interval, true } }`)
	if hasWS {
		writeWSServerOption(p)
	}
	p.P()
	p.P(`func defaultRequestIDGenerator() string {`)
	p.P(`var value [16]byte`)
	p.P(`if _, err := rand.Read(value[:]); err != nil { return "" }`)
	p.P(`return hex.EncodeToString(value[:])`)
	p.P(`}`)
	p.P()
	p.P(`func (o serverOptions) wrapHandler(handler http.Handler, metadata RequestMetadata) http.Handler {`)
	p.P(`if o.authorizer != nil {`)
	p.P(`next := handler`)
	p.P(`handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {`)
	p.P(`if err := o.authorizer(r.Context(), metadata, r); err != nil {`)
	p.P(`var statusErr interface{ HTTPStatusCode() int }`)
	p.P(`if errors.As(err, &statusErr) { o.writeHandlerError(w, r, err) } else { o.fail(w, r, &ServerError{Status: http.StatusUnauthorized, Code: "unauthorized", Message: "unauthorized", Cause: err}) }`)
	p.P(`return`)
	p.P(`}`)
	p.P(`next.ServeHTTP(w, r)`)
	p.P(`})`)
	p.P(`}`)
	p.P(`for i := len(o.middlewares)-1; i >= 0; i-- { if o.middlewares[i] != nil { handler = o.middlewares[i](handler) } }`)
	p.P(`return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {`)
	p.P(`ctx := context.WithValue(r.Context(), requestMetadataContextKey{}, metadata)`)
	p.P(`if o.requestIDHeader != "" {`)
	p.P(`requestID := r.Header.Get(o.requestIDHeader)`)
	p.P(`if requestID == "" && o.requestIDGenerator != nil { requestID = o.requestIDGenerator() }`)
	p.P(`if requestID != "" { w.Header().Set(o.requestIDHeader, requestID); ctx = context.WithValue(ctx, requestIDContextKey{}, requestID) }`)
	p.P(`}`)
	p.P(`if o.observer == nil { handler.ServeHTTP(w, r.WithContext(ctx)); return }`)
	p.P(`started := time.Now()`)
	p.P(`ctx = o.observer.RequestStarted(ctx, metadata)`)
	p.P(`rw := &statusResponseWriter{ResponseWriter: w, statusCode: http.StatusOK}`)
	p.P(`defer func() { o.observer.RequestFinished(ctx, metadata, RequestResult{StatusCode: rw.statusCode, Duration: time.Since(started)}) }()`)
	p.P(`handler.ServeHTTP(rw, r.WithContext(ctx))`)
	p.P(`})`)
	p.P(`}`)
	p.P()
	p.P(`type statusResponseWriter struct { http.ResponseWriter; statusCode int; wroteHeader bool }`)
	p.P(`func (w *statusResponseWriter) WriteHeader(statusCode int) { if w.wroteHeader { return }; w.wroteHeader = true; w.statusCode = statusCode; w.ResponseWriter.WriteHeader(statusCode) }`)
	p.P(`func (w *statusResponseWriter) Write(data []byte) (int, error) { if !w.wroteHeader { w.WriteHeader(http.StatusOK) }; return w.ResponseWriter.Write(data) }`)
	p.P(`func (w *statusResponseWriter) Unwrap() http.ResponseWriter { return w.ResponseWriter }`)
	p.P(`func (w *statusResponseWriter) Flush() { if flusher, ok := w.ResponseWriter.(http.Flusher); ok { flusher.Flush() } }`)
	p.P()
}

func writeScopesOption(p *Printer) {
	p.P()
	p.P(`// WithScopes installs an authorizer that enforces @requires: granted returns the`)
	p.P(`// scopes the caller holds (return an error to reject the request, for example a`)
	p.P(`// 401), and any scope a route requires but the caller lacks produces a *ScopeError.`)
	p.P(`// It replaces a previous WithAuthorizer; to combine both, read RequestMetadata.Scopes`)
	p.P(`// inside your own Authorizer.`)
	p.P(`func WithScopes(granted func(context.Context, *http.Request) ([]string, error)) ServerOption {`)
	p.P(`return WithAuthorizer(func(ctx context.Context, metadata RequestMetadata, r *http.Request) error {`)
	p.P(`if len(metadata.Scopes) == 0 { return nil }`)
	p.P(`have, err := granted(ctx, r)`)
	p.P(`if err != nil { return err }`)
	p.P(`held := make(map[string]bool, len(have))`)
	p.P(`for _, scope := range have { held[scope] = true }`)
	p.P(`var missing []string`)
	p.P(`for _, scope := range metadata.Scopes { if !held[scope] { missing = append(missing, scope) } }`)
	p.P(`if len(missing) > 0 { return &ScopeError{Missing: missing} }`)
	p.P(`return nil`)
	p.P(`})`)
	p.P(`}`)
	p.P()
}

func writeRuntimeHelpers(p *Printer) {
	p.P(`func writeJSON(w http.ResponseWriter, status int, value any) {`)
	p.P(`data, err := json.Marshal(value)`)
	p.P(`if err != nil {`)
	p.P(`writeJSONError(w, http.StatusInternalServerError, "internal server error")`)
	p.P(`return`)
	p.P(`}`)
	p.P(`w.Header().Set("Content-Type", "application/json")`)
	p.P(`w.WriteHeader(status)`)
	p.P(`_, _ = w.Write(append(data, '\n'))`)
	p.P(`}`)
	p.P()
	p.P(`func writeJSONError(w http.ResponseWriter, status int, message string) {`)
	p.P(`w.Header().Set("Content-Type", "application/json")`)
	p.P(`w.WriteHeader(status)`)
	p.P(`_ = json.NewEncoder(w).Encode(map[string]string{"message": message})`)
	p.P(`}`)
	p.P()
	p.P(`func requestBodyLimit(limit int64) int64 {`)
	p.P(`if limit <= 0 { return 8 << 20 }`)
	p.P(`return limit`)
	p.P(`}`)
	p.P()
	p.P(`func parseInt32(s string) (int32, error) { v, err := strconv.ParseInt(s, 10, 32); if err != nil { return 0, errors.New("must be a 32-bit integer") }; return int32(v), nil }`)
	p.P(`func parseInt64(s string) (int64, error) { v, err := strconv.ParseInt(s, 10, 64); if err != nil { return 0, errors.New("must be an integer") }; return v, nil }`)
	p.P(`func parseUint32(s string) (uint32, error) { v, err := strconv.ParseUint(s, 10, 32); if err != nil { return 0, errors.New("must be a non-negative 32-bit integer") }; return uint32(v), nil }`)
	p.P(`func parseUint64(s string) (uint64, error) { v, err := strconv.ParseUint(s, 10, 64); if err != nil { return 0, errors.New("must be a non-negative integer") }; return v, nil }`)
	p.P(`func parseFloat32(s string) (float32, error) { v, err := strconv.ParseFloat(s, 32); if err != nil || math.IsNaN(v) || math.IsInf(v, 0) { return 0, fmt.Errorf("must be a finite number") }; return float32(v), nil }`)
	p.P(`func parseFloat64(s string) (float64, error) { v, err := strconv.ParseFloat(s, 64); if err != nil || math.IsNaN(v) || math.IsInf(v, 0) { return 0, fmt.Errorf("must be a finite number") }; return v, nil }`)
	p.P(`func parseBool(s string) (bool, error) {`)
	p.P(`if s == "true" { return true, nil }`)
	p.P(`if s == "false" { return false, nil }`)
	p.P(`return false, fmt.Errorf("must be true or false")`)
	p.P(`}`)
	p.P()
	p.P(`func hasAuthScheme(value, scheme string) bool {`)
	p.P(`if len(value) <= len(scheme)+1 || value[len(scheme)] != ' ' { return false }`)
	p.P(`for i := 0; i < len(scheme); i++ {`)
	p.P(`a, b := value[i], scheme[i]`)
	p.P(`if a >= 'A' && a <= 'Z' { a += 'a' - 'A' }`)
	p.P(`if b >= 'A' && b <= 'Z' { b += 'a' - 'A' }`)
	p.P(`if a != b { return false }`)
	p.P(`}`)
	p.P(`return true`)
	p.P(`}`)
	p.P()
	p.P(`func validHeaderFormat(value, format string) bool {`)
	p.P(`switch format {`)
	p.P(`case "uuid": return validHeaderUUID.MatchString(value)`)
	p.P(`case "email": return validHeaderEmail.MatchString(value)`)
	p.P(`case "uri": return validHeaderURI.MatchString(value)`)
	p.P(`default: return true`)
	p.P(`}`)
	p.P(`}`)
	p.P()
}

// writeHeaderFormatPatterns emits the package-level regexps backing
// validHeaderFormat. Compiling them once instead of per request avoids a
// regexp.MustCompile on every header validation call.
func writeHeaderFormatPatterns(p *Printer) {
	uuid := `^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`
	email := `^[^@\s]+@[^@\s]+\.[^@\s]+$`
	uri := `^[a-zA-Z][a-zA-Z0-9+.-]*://[^\s]+$`
	p.P(`var (`)
	p.P("validHeaderUUID = regexp.MustCompile(`" + uuid + "`)")
	p.P("validHeaderEmail = regexp.MustCompile(`" + email + "`)")
	p.P("validHeaderURI = regexp.MustCompile(`" + uri + "`)")
	p.P(`)`)
	p.P()
}

func writeServiceInterface(p *Printer, s *onkir.Service) {
	writeDoc(p, s.Doc)
	p.P("type ", s.Name, "Server interface {")
	for _, m := range s.Methods {
		writeDoc(p, deprecatedDoc(m.Doc, m.Deprecated))
		switch {
		case m.IsWebSocket():
			outType := "WSOut[" + p.MessageTypeName(m.Response) + "]"
			if _, ok := m.WSIDField(); ok {
				outType = "*" + wsOutName(s, m)
			}
			p.P(PascalCase(m.Name), "(ctx context.Context, req *",
				p.MessageTypeName(m.Request), ", out ", outType, ") error")
		case m.IsStream():
			p.P(PascalCase(m.Name), "(ctx context.Context, req *",
				p.MessageTypeName(m.Request), ", sender SSESender) error")
		default:
			p.P(PascalCase(m.Name), "(ctx context.Context, req *", p.MessageTypeName(m.Request),
				") (*", p.MessageTypeName(m.Response), ", error)")
		}
	}
	p.P("}")
	p.P()
}

func writeRegisterFunc(p *Printer, s *onkir.Service) {
	p.P("func Register", s.Name, "Server(first any, rest ...any) error {")
	p.P("var o serverOptions")
	p.P("var srv ", s.Name, "Server")
	p.P("if mux, ok := first.(*http.ServeMux); ok {")
	p.P("o.mux = mux")
	p.P("if len(rest) == 0 { return fmt.Errorf(\"Register", s.Name, "Server: implementation is required\") }")
	p.P("var ok bool")
	p.P("srv, ok = rest[0].(", s.Name, "Server)")
	p.P("if !ok { return fmt.Errorf(\"Register", s.Name, "Server: invalid implementation\") }")
	p.P("rest = rest[1:]")
	p.P("} else {")
	p.P("var ok bool")
	p.P("srv, ok = first.(", s.Name, "Server)")
	p.P("if !ok { return fmt.Errorf(\"Register", s.Name, "Server: invalid implementation\") }")
	p.P("}")
	p.P("for _, value := range rest {")
	p.P("opt, ok := value.(ServerOption)")
	p.P("if !ok { return fmt.Errorf(\"Register", s.Name, "Server: options must be ServerOption values\") }")
	p.P("opt(&o)")
	p.P("}")
	p.P("if o.mux == nil { return fmt.Errorf(\"Register", s.Name, "Server: mux is required\") }")
	p.P("mux := o.mux")
	for _, m := range s.Methods {
		switch {
		case m.IsWebSocket():
			writeWSRoute(p, s, m)
		case m.IsStream():
			writeSSERoute(p, s, m)
		default:
			writeRoute(p, s, m)
		}
	}
	p.P("return nil")
	p.P("}")
	p.P()
}

func writeBodyBinding(p *Printer, method *onkir.Method) {
	target := "req"
	var bodyField *onkir.Field
	if bodyName, ok := method.BodyField(); ok {
		if field := onkir.FindField(method.Request, bodyName); field != nil {
			target = "&req." + GoFieldName(field)
			bodyField = field
		}
	}
	p.P("if r.Body != nil {")
	if limit, ok := method.MaxBodyBytes(); ok {
		p.P("r.Body = http.MaxBytesReader(w, r.Body, ", limit, ")")
	} else {
		p.P("r.Body = http.MaxBytesReader(w, r.Body, requestBodyLimit(o.maxRequestBodyBytes))")
	}
	if bodyField != nil && bodyFieldNeedsCustomJSON(bodyField) {
		p.P("var bodyValue json.RawMessage")
		p.P("if err := json.NewDecoder(r.Body).Decode(&bodyValue); err != nil && !errors.Is(err, io.EOF) {")
		p.P(`o.writeBodyError(w, r, err)`)
		p.P("return")
		p.P("}")
		p.P("var bodyObject struct { Value json.RawMessage `json:\"", bodyField.Name, "\"` }")
		p.P("bodyObject.Value = bodyValue")
		p.P("bodyData, err := json.Marshal(bodyObject)")
		p.P("if err != nil {")
		p.P(`o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "invalid_request_body", Message: "invalid request body", Cause: err})`)
		p.P("return")
		p.P("}")
		p.P("if err := json.Unmarshal(bodyData, req); err != nil {")
	} else {
		p.P("if err := json.NewDecoder(r.Body).Decode(", target, "); err != nil && !errors.Is(err, io.EOF) {")
		p.P(`o.writeBodyError(w, r, err)`)
		p.P("return")
		p.P("}")
		p.P("}")
		return
	}
	p.P(`o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "invalid_request_body", Message: "invalid request body", Cause: err})`)
	p.P("return")
	p.P("}")
	p.P("}")
}

func writePathParamBinding(p *Printer, path string, req *onkir.Message) {
	for _, paramName := range onkir.PathParamNames(path) {
		field := onkir.FindField(req, paramName)
		if field == nil || field.Type == nil || field.Type.Kind != onkir.KindScalar {
			continue
		}
		raw := fmt.Sprintf("r.PathValue(%q)", paramName)
		if field.Type.Scalar == onkir.ScalarString {
			writeBoundFieldAssignment(p, field, raw)
			continue
		}
		call, ok := scalarParseCall(field.Type.Scalar, raw)
		if !ok {
			continue
		}
		writeParsedFieldAssignment(p, field, call, "path parameter "+paramName)
	}
}

func writeQueryParamBinding(p *Printer, req *onkir.Message) {
	for _, field := range req.Fields {
		d, ok := field.Decorator("query")
		if !ok || field.Type == nil || field.Type.Kind != onkir.KindScalar {
			continue
		}
		queryName, _ := d.Value()
		if queryName == "" {
			queryName = field.Name
		}
		if field.Repeated {
			valuesExpr := fmt.Sprintf("r.URL.Query()[%q]", queryName)
			p.P("if values := ", valuesExpr, "; len(values) > 0 {")
			p.P("req.", GoFieldName(field), " = make([]", p.GoFieldType(field.Type), ", 0, len(values))")
			p.P("for _, value := range values {")
			if field.Type.Scalar == onkir.ScalarString {
				p.P("req.", GoFieldName(field), " = append(req.", GoFieldName(field), ", value)")
			} else if call, ok := scalarParseCall(field.Type.Scalar, "value"); ok {
				parsed := "parsed" + GoFieldName(field)
				p.P(parsed, ", err := ", call)
				p.P("if err != nil {")
				p.P(`o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "invalid_query_parameter", Field: `, fmt.Sprintf("%q", queryName), `, Message: "invalid query parameter `, queryName, `: "+err.Error(), Cause: err})`)
				p.P("return")
				p.P("}")
				p.P("req.", GoFieldName(field), " = append(req.", GoFieldName(field), ", ", parsed, ")")
			}
			p.P("}")
			p.P("}")
			continue
		}
		p.P("if values := r.URL.Query()[", fmt.Sprintf("%q", queryName), "]; len(values) > 0 {")
		p.P("value := values[0]")
		if field.Type.Scalar == onkir.ScalarString {
			writeBoundFieldAssignment(p, field, "value")
		} else {
			call, ok := scalarParseCall(field.Type.Scalar, "value")
			if ok {
				writeParsedFieldAssignment(p, field, call, "query parameter "+queryName)
			}
		}
		p.P("}")
	}
}

func writeBoundFieldAssignment(p *Printer, field *onkir.Field, expr string) {
	if field.Optional {
		varName := CamelCase(field.Name) + "Val"
		p.P(varName, " := ", expr)
		p.P("req.", GoFieldName(field), " = &", varName)
		return
	}
	p.P("req.", GoFieldName(field), " = ", expr)
}

func writeParsedFieldAssignment(p *Printer, field *onkir.Field, call, location string) {
	code, fieldName := "invalid_query_parameter", field.Name
	if strings.HasPrefix(location, "path parameter ") {
		code, fieldName = "invalid_path_parameter", strings.TrimPrefix(location, "path parameter ")
	} else if strings.HasPrefix(location, "query parameter ") {
		fieldName = strings.TrimPrefix(location, "query parameter ")
	}
	varName := "parsed" + GoFieldName(field)
	p.P(varName, ", err := ", call)
	p.P("if err != nil {")
	p.P(`o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "`, code, `", Field: `, fmt.Sprintf("%q", fieldName), `, Message: "invalid `, location, `: "+err.Error(), Cause: err})`)
	p.P("return")
	p.P("}")
	if field.Optional {
		p.P("req.", GoFieldName(field), " = &", varName)
		return
	}
	p.P("req.", GoFieldName(field), " = ", varName)
}

func writeValidateCall(p *Printer) {
	p.P("if v, ok := any(req).(interface{ Validate() error }); ok {")
	p.P("if err := v.Validate(); err != nil {")
	p.P(`var list interface{ ViolationList() []string }`)
	p.P(`if errors.As(err, &list) {`)
	p.P(`o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "validation_failed", Message: err.Error(), Violations: list.ViolationList(), Cause: err})`)
	p.P("return")
	p.P("}")
	p.P(`o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "validation_failed", Message: err.Error(), Cause: err})`)
	p.P("return")
	p.P("}")
	p.P("}")
}

func writeRoute(p *Printer, s *onkir.Service, m *onkir.Method) {
	verb, _ := m.Verb()
	path, _ := m.Path()
	fullPath := s.BasePath + path
	bodyBearing := onkir.IsBodyBearingVerb(verb)

	p.P("mux.Handle(", fmt.Sprintf("%q", strings.ToUpper(verb)+" "+fullPath), ", o.wrapHandler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {")
	writePrincipalLookup(p, m)
	p.P("req := new(", p.MessageTypeName(m.Request), ")")

	if bodyBearing {
		writeBodyBinding(p, m)
	}
	writePathParamBinding(p, path, m.Request)
	if !bodyBearing {
		writeQueryParamBinding(p, m.Request)
	}

	for _, h := range m.Service.Headers {
		writeHeaderCheck(p, h)
	}
	for _, h := range m.Headers {
		writeHeaderCheck(p, h)
	}

	writeValidateCall(p)
	writeAuthorizeCall(p, m)

	p.P("control := &responseControl{status: http.StatusOK, header: w.Header()}")
	p.P("resp, err := srv.", PascalCase(m.Name), "(context.WithValue(withHTTPRequest(r), responseControlKey{}, control), req)")
	p.P("if err != nil {")
	writeErrorHandling(p, m)
	p.P("return")
	p.P("}")
	p.P("writeJSON(w, control.status, resp)")
	p.P("}), RequestMetadata{Service: ", fmt.Sprintf("%q", s.Name), ", Method: ", fmt.Sprintf("%q", m.Name), ", HTTPMethod: ", fmt.Sprintf("%q", strings.ToUpper(verb)), ", Route: ", fmt.Sprintf("%q", fullPath), ", AuthSchemes: ", authSchemesLiteral(s, m), ", Scopes: ", scopesLiteral(m), ", Meta: ", metaLiteral(m), "}))")
}

const goNilLiteral = "nil"

func metaLiteral(m *onkir.Method) string {
	meta := m.Meta()
	if len(meta) == 0 {
		return goNilLiteral
	}
	entries := make([]string, 0, len(meta))
	for _, entry := range meta {
		entries = append(entries, fmt.Sprintf("%q: %q", entry.Key, entry.Value))
	}
	return "map[string]string{" + strings.Join(entries, ", ") + "}"
}

func scopesLiteral(m *onkir.Method) string {
	scopes := m.RequiredScopes()
	if len(scopes) == 0 {
		return goNilLiteral
	}
	quoted := make([]string, 0, len(scopes))
	for _, scope := range scopes {
		quoted = append(quoted, fmt.Sprintf("%q", scope))
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

// authSchemeNamePattern strips characters that are unsafe in generated
// security-scheme identifiers.
var authSchemeNamePattern = regexp.MustCompile(`[^A-Za-z0-9_.-]+`)

func authSchemesLiteral(s *onkir.Service, m *onkir.Method) string {
	var names []string
	for _, h := range slices.Concat(s.Headers, m.Headers) {
		if _, ok := h.AuthType(); !ok {
			continue
		}
		if name, ok := h.AuthSchemeName(); ok && name != "" {
			names = append(names, name)
			continue
		}
		name := authSchemeNamePattern.ReplaceAllString(h.Name, "")
		if name == "" {
			name = "Header"
		}
		names = append(names, name+"Auth")
	}
	if len(names) == 0 {
		return goNilLiteral
	}
	quoted := make([]string, 0, len(names))
	for _, name := range names {
		quoted = append(quoted, fmt.Sprintf("%q", name))
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

func writeHeaderCheck(p *Printer, h *onkir.Header) {
	format, hasFormat := h.Format()
	if !h.Required() && !hasFormat {
		return
	}
	p.P("{")
	p.P("value := r.Header.Get(", fmt.Sprintf("%q", h.Name), ")")
	if h.Required() {
		p.P(`if value == "" {`)
		p.P("o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: \"missing_header\", Field: ", fmt.Sprintf("%q", h.Name), ", Message: ", fmt.Sprintf("%q", "missing required header: "+h.Name), "})")
		p.P("return")
		p.P("}")
	}
	if hasFormat {
		p.P(`if value != "" && !validHeaderFormat(value, `, fmt.Sprintf("%q", format), `) {`)
		p.P("o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: \"invalid_header\", Field: ", fmt.Sprintf("%q", h.Name), ", Message: ", fmt.Sprintf("%q", "invalid header "+h.Name+": expected "+format), "})")
		p.P("return")
		p.P("}")
	}
	if authType, ok := h.AuthType(); ok && (authType == "bearer" || authType == "basic") {
		scheme := "Bearer"
		if authType == "basic" {
			scheme = "Basic"
		}
		p.P(`if value != "" && !hasAuthScheme(value, `, fmt.Sprintf("%q", scheme), `) {`)
		p.P("o.fail(w, r, &ServerError{Status: http.StatusUnauthorized, Code: \"invalid_credentials\", Field: ", fmt.Sprintf("%q", h.Name), ", Message: ", fmt.Sprintf("%q", "invalid "+h.Name+" header: expected "+scheme+" credentials"), "})")
		p.P("return")
		p.P("}")
	}
	p.P("}")
}

func writeErrorHandling(p *Printer, m *onkir.Method) {
	if len(m.ErrorTypes) == 0 {
		p.P(`o.writeHandlerError(w, r, err)`)
		return
	}
	// errors.As unwraps wrapped errors (fmt.Errorf("%w", ...)), so typed
	// error responses still match when handlers wrap their error values.
	for index, errType := range m.ErrorTypes {
		status := 500
		if code, ok := errType.StatusCode(); ok {
			status = code
		}
		target := fmt.Sprintf("typedErr%d", index)
		p.P("var ", target, " *", p.MessageTypeName(errType))
		p.P("if errors.As(err, &", target, ") {")
		p.P(fmt.Sprintf("writeJSON(w, %d, ", status), target, ")")
		p.P("return")
		p.P("}")
	}
	p.P(`o.writeHandlerError(w, r, err)`)
}

const serverErrorSource = `// ServerError describes a failure the generated server is about to report.
// The default writer sends {"message": ...} (plus "violations" when there are
// any); install WithErrorWriter to send any other shape.
type ServerError struct {
	// Status is the HTTP status the server chose.
	Status int
	// Code is a stable machine-readable class: invalid_request_body,
	// request_body_too_large, invalid_path_parameter, invalid_query_parameter,
	// missing_header, invalid_header, invalid_credentials, validation_failed,
	// unauthorized, forbidden, not_found, method_not_allowed, internal, or the
	// snake_case name of the status for errors a handler returned.
	Code string
	// Message is the default human-readable message.
	Message string
	// Field names the path parameter, query parameter or header at fault.
	Field string
	// Violations lists the failed validation or authorization messages.
	Violations []string
	// Cause is the underlying error. It is never sent by the default writer.
	Cause error
}

// ErrorWriter writes a ServerError as the response. The request carries the
// request ID (RequestIDFromContext) and the route (RequestMetadataFromContext).
type ErrorWriter func(w http.ResponseWriter, r *http.Request, e *ServerError)

// WithErrorWriter replaces how the server reports its own errors: decoding,
// validation, parameters, headers, authorization, handler errors without a
// declared body, and the 404/405 answers wrapped by ErrorHandler. Errors a
// method declares with @status keep their declared body.
func WithErrorWriter(write ErrorWriter) ServerOption {
	return func(o *serverOptions) { o.errorWriter = write }
}

func (o serverOptions) fail(w http.ResponseWriter, r *http.Request, e *ServerError) {
	if o.errorWriter != nil {
		o.errorWriter(w, r, e)
		return
	}
	body := map[string]any{"message": e.Message}
	if len(e.Violations) > 0 {
		body["violations"] = e.Violations
	}
	writeJSON(w, e.Status, body)
}

func (o serverOptions) writeBodyError(w http.ResponseWriter, r *http.Request, err error) {
	var tooLarge *http.MaxBytesError
	if errors.As(err, &tooLarge) {
		o.fail(w, r, &ServerError{Status: http.StatusRequestEntityTooLarge, Code: "request_body_too_large", Message: "request body too large", Cause: err})
		return
	}
	o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "invalid_request_body", Message: "invalid request body", Cause: err})
}

func (o serverOptions) writeHandlerError(w http.ResponseWriter, r *http.Request, err error) {
	status := http.StatusInternalServerError
	var statusErr interface{ HTTPStatusCode() int }
	if errors.As(err, &statusErr) {
		if candidate := statusErr.HTTPStatusCode(); candidate >= 100 && candidate <= 599 {
			status = candidate
		}
	}
	message := "internal server error"
	var public interface{ PublicMessage() string }
	if errors.As(err, &public) && public.PublicMessage() != "" {
		message = public.PublicMessage()
	}
	code := statusCode(status)
	var coded interface{ PublicCode() string }
	if errors.As(err, &coded) && coded.PublicCode() != "" {
		code = coded.PublicCode()
	}
	o.fail(w, r, &ServerError{Status: status, Code: code, Message: message, Cause: err})
}

func statusCode(status int) string {
	if status == http.StatusInternalServerError {
		return "internal"
	}
	text := http.StatusText(status)
	out := make([]byte, 0, len(text))
	for i := 0; i < len(text); i++ {
		c := text[i]
		switch {
		case c >= 'A' && c <= 'Z':
			out = append(out, c+'a'-'A')
		case c >= 'a' && c <= 'z', c >= '0' && c <= '9':
			out = append(out, c)
		case len(out) > 0 && out[len(out)-1] != '_':
			out = append(out, '_')
		}
	}
	for len(out) > 0 && out[len(out)-1] == '_' {
		out = out[:len(out)-1]
	}
	if len(out) == 0 {
		return "error"
	}
	return string(out)
}

// ErrorHandler makes the router's own plain-text 404 and 405 answers use the
// same error writer as the generated routes. Wrap the mux you serve:
//
//	http.ListenAndServe(addr, ErrorHandler(mux, WithErrorWriter(write)))
//
// Only text/plain 404 and 405 responses are converted, so a handler that
// answers with its own JSON or HTML 404 is left alone.
func ErrorHandler(next http.Handler, opts ...ServerOption) http.Handler {
	var o serverOptions
	for _, opt := range opts {
		opt(&o)
	}
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		next.ServeHTTP(&routerErrorWriter{ResponseWriter: w, o: o, r: r}, r)
	})
}

type routerErrorWriter struct {
	http.ResponseWriter
	o         serverOptions
	r         *http.Request
	wrote     bool
	swallowed bool
}

func (w *routerErrorWriter) WriteHeader(status int) {
	if w.wrote {
		return
	}
	w.wrote = true
	contentType := w.Header().Get("Content-Type")
	if (status == http.StatusNotFound || status == http.StatusMethodNotAllowed) && len(contentType) >= 10 && contentType[:10] == "text/plain" {
		w.swallowed = true
		header := w.Header()
		header.Del("Content-Type")
		header.Del("Content-Length")
		header.Del("X-Content-Type-Options")
		code, message := "not_found", "not found"
		if status == http.StatusMethodNotAllowed {
			code, message = "method_not_allowed", "method not allowed"
		}
		w.o.fail(w.ResponseWriter, w.r, &ServerError{Status: status, Code: code, Message: message})
		return
	}
	w.ResponseWriter.WriteHeader(status)
}

func (w *routerErrorWriter) Write(data []byte) (int, error) {
	if !w.wrote {
		w.WriteHeader(http.StatusOK)
	}
	if w.swallowed {
		return len(data), nil
	}
	return w.ResponseWriter.Write(data)
}

func (w *routerErrorWriter) Unwrap() http.ResponseWriter { return w.ResponseWriter }

func (w *routerErrorWriter) Flush() {
	if flusher, ok := w.ResponseWriter.(http.Flusher); ok && !w.swallowed {
		flusher.Flush()
	}
}
`
