package gengo

import (
	"fmt"
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

func messageHasValidation(m *onkir.Message) bool {
	for _, f := range m.Fields {
		if fieldValidationRules(f) != nil {
			return true
		}
	}
	return false
}

func fieldValidationRules(f *onkir.Field) []string {
	if f.Type == nil || f.Type.Kind != onkir.KindScalar || f.Repeated {
		if !f.HasDecorator("required") {
			return nil
		}
	}

	var rules []string
	goName := PascalCase(f.Name)
	accessor := "m." + goName
	if f.Optional && f.Type != nil && f.Type.Kind == onkir.KindScalar {
		accessor = "*m." + goName
	}

	if f.HasDecorator("required") {
		requiredMsg := f.Name + " is required"
		switch {
		case f.Optional, f.Type != nil && f.Type.Kind == onkir.KindMessage:
			rules = append(rules, fmt.Sprintf(
				"if m.%s == nil { violations = append(violations, %q) }", goName, requiredMsg,
			))
		case f.Type != nil && f.Type.Kind == onkir.KindScalar && f.Type.Scalar == onkir.ScalarString:
			rules = append(rules, fmt.Sprintf(
				`if %s == "" { violations = append(violations, %q) }`, accessor, requiredMsg,
			))
		}
	}

	if f.Type == nil || f.Type.Kind != onkir.KindScalar || f.Type.Scalar != onkir.ScalarString {
		return dedupeEmpty(rules)
	}

	if f.HasDecorator("email") {
		rules = append(rules, fmt.Sprintf(
			`if %s != "" && !emailPattern.MatchString(%s) { violations = append(violations, %q) }`,
			accessor, accessor, f.Name+" must be a valid email",
		))
	}
	if f.HasDecorator("uuid") {
		rules = append(rules, fmt.Sprintf(
			`if %s != "" && !uuidPattern.MatchString(%s) { violations = append(violations, %q) }`,
			accessor, accessor, f.Name+" must be a valid uuid",
		))
	}
	if d, ok := f.Decorator("len"); ok {
		minArg, _ := d.Arg(0)
		maxArg, _ := d.Arg(1)
		rules = append(rules, fmt.Sprintf(
			"if len(%s) < %s || len(%s) > %s { violations = append(violations, %q) }",
			accessor, minArg, accessor, maxArg,
			fmt.Sprintf("%s must be between %s and %s characters", f.Name, minArg, maxArg),
		))
	}
	if d, ok := f.Decorator("in"); ok {
		var quoted []string
		for _, a := range d.Args {
			quoted = append(quoted, fmt.Sprintf("%q", a.Value))
		}
		rules = append(rules, fmt.Sprintf(
			"if !inSet(%s, %s) { violations = append(violations, %q) }",
			accessor, strings.Join(quoted, ", "), f.Name+" must be one of the allowed values",
		))
	}
	if d, ok := f.Decorator("range"); ok {
		minArg, _ := d.Arg(0)
		maxArg, _ := d.Arg(1)
		rules = append(rules, fmt.Sprintf(
			"if %s < %s || %s > %s { violations = append(violations, %q) }",
			accessor, minArg, accessor, maxArg,
			fmt.Sprintf("%s must be between %s and %s", f.Name, minArg, maxArg),
		))
	}

	return dedupeEmpty(rules)
}

func dedupeEmpty(rules []string) []string {
	if len(rules) == 0 {
		return nil
	}
	return rules
}

func GenerateValidation(file *onkir.File) ([]byte, error) {
	var needed bool
	for _, m := range file.Messages {
		if messageHasValidation(m) {
			needed = true
			break
		}
	}
	if !needed {
		return nil, nil
	}

	p := &Printer{}
	p.P("// Code generated by onek. DO NOT EDIT.")
	p.P("package ", GoPackageName(file))
	p.P()
	p.P(`import (`)
	p.P(`"errors"`)
	p.P(`"regexp"`)
	p.P(`"strings"`)
	p.P(")")
	p.P()
	p.P(`var emailPattern = regexp.MustCompile(` + "`" + `^[^@\s]+@[^@\s]+\.[^@\s]+$` + "`" + `)`)
	uuidRegex := `^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-` +
		`[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`
	p.P(`var uuidPattern = regexp.MustCompile(` + "`" + uuidRegex + "`" + `)`)
	p.P()
	p.P("func inSet(v string, allowed ...string) bool {")
	p.P("for _, a := range allowed {")
	p.P("if v == a {")
	p.P("return true")
	p.P("}")
	p.P("}")
	p.P("return false")
	p.P("}")
	p.P()

	for _, m := range file.Messages {
		writeValidate(p, m)
	}

	return p.Format()
}

func writeValidate(p *Printer, m *onkir.Message) {
	if messageHasValidation(m) {
		p.P("func (m *", m.Name, ") Validate() error {")
		p.P("var violations []string")
		for _, f := range m.Fields {
			for _, rule := range fieldValidationRules(f) {
				p.P(rule)
			}
		}
		p.P("if len(violations) > 0 {")
		p.P(`return errors.New(strings.Join(violations, "; "))`)
		p.P("}")
		p.P("return nil")
		p.P("}")
		p.P()
	}
	for _, nested := range m.Nested {
		writeValidate(p, nested)
	}
}
