// Code generated by onek. DO NOT EDIT.

import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

public let onekitDefaultMaxResponseBodyBytes = 8 << 20
public let onekitDefaultMaxSSELineBytes = 1 << 20
public let onekitDefaultRequestTimeout: TimeInterval = 30

public let onekitEmailPattern = "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"
public let onekitUUIDPattern = "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
public let onekitURIPattern = "^[a-zA-Z][a-zA-Z0-9+.-]*://[^\\s]+$"

public enum OnekitError: Error, CustomStringConvertible, @unchecked Sendable {
    case validation([String])
    case unexpectedStatus(status: Int, body: Data, headers: [String: String])
    case stream(payload: Any?)
    case responseTooLarge(limit: Int)
    case decoding(String)
    case invalidURL(String)

    public var description: String {
        switch self {
        case .validation(let violations):
            return "OnekitError.validation: " + violations.joined(separator: "; ")
        case .unexpectedStatus(let status, let body, _):
            return "OnekitError.unexpectedStatus: \(status) " + String(decoding: body, as: UTF8.self)
        case .stream(let payload):
            return "OnekitError.stream: \(String(describing: payload))"
        case .responseTooLarge(let limit):
            return "OnekitError.responseTooLarge: response exceeds \(limit) bytes"
        case .decoding(let message):
            return "OnekitError.decoding: " + message
        case .invalidURL(let url):
            return "OnekitError.invalidURL: " + url
        }
    }
}

public protocol OnekitMessage {
    func toJSONValue() -> Any
    func validate() -> [String]
}

public struct OnekitResponse {
    public let status: Int
    public let headers: [String: String]
    public let body: Data

    public var ok: Bool { status >= 200 && status < 300 }
}

public func onekitCheck(_ violations: [String]) throws {
    if !violations.isEmpty { throw OnekitError.validation(violations) }
}

public func onekitMatches(_ pattern: String, _ value: String) -> Bool {
    value.range(of: pattern, options: .regularExpression) != nil
}

public func onekitTrimSlash(_ baseURL: String) -> String {
    var out = baseURL
    while out.hasSuffix("/") { out.removeLast() }
    return out
}

private let onekitUnreserved = CharacterSet(charactersIn: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~")

public func onekitPathValue<T>(_ value: T) -> String {
    String(describing: value).addingPercentEncoding(withAllowedCharacters: onekitUnreserved) ?? ""
}

public func onekitPathWildcard<T>(_ value: T) -> String {
    String(describing: value).split(separator: "/", omittingEmptySubsequences: false)
        .map { onekitPathValue(String($0)) }
        .joined(separator: "/")
}

public func onekitQueryValue<T>(_ value: T) -> String {
    String(describing: value)
}

public func onekitMerge(_ base: [String: String], _ extra: [String: String]) -> [String: String] {
    base.merging(extra) { _, new in new }
}

public func onekitTimeout(_ client: TimeInterval?, _ call: TimeInterval?) -> TimeInterval? {
    guard let timeout = call ?? client, timeout > 0 else { return nil }
    return timeout
}

public func onekitRequest(
    method: String,
    baseURL: String,
    path: String,
    query: [(String, String)],
    headers: [String: String],
    timeout: TimeInterval?
) throws -> URLRequest {
    var text = baseURL + path
    if !query.isEmpty {
        let encoded = query.map { key, value in
            onekitQueryComponent(key) + "=" + onekitQueryComponent(value)
        }
        text += "?" + encoded.joined(separator: "&")
    }
    guard let url = URL(string: text) else { throw OnekitError.invalidURL(text) }
    var request = URLRequest(url: url)
    request.httpMethod = method
    if let timeout { request.timeoutInterval = timeout }
    for (name, value) in headers { request.setValue(value, forHTTPHeaderField: name) }
    return request
}

private func onekitQueryComponent(_ value: String) -> String {
    value.addingPercentEncoding(withAllowedCharacters: onekitUnreserved) ?? ""
}

public func onekitHeaderMap(_ response: HTTPURLResponse) -> [String: String] {
    var out: [String: String] = [:]
    for (key, value) in response.allHeaderFields {
        out[String(describing: key).lowercased()] = String(describing: value)
    }
    return out
}

@available(macOS 12.0, iOS 15.0, tvOS 15.0, watchOS 8.0, *)
public func onekitReadBounded(_ bytes: URLSession.AsyncBytes, limit: Int) async throws -> Data {
    let max = limit > 0 ? limit : onekitDefaultMaxResponseBodyBytes
    var out = Data()
    for try await byte in bytes {
        out.append(byte)
        if out.count > max { throw OnekitError.responseTooLarge(limit: max) }
    }
    return out
}

@available(macOS 12.0, iOS 15.0, tvOS 15.0, watchOS 8.0, *)
public func onekitSend(_ session: URLSession, _ request: URLRequest, maxBodyBytes: Int) async throws -> OnekitResponse {
    let (bytes, response) = try await session.bytes(for: request)
    guard let http = response as? HTTPURLResponse else { throw OnekitError.invalidURL(request.url?.absoluteString ?? "") }
    let limit = maxBodyBytes > 0 ? maxBodyBytes : onekitDefaultMaxResponseBodyBytes
    if http.expectedContentLength > Int64(limit) { throw OnekitError.responseTooLarge(limit: limit) }
    let body = try await onekitReadBounded(bytes, limit: limit)
    return OnekitResponse(status: http.statusCode, headers: onekitHeaderMap(http), body: body)
}

public func onekitJSONData(_ value: Any) throws -> Data {
    do {
        return try JSONSerialization.data(withJSONObject: value, options: [.fragmentsAllowed])
    } catch {
        throw OnekitError.decoding("request is not valid JSON: \(error)")
    }
}

public func onekitDecodeBody(_ body: Data) throws -> Any? {
    if String(decoding: body, as: UTF8.self).trimmingCharacters(in: .whitespacesAndNewlines).isEmpty { return [String: Any]() }
    return try onekitParseJSON(body)
}

public func onekitParseJSON(_ data: Data) throws -> Any? {
    do {
        return try JSONSerialization.jsonObject(with: data, options: [.fragmentsAllowed])
    } catch {
        throw OnekitError.decoding("invalid JSON: \(error)")
    }
}

public func onekitTryJSON(_ body: Data) -> Any? {
    try? JSONSerialization.jsonObject(with: body, options: [.fragmentsAllowed])
}

public func onekitIsNull(_ value: Any?) -> Bool {
    value == nil || value is NSNull
}

public func onekitNonNull(_ value: Any?) -> Any? {
    onekitIsNull(value) ? nil : value
}

public func onekitIsEmptyObject(_ value: Any) -> Bool {
    (value as? [String: Any])?.isEmpty ?? false
}

public func onekitObject(_ value: Any?) throws -> [String: Any] {
    if onekitIsNull(value) { return [:] }
    if let object = value as? [String: Any] { return object }
    throw OnekitError.decoding("expected a JSON object")
}

public func onekitString(_ value: Any?) throws -> String {
    if let text = value as? String { return text }
    throw OnekitError.decoding("expected a string")
}

public func onekitBool(_ value: Any?) throws -> Bool {
    if let flag = value as? Bool { return flag }
    throw OnekitError.decoding("expected a boolean")
}

public func onekitInt64(_ value: Any?) throws -> Int64 {
    if let number = value as? NSNumber, let exact = Int64(exactly: number) { return exact }
    if let text = value as? String, let number = Int64(text) { return number }
    throw OnekitError.decoding("expected an integer")
}

public func onekitUInt64(_ value: Any?) throws -> UInt64 {
    if let number = value as? NSNumber, let exact = UInt64(exactly: number) { return exact }
    if let text = value as? String, let number = UInt64(text) { return number }
    throw OnekitError.decoding("expected an unsigned integer")
}

public func onekitInt32(_ value: Any?) throws -> Int32 {
    guard let number = Int32(exactly: try onekitInt64(value)) else { throw OnekitError.decoding("integer out of int32 range") }
    return number
}

public func onekitUInt32(_ value: Any?) throws -> UInt32 {
    guard let number = UInt32(exactly: try onekitUInt64(value)) else { throw OnekitError.decoding("integer out of uint32 range") }
    return number
}

public func onekitDouble(_ value: Any?) throws -> Double {
    if let number = value as? NSNumber { return number.doubleValue }
    if let text = value as? String, let number = Double(text) { return number }
    throw OnekitError.decoding("expected a number")
}

public func onekitList<T>(_ value: Any?, _ decode: (Any?) throws -> T) throws -> [T] {
    guard let list = value as? [Any] else { throw OnekitError.decoding("expected a JSON array") }
    return try list.map { try decode($0) }
}

public func onekitMap<T>(_ value: Any?, _ decode: (Any?) throws -> T) throws -> [String: T] {
    let object = try onekitObject(value)
    var out: [String: T] = [:]
    for (key, item) in object { out[key] = try decode(item) }
    return out
}

public func onekitEnumByIndex<T: CaseIterable>(_ type: T.Type, _ value: Any?) throws -> T {
    let index = try onekitInt64(value)
    let all = Array(T.allCases)
    guard index >= 0, index < Int64(all.count) else { throw OnekitError.decoding("enum index \(index) out of range") }
    return all[Int(index)]
}

public func onekitBytesEncode(_ value: Data, _ encoding: String) -> String {
    switch encoding {
    case "hex":
        return value.map { String(format: "%02x", $0) }.joined()
    case "base64_raw":
        return value.base64EncodedString().replacingOccurrences(of: "=", with: "")
    case "base64url":
        return onekitURLSafe(value.base64EncodedString())
    case "base64url_raw":
        return onekitURLSafe(value.base64EncodedString()).replacingOccurrences(of: "=", with: "")
    default:
        return value.base64EncodedString()
    }
}

private func onekitURLSafe(_ text: String) -> String {
    text.replacingOccurrences(of: "+", with: "-").replacingOccurrences(of: "/", with: "_")
}

public func onekitBytesDecode(_ value: Any?, _ encoding: String) throws -> Data {
    let text = try onekitString(value)
    switch encoding {
    case "hex":
        let chars = Array(text.utf8)
        guard chars.count % 2 == 0 else { throw OnekitError.decoding("odd-length hex string") }
        var out = Data()
        var index = 0
        while index < chars.count {
            guard let byte = UInt8(String(decoding: chars[index..<index + 2], as: UTF8.self), radix: 16) else {
                throw OnekitError.decoding("invalid hex string")
            }
            out.append(byte)
            index += 2
        }
        return out
    case "base64url", "base64url_raw":
        return try onekitBase64(text.replacingOccurrences(of: "-", with: "+").replacingOccurrences(of: "_", with: "/"))
    default:
        return try onekitBase64(text)
    }
}

private func onekitBase64(_ text: String) throws -> Data {
    var padded = text
    while padded.count % 4 != 0 { padded += "=" }
    guard let data = Data(base64Encoded: padded) else { throw OnekitError.decoding("invalid base64 string") }
    return data
}

private func onekitDaysFromCivil(_ year: Int, _ month: Int, _ day: Int) -> Int {
    let y = month <= 2 ? year - 1 : year
    let era = (y >= 0 ? y : y - 399) / 400
    let yoe = y - era * 400
    let mp = (month + 9) % 12
    let doy = (153 * mp + 2) / 5 + day - 1
    let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy
    return era * 146097 + doe - 719468
}

private func onekitCivilFromDays(_ days: Int) -> (Int, Int, Int) {
    let z = days + 719468
    let era = (z >= 0 ? z : z - 146096) / 146097
    let doe = z - era * 146097
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365
    let y = yoe + era * 400
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100)
    let mp = (5 * doy + 2) / 153
    let d = doy - (153 * mp + 2) / 5 + 1
    let m = mp < 10 ? mp + 3 : mp - 9
    return (m <= 2 ? y + 1 : y, m, d)
}

private func onekitTwo(_ value: Int) -> String {
    value < 10 ? "0\(value)" : "\(value)"
}

public func onekitTimeEncode(_ value: Date, _ encoding: String) -> Any {
    let seconds = value.timeIntervalSince1970
    switch encoding {
    case "unix_seconds":
        return Int64(seconds.rounded(.down))
    case "unix_millis":
        return Int64((seconds * 1000).rounded(.down))
    default:
        var whole = Int64(seconds.rounded(.down))
        var micros = Int(((seconds - Double(whole)) * 1_000_000).rounded())
        if micros >= 1_000_000 {
            whole += 1
            micros = 0
        }
        let days = Int(whole >= 0 ? whole / 86400 : (whole - 86399) / 86400)
        let remainder = Int(whole - Int64(days) * 86400)
        let (year, month, day) = onekitCivilFromDays(days)
        let date = String(format: "%04d-%02d-%02d", year, month, day)
        if encoding == "date" { return date }
        var out = date + "T" + onekitTwo(remainder / 3600) + ":" + onekitTwo(remainder % 3600 / 60) + ":" + onekitTwo(remainder % 60)
        if micros != 0 { out += "." + String(format: "%06d", micros) }
        return out + "Z"
    }
}

public func onekitTimeDecode(_ value: Any?, _ encoding: String) throws -> Date {
    switch encoding {
    case "unix_seconds":
        return Date(timeIntervalSince1970: Double(try onekitInt64(value)))
    case "unix_millis":
        return Date(timeIntervalSince1970: Double(try onekitInt64(value)) / 1000)
    case "date":
        return try onekitParseTimestamp(try onekitString(value) + "T00:00:00Z")
    default:
        return try onekitParseTimestamp(try onekitString(value))
    }
}

private let onekitTimestampPattern = try! NSRegularExpression(
    pattern: "^(\\d{4})-(\\d{2})-(\\d{2})[Tt ](\\d{2}):(\\d{2}):(\\d{2})(\\.\\d+)?([Zz]|[+-]\\d{2}:?\\d{2})$"
)

private func onekitParseTimestamp(_ text: String) throws -> Date {
    let range = NSRange(text.startIndex..., in: text)
    guard let match = onekitTimestampPattern.firstMatch(in: text, range: range) else {
        throw OnekitError.decoding("invalid timestamp: \(text)")
    }
    func group(_ index: Int) -> String? {
        let r = match.range(at: index)
        guard r.location != NSNotFound, let swiftRange = Range(r, in: text) else { return nil }
        return String(text[swiftRange])
    }
    guard let year = Int(group(1) ?? ""), let month = Int(group(2) ?? ""), let day = Int(group(3) ?? ""),
          let hour = Int(group(4) ?? ""), let minute = Int(group(5) ?? ""), let second = Int(group(6) ?? "") else {
        throw OnekitError.decoding("invalid timestamp: \(text)")
    }
    var seconds = Double(onekitDaysFromCivil(year, month, day)) * 86400 + Double(hour * 3600 + minute * 60 + second)
    if let fraction = group(7), let value = Double("0" + fraction) { seconds += value }
    if let zone = group(8), zone.uppercased() != "Z" {
        let sign: Double = zone.hasPrefix("-") ? -1 : 1
        let digits = zone.dropFirst().replacingOccurrences(of: ":", with: "")
        if digits.count == 4, let hours = Int(digits.prefix(2)), let minutes = Int(digits.suffix(2)) {
            seconds -= sign * Double(hours * 3600 + minutes * 60)
        }
    }
    return Date(timeIntervalSince1970: seconds)
}

public func onekitHasPrefix(_ json: [String: Any], _ prefix: String) -> Bool {
    json.keys.contains { $0.hasPrefix(prefix) }
}

public func onekitStripPrefix(_ json: [String: Any], _ prefix: String) -> [String: Any] {
    var out: [String: Any] = [:]
    for (key, value) in json where key.hasPrefix(prefix) {
        out[String(key.dropFirst(prefix.count))] = value
    }
    return out
}

public func onekitJSONEquals(_ left: Any?, _ right: Any?) -> Bool {
    if onekitIsNull(left) && onekitIsNull(right) { return true }
    if let a = left as? [String: Any], let b = right as? [String: Any] {
        guard a.count == b.count else { return false }
        for (key, value) in a {
            guard let other = b[key], onekitJSONEquals(value, other) else { return false }
        }
        return true
    }
    if let a = left as? [Any], let b = right as? [Any] {
        guard a.count == b.count else { return false }
        for index in a.indices where !onekitJSONEquals(a[index], b[index]) { return false }
        return true
    }
    if let a = left as? String, let b = right as? String { return a == b }
    if left is String || right is String { return false }
    if let a = left as? NSNumber, let b = right as? NSNumber { return a == b }
    return false
}

public struct OnekitSSEEvent {
    public let event: String
    public let data: String
}

@available(macOS 12.0, iOS 15.0, tvOS 15.0, watchOS 8.0, *)
public func onekitSSEEvents(_ bytes: URLSession.AsyncBytes, maxLineBytes: Int) -> AsyncThrowingStream<OnekitSSEEvent, Error> {
    let limit = maxLineBytes > 0 ? maxLineBytes : onekitDefaultMaxSSELineBytes
    return AsyncThrowingStream { continuation in
        let task = Task {
            var event = ""
            var data: [String] = []
            var line = [UInt8]()
            func finish(_ raw: [UInt8]) throws {
                var bytes = raw
                if bytes.last == 13 { bytes.removeLast() }
                if bytes.count > limit { throw OnekitError.decoding("SSE line exceeds configured limit") }
                let text = String(decoding: bytes, as: UTF8.self)
                if text.isEmpty {
                    if !data.isEmpty { continuation.yield(OnekitSSEEvent(event: event, data: data.joined(separator: "\n"))) }
                    event = ""
                    data.removeAll()
                    return
                }
                if text.hasPrefix(":") { return }
                var name = text
                var value = ""
                if let colon = text.firstIndex(of: ":") {
                    name = String(text[text.startIndex..<colon])
                    value = String(text[text.index(after: colon)...])
                    if value.hasPrefix(" ") { value.removeFirst() }
                }
                if name == "event" {
                    event = value
                } else if name == "data" {
                    data.append(value)
                }
            }
            do {
                for try await byte in bytes {
                    if byte == 10 {
                        try finish(line)
                        line.removeAll(keepingCapacity: true)
                    } else {
                        line.append(byte)
                        if line.count > limit + 1 { throw OnekitError.decoding("SSE line exceeds configured limit") }
                    }
                }
                if !line.isEmpty { try finish(line) }
                if !data.isEmpty { continuation.yield(OnekitSSEEvent(event: event, data: data.joined(separator: "\n"))) }
                continuation.finish()
            } catch {
                continuation.finish(throwing: error)
            }
        }
        continuation.onTermination = { _ in task.cancel() }
    }
}

@available(macOS 12.0, iOS 15.0, tvOS 15.0, watchOS 8.0, *)
public func onekitStream<T>(
    session: URLSession,
    maxResponseBodyBytes: Int,
    maxSSELineBytes: Int,
    request makeRequest: @escaping () throws -> URLRequest,
    typedError: @escaping (Int, Data) -> Error?,
    decode: @escaping (Any?) throws -> T
) -> AsyncThrowingStream<T, Error> {
    AsyncThrowingStream { continuation in
        let task = Task {
            do {
                let request = try makeRequest()
                let (bytes, response) = try await session.bytes(for: request)
                guard let http = response as? HTTPURLResponse else {
                    throw OnekitError.invalidURL(request.url?.absoluteString ?? "")
                }
                if http.statusCode < 200 || http.statusCode >= 300 {
                    let body = try await onekitReadBounded(bytes, limit: maxResponseBodyBytes)
                    if let error = typedError(http.statusCode, body) { throw error }
                    throw OnekitError.unexpectedStatus(status: http.statusCode, body: body, headers: onekitHeaderMap(http))
                }
                for try await event in onekitSSEEvents(bytes, maxLineBytes: maxSSELineBytes) {
                    let payload = try onekitParseJSON(Data(event.data.utf8))
                    if event.event == "error" { throw OnekitError.stream(payload: payload) }
                    continuation.yield(try decode(payload))
                }
                continuation.finish()
            } catch {
                continuation.finish(throwing: error)
            }
        }
        continuation.onTermination = { _ in task.cancel() }
    }
}
