// Code generated by onek. DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

const defaultMaxResponseBodyBytes int64 = 8 << 20
const defaultMaxSSELineBytes = 1 << 20

func responseBodyLimit(value int64) int64 {
	if value <= 0 {
		return defaultMaxResponseBodyBytes
	}
	return value
}

func readResponseBody(body io.Reader, limit int64) ([]byte, error) {
	limit = responseBodyLimit(limit)
	data, err := io.ReadAll(io.LimitReader(body, limit+1))
	if err != nil {
		return nil, err
	}
	if int64(len(data)) > limit {
		return nil, fmt.Errorf("response body exceeds configured limit")
	}
	return data, nil
}

type UserServiceClient struct {
	BaseURL              string
	HTTPClient           *http.Client
	Headers              map[string]string
	MaxResponseBodyBytes int64
	MaxSSELineBytes      int
}

func NewUserServiceClient(baseURL string) *UserServiceClient {
	return &UserServiceClient{BaseURL: baseURL, HTTPClient: http.DefaultClient, Headers: map[string]string{}, MaxResponseBodyBytes: defaultMaxResponseBodyBytes, MaxSSELineBytes: defaultMaxSSELineBytes}
}

func (c *UserServiceClient) CreateUser(ctx context.Context, req *CreateUserRequest) (*User, error) {
	if validator, ok := any(req).(interface{ Validate() error }); ok {
		if err := validator.Validate(); err != nil {
			return nil, fmt.Errorf("validate request: %w", err)
		}
	}
	path := "/api/v1/users"
	body, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("marshal request: %w", err)
	}
	httpReq, err := http.NewRequestWithContext(ctx, "POST", c.BaseURL+path, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("build request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")
	for k, v := range c.Headers {
		httpReq.Header.Set(k, v)
	}
	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		respBody, bodyErr := readResponseBody(resp.Body, c.MaxResponseBodyBytes)
		if bodyErr != nil {
			return nil, bodyErr
		}
		return nil, fmt.Errorf("unexpected status %d: %s", resp.StatusCode, string(respBody))
	}
	result := new(User)
	if err := json.NewDecoder(io.LimitReader(resp.Body, responseBodyLimit(c.MaxResponseBodyBytes))).Decode(result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

func (c *UserServiceClient) GetUser(ctx context.Context, req *GetUserRequest) (*User, error) {
	if validator, ok := any(req).(interface{ Validate() error }); ok {
		if err := validator.Validate(); err != nil {
			return nil, fmt.Errorf("validate request: %w", err)
		}
	}
	path := "/api/v1/users/get"
	body, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("marshal request: %w", err)
	}
	httpReq, err := http.NewRequestWithContext(ctx, "POST", c.BaseURL+path, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("build request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")
	for k, v := range c.Headers {
		httpReq.Header.Set(k, v)
	}
	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		respBody, bodyErr := readResponseBody(resp.Body, c.MaxResponseBodyBytes)
		if bodyErr != nil {
			return nil, bodyErr
		}
		return nil, fmt.Errorf("unexpected status %d: %s", resp.StatusCode, string(respBody))
	}
	result := new(User)
	if err := json.NewDecoder(io.LimitReader(resp.Body, responseBodyLimit(c.MaxResponseBodyBytes))).Decode(result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

func (c *UserServiceClient) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	if validator, ok := any(req).(interface{ Validate() error }); ok {
		if err := validator.Validate(); err != nil {
			return nil, fmt.Errorf("validate request: %w", err)
		}
	}
	path := "/api/v1/auth/login"
	body, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("marshal request: %w", err)
	}
	httpReq, err := http.NewRequestWithContext(ctx, "POST", c.BaseURL+path, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("build request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")
	for k, v := range c.Headers {
		httpReq.Header.Set(k, v)
	}
	resp, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("do request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		respBody, bodyErr := readResponseBody(resp.Body, c.MaxResponseBodyBytes)
		if bodyErr != nil {
			return nil, bodyErr
		}
		return nil, fmt.Errorf("unexpected status %d: %s", resp.StatusCode, string(respBody))
	}
	result := new(LoginResponse)
	if err := json.NewDecoder(io.LimitReader(resp.Body, responseBodyLimit(c.MaxResponseBodyBytes))).Decode(result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}
