// Code generated by onek. DO NOT EDIT.
package api

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math"
	"net/http"
	"regexp"
	"strconv"
	"time"
)

func writeJSON(w http.ResponseWriter, status int, value any) {
	data, err := json.Marshal(value)
	if err != nil {
		writeJSONError(w, http.StatusInternalServerError, "internal server error")
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_, _ = w.Write(append(data, '\n'))
}

func writeJSONError(w http.ResponseWriter, status int, message string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(map[string]string{"message": message})
}

func requestBodyLimit(limit int64) int64 {
	if limit <= 0 {
		return 8 << 20
	}
	return limit
}

func parseInt32(s string) (int32, error) {
	v, err := strconv.ParseInt(s, 10, 32)
	if err != nil {
		return 0, errors.New("must be a 32-bit integer")
	}
	return int32(v), nil
}
func parseInt64(s string) (int64, error) {
	v, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		return 0, errors.New("must be an integer")
	}
	return v, nil
}
func parseUint32(s string) (uint32, error) {
	v, err := strconv.ParseUint(s, 10, 32)
	if err != nil {
		return 0, errors.New("must be a non-negative 32-bit integer")
	}
	return uint32(v), nil
}
func parseUint64(s string) (uint64, error) {
	v, err := strconv.ParseUint(s, 10, 64)
	if err != nil {
		return 0, errors.New("must be a non-negative integer")
	}
	return v, nil
}
func parseFloat32(s string) (float32, error) {
	v, err := strconv.ParseFloat(s, 32)
	if err != nil || math.IsNaN(v) || math.IsInf(v, 0) {
		return 0, fmt.Errorf("must be a finite number")
	}
	return float32(v), nil
}
func parseFloat64(s string) (float64, error) {
	v, err := strconv.ParseFloat(s, 64)
	if err != nil || math.IsNaN(v) || math.IsInf(v, 0) {
		return 0, fmt.Errorf("must be a finite number")
	}
	return v, nil
}
func parseBool(s string) (bool, error) {
	if s == "true" {
		return true, nil
	}
	if s == "false" {
		return false, nil
	}
	return false, fmt.Errorf("must be true or false")
}

func hasAuthScheme(value, scheme string) bool {
	if len(value) <= len(scheme)+1 || value[len(scheme)] != ' ' {
		return false
	}
	for i := 0; i < len(scheme); i++ {
		a, b := value[i], scheme[i]
		if a >= 'A' && a <= 'Z' {
			a += 'a' - 'A'
		}
		if b >= 'A' && b <= 'Z' {
			b += 'a' - 'A'
		}
		if a != b {
			return false
		}
	}
	return true
}

func validHeaderFormat(value, format string) bool {
	switch format {
	case "uuid":
		return validHeaderUUID.MatchString(value)
	case "email":
		return validHeaderEmail.MatchString(value)
	case "uri":
		return validHeaderURI.MatchString(value)
	default:
		return true
	}
}

var (
	validHeaderUUID  = regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`)
	validHeaderEmail = regexp.MustCompile(`^[^@\s]+@[^@\s]+\.[^@\s]+$`)
	validHeaderURI   = regexp.MustCompile(`^[a-zA-Z][a-zA-Z0-9+.-]*://[^\s]+$`)
)

// RequestMetadata identifies the generated route handling a request.
type RequestMetadata struct {
	Service     string
	Method      string
	HTTPMethod  string
	Route       string
	AuthSchemes []string
	Scopes      []string
	// Meta holds the route's @meta(key, value) pairs. The map is shared by
	// every request to the route: read it, do not modify it.
	Meta map[string]string
}

// MetaValue returns the route's @meta value for key, or "" when it has none.
func (m RequestMetadata) MetaValue(key string) string { return m.Meta[key] }

// ScopeError is returned by WithScopes when a caller lacks scopes the route
// declares with @requires. It renders as 403 with a public message.
type ScopeError struct{ Missing []string }

func (e *ScopeError) Error() string       { return e.PublicMessage() }
func (e *ScopeError) HTTPStatusCode() int { return http.StatusForbidden }
func (e *ScopeError) PublicMessage() string {
	message := "missing required scope"
	for i, scope := range e.Missing {
		if i == 0 {
			message += ": " + scope
		} else {
			message += ", " + scope
		}
	}
	return message
}

type requestMetadataContextKey struct{}
type requestIDContextKey struct{}

func RequestMetadataFromContext(ctx context.Context) (RequestMetadata, bool) {
	metadata, ok := ctx.Value(requestMetadataContextKey{}).(RequestMetadata)
	return metadata, ok
}

type httpRequestContextKey struct{}

func withHTTPRequest(r *http.Request) context.Context {
	return context.WithValue(r.Context(), httpRequestContextKey{}, r)
}

type responseControl struct {
	status int
	header http.Header
}

type responseControlKey struct{}

func SetResponseStatus(ctx context.Context, status int) {
	if control, ok := ctx.Value(responseControlKey{}).(*responseControl); ok && status >= 200 && status <= 299 {
		control.status = status
	}
}

func ResponseHeader(ctx context.Context) http.Header {
	if control, ok := ctx.Value(responseControlKey{}).(*responseControl); ok {
		return control.header
	}
	return http.Header{}
}

func HTTPRequestFromContext(ctx context.Context) (*http.Request, bool) {
	r, ok := ctx.Value(httpRequestContextKey{}).(*http.Request)
	return r, ok
}

func RequestIDFromContext(ctx context.Context) (string, bool) {
	requestID, ok := ctx.Value(requestIDContextKey{}).(string)
	return requestID, ok && requestID != ""
}

type Middleware func(http.Handler) http.Handler
type RequestIDGenerator func() string
type Authorizer func(context.Context, RequestMetadata, *http.Request) error
type RequestResult struct {
	StatusCode int
	Duration   time.Duration
}
type RequestObserver interface {
	RequestStarted(context.Context, RequestMetadata) context.Context
	RequestFinished(context.Context, RequestMetadata, RequestResult)
}

type ServerOption func(*serverOptions)

type serverOptions struct {
	mux                 *http.ServeMux
	middlewares         []Middleware
	requestIDHeader     string
	requestIDGenerator  RequestIDGenerator
	authorizer          Authorizer
	errorWriter         ErrorWriter
	observer            RequestObserver
	maxRequestBodyBytes int64
	sseHeartbeat        time.Duration
	sseHeartbeatSet     bool
}

// WithMux supports the options-first registration form.
func WithMux(mux *http.ServeMux) ServerOption { return func(o *serverOptions) { o.mux = mux } }

func WithMiddleware(middleware ...Middleware) ServerOption {
	return func(o *serverOptions) { o.middlewares = append(o.middlewares, middleware...) }
}

func WithRequestID(headerName string) ServerOption {
	return WithRequestIDGenerator(headerName, defaultRequestIDGenerator)
}
func WithRequestIDGenerator(headerName string, generate RequestIDGenerator) ServerOption {
	return func(o *serverOptions) {
		if headerName == "" {
			headerName = "X-Request-ID"
		}
		o.requestIDHeader, o.requestIDGenerator = headerName, generate
	}
}

func WithAuthorizer(authorizer Authorizer) ServerOption {
	return func(o *serverOptions) { o.authorizer = authorizer }
}

// WithScopes installs an authorizer that enforces @requires: granted returns the
// scopes the caller holds (return an error to reject the request, for example a
// 401), and any scope a route requires but the caller lacks produces a *ScopeError.
// It replaces a previous WithAuthorizer; to combine both, read RequestMetadata.Scopes
// inside your own Authorizer.
func WithScopes(granted func(context.Context, *http.Request) ([]string, error)) ServerOption {
	return WithAuthorizer(func(ctx context.Context, metadata RequestMetadata, r *http.Request) error {
		if len(metadata.Scopes) == 0 {
			return nil
		}
		have, err := granted(ctx, r)
		if err != nil {
			return err
		}
		held := make(map[string]bool, len(have))
		for _, scope := range have {
			held[scope] = true
		}
		var missing []string
		for _, scope := range metadata.Scopes {
			if !held[scope] {
				missing = append(missing, scope)
			}
		}
		if len(missing) > 0 {
			return &ScopeError{Missing: missing}
		}
		return nil
	})
}

// ServerError describes a failure the generated server is about to report.
// The default writer sends {"message": ...} (plus "violations" when there are
// any); install WithErrorWriter to send any other shape.
type ServerError struct {
	// Status is the HTTP status the server chose.
	Status int
	// Code is a stable machine-readable class: invalid_request_body,
	// request_body_too_large, invalid_path_parameter, invalid_query_parameter,
	// missing_header, invalid_header, invalid_credentials, validation_failed,
	// unauthorized, forbidden, not_found, method_not_allowed, internal, or the
	// snake_case name of the status for errors a handler returned.
	Code string
	// Message is the default human-readable message.
	Message string
	// Field names the path parameter, query parameter or header at fault.
	Field string
	// Violations lists the failed validation or authorization messages.
	Violations []string
	// Cause is the underlying error. It is never sent by the default writer.
	Cause error
}

// ErrorWriter writes a ServerError as the response. The request carries the
// request ID (RequestIDFromContext) and the route (RequestMetadataFromContext).
type ErrorWriter func(w http.ResponseWriter, r *http.Request, e *ServerError)

// WithErrorWriter replaces how the server reports its own errors: decoding,
// validation, parameters, headers, authorization, handler errors without a
// declared body, and the 404/405 answers wrapped by ErrorHandler. Errors a
// method declares with @status keep their declared body.
func WithErrorWriter(write ErrorWriter) ServerOption {
	return func(o *serverOptions) { o.errorWriter = write }
}

func (o serverOptions) fail(w http.ResponseWriter, r *http.Request, e *ServerError) {
	if o.errorWriter != nil {
		o.errorWriter(w, r, e)
		return
	}
	body := map[string]any{"message": e.Message}
	if len(e.Violations) > 0 {
		body["violations"] = e.Violations
	}
	writeJSON(w, e.Status, body)
}

func (o serverOptions) writeBodyError(w http.ResponseWriter, r *http.Request, err error) {
	var tooLarge *http.MaxBytesError
	if errors.As(err, &tooLarge) {
		o.fail(w, r, &ServerError{Status: http.StatusRequestEntityTooLarge, Code: "request_body_too_large", Message: "request body too large", Cause: err})
		return
	}
	o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "invalid_request_body", Message: "invalid request body", Cause: err})
}

func (o serverOptions) writeHandlerError(w http.ResponseWriter, r *http.Request, err error) {
	status := http.StatusInternalServerError
	var statusErr interface{ HTTPStatusCode() int }
	if errors.As(err, &statusErr) {
		if candidate := statusErr.HTTPStatusCode(); candidate >= 100 && candidate <= 599 {
			status = candidate
		}
	}
	message := "internal server error"
	var public interface{ PublicMessage() string }
	if errors.As(err, &public) && public.PublicMessage() != "" {
		message = public.PublicMessage()
	}
	code := statusCode(status)
	var coded interface{ PublicCode() string }
	if errors.As(err, &coded) && coded.PublicCode() != "" {
		code = coded.PublicCode()
	}
	o.fail(w, r, &ServerError{Status: status, Code: code, Message: message, Cause: err})
}

func statusCode(status int) string {
	if status == http.StatusInternalServerError {
		return "internal"
	}
	text := http.StatusText(status)
	out := make([]byte, 0, len(text))
	for i := 0; i < len(text); i++ {
		c := text[i]
		switch {
		case c >= 'A' && c <= 'Z':
			out = append(out, c+'a'-'A')
		case c >= 'a' && c <= 'z', c >= '0' && c <= '9':
			out = append(out, c)
		case len(out) > 0 && out[len(out)-1] != '_':
			out = append(out, '_')
		}
	}
	for len(out) > 0 && out[len(out)-1] == '_' {
		out = out[:len(out)-1]
	}
	if len(out) == 0 {
		return "error"
	}
	return string(out)
}

// ErrorHandler makes the router's own plain-text 404 and 405 answers use the
// same error writer as the generated routes. Wrap the mux you serve:
//
//	http.ListenAndServe(addr, ErrorHandler(mux, WithErrorWriter(write)))
//
// Only text/plain 404 and 405 responses are converted, so a handler that
// answers with its own JSON or HTML 404 is left alone.
func ErrorHandler(next http.Handler, opts ...ServerOption) http.Handler {
	var o serverOptions
	for _, opt := range opts {
		opt(&o)
	}
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		next.ServeHTTP(&routerErrorWriter{ResponseWriter: w, o: o, r: r}, r)
	})
}

type routerErrorWriter struct {
	http.ResponseWriter
	o         serverOptions
	r         *http.Request
	wrote     bool
	swallowed bool
}

func (w *routerErrorWriter) WriteHeader(status int) {
	if w.wrote {
		return
	}
	w.wrote = true
	contentType := w.Header().Get("Content-Type")
	if (status == http.StatusNotFound || status == http.StatusMethodNotAllowed) && len(contentType) >= 10 && contentType[:10] == "text/plain" {
		w.swallowed = true
		header := w.Header()
		header.Del("Content-Type")
		header.Del("Content-Length")
		header.Del("X-Content-Type-Options")
		code, message := "not_found", "not found"
		if status == http.StatusMethodNotAllowed {
			code, message = "method_not_allowed", "method not allowed"
		}
		w.o.fail(w.ResponseWriter, w.r, &ServerError{Status: status, Code: code, Message: message})
		return
	}
	w.ResponseWriter.WriteHeader(status)
}

func (w *routerErrorWriter) Write(data []byte) (int, error) {
	if !w.wrote {
		w.WriteHeader(http.StatusOK)
	}
	if w.swallowed {
		return len(data), nil
	}
	return w.ResponseWriter.Write(data)
}

func (w *routerErrorWriter) Unwrap() http.ResponseWriter { return w.ResponseWriter }

func (w *routerErrorWriter) Flush() {
	if flusher, ok := w.ResponseWriter.(http.Flusher); ok && !w.swallowed {
		flusher.Flush()
	}
}

func WithRequestObserver(observer RequestObserver) ServerOption {
	return func(o *serverOptions) { o.observer = observer }
}
func WithMaxRequestBodyBytes(limit int64) ServerOption {
	return func(o *serverOptions) { o.maxRequestBodyBytes = limit }
}
func WithSSEHeartbeat(interval time.Duration) ServerOption {
	return func(o *serverOptions) { o.sseHeartbeat, o.sseHeartbeatSet = interval, true }
}

func defaultRequestIDGenerator() string {
	var value [16]byte
	if _, err := rand.Read(value[:]); err != nil {
		return ""
	}
	return hex.EncodeToString(value[:])
}

func (o serverOptions) wrapHandler(handler http.Handler, metadata RequestMetadata) http.Handler {
	if o.authorizer != nil {
		next := handler
		handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if err := o.authorizer(r.Context(), metadata, r); err != nil {
				var statusErr interface{ HTTPStatusCode() int }
				if errors.As(err, &statusErr) {
					o.writeHandlerError(w, r, err)
				} else {
					o.fail(w, r, &ServerError{Status: http.StatusUnauthorized, Code: "unauthorized", Message: "unauthorized", Cause: err})
				}
				return
			}
			next.ServeHTTP(w, r)
		})
	}
	for i := len(o.middlewares) - 1; i >= 0; i-- {
		if o.middlewares[i] != nil {
			handler = o.middlewares[i](handler)
		}
	}
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := context.WithValue(r.Context(), requestMetadataContextKey{}, metadata)
		if o.requestIDHeader != "" {
			requestID := r.Header.Get(o.requestIDHeader)
			if requestID == "" && o.requestIDGenerator != nil {
				requestID = o.requestIDGenerator()
			}
			if requestID != "" {
				w.Header().Set(o.requestIDHeader, requestID)
				ctx = context.WithValue(ctx, requestIDContextKey{}, requestID)
			}
		}
		if o.observer == nil {
			handler.ServeHTTP(w, r.WithContext(ctx))
			return
		}
		started := time.Now()
		ctx = o.observer.RequestStarted(ctx, metadata)
		rw := &statusResponseWriter{ResponseWriter: w, statusCode: http.StatusOK}
		defer func() {
			o.observer.RequestFinished(ctx, metadata, RequestResult{StatusCode: rw.statusCode, Duration: time.Since(started)})
		}()
		handler.ServeHTTP(rw, r.WithContext(ctx))
	})
}

type statusResponseWriter struct {
	http.ResponseWriter
	statusCode  int
	wroteHeader bool
}

func (w *statusResponseWriter) WriteHeader(statusCode int) {
	if w.wroteHeader {
		return
	}
	w.wroteHeader = true
	w.statusCode = statusCode
	w.ResponseWriter.WriteHeader(statusCode)
}
func (w *statusResponseWriter) Write(data []byte) (int, error) {
	if !w.wroteHeader {
		w.WriteHeader(http.StatusOK)
	}
	return w.ResponseWriter.Write(data)
}
func (w *statusResponseWriter) Unwrap() http.ResponseWriter { return w.ResponseWriter }
func (w *statusResponseWriter) Flush() {
	if flusher, ok := w.ResponseWriter.(http.Flusher); ok {
		flusher.Flush()
	}
}

// UserService manages users in the system.
type UserServiceServer interface {
	// Create a new user.
	CreateUser(ctx context.Context, req *CreateUserRequest) (*User, error)
	// Get a user by ID.
	GetUser(ctx context.Context, req *GetUserRequest) (*User, error)
	// Login with different authentication methods.
	Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error)
}

func RegisterUserServiceServer(first any, rest ...any) error {
	var o serverOptions
	var srv UserServiceServer
	if mux, ok := first.(*http.ServeMux); ok {
		o.mux = mux
		if len(rest) == 0 {
			return fmt.Errorf("RegisterUserServiceServer: implementation is required")
		}
		var ok bool
		srv, ok = rest[0].(UserServiceServer)
		if !ok {
			return fmt.Errorf("RegisterUserServiceServer: invalid implementation")
		}
		rest = rest[1:]
	} else {
		var ok bool
		srv, ok = first.(UserServiceServer)
		if !ok {
			return fmt.Errorf("RegisterUserServiceServer: invalid implementation")
		}
	}
	for _, value := range rest {
		opt, ok := value.(ServerOption)
		if !ok {
			return fmt.Errorf("RegisterUserServiceServer: options must be ServerOption values")
		}
		opt(&o)
	}
	if o.mux == nil {
		return fmt.Errorf("RegisterUserServiceServer: mux is required")
	}
	mux := o.mux
	mux.Handle("POST /api/v1/users", o.wrapHandler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		req := new(CreateUserRequest)
		if r.Body != nil {
			r.Body = http.MaxBytesReader(w, r.Body, requestBodyLimit(o.maxRequestBodyBytes))
			if err := json.NewDecoder(r.Body).Decode(req); err != nil && !errors.Is(err, io.EOF) {
				o.writeBodyError(w, r, err)
				return
			}
		}
		{
			value := r.Header.Get("X-API-Key")
			if value == "" {
				o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "missing_header", Field: "X-API-Key", Message: "missing required header: X-API-Key"})
				return
			}
			if value != "" && !validHeaderFormat(value, "uuid") {
				o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "invalid_header", Field: "X-API-Key", Message: "invalid header X-API-Key: expected uuid"})
				return
			}
		}
		if v, ok := any(req).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				var list interface{ ViolationList() []string }
				if errors.As(err, &list) {
					o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "validation_failed", Message: err.Error(), Violations: list.ViolationList(), Cause: err})
					return
				}
				o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "validation_failed", Message: err.Error(), Cause: err})
				return
			}
		}
		control := &responseControl{status: http.StatusOK, header: w.Header()}
		resp, err := srv.CreateUser(context.WithValue(withHTTPRequest(r), responseControlKey{}, control), req)
		if err != nil {
			o.writeHandlerError(w, r, err)
			return
		}
		writeJSON(w, control.status, resp)
	}), RequestMetadata{Service: "UserService", Method: "createUser", HTTPMethod: "POST", Route: "/api/v1/users", AuthSchemes: nil, Scopes: nil, Meta: nil}))
	mux.Handle("POST /api/v1/users/get", o.wrapHandler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		req := new(GetUserRequest)
		if r.Body != nil {
			r.Body = http.MaxBytesReader(w, r.Body, requestBodyLimit(o.maxRequestBodyBytes))
			if err := json.NewDecoder(r.Body).Decode(req); err != nil && !errors.Is(err, io.EOF) {
				o.writeBodyError(w, r, err)
				return
			}
		}
		{
			value := r.Header.Get("X-API-Key")
			if value == "" {
				o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "missing_header", Field: "X-API-Key", Message: "missing required header: X-API-Key"})
				return
			}
			if value != "" && !validHeaderFormat(value, "uuid") {
				o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "invalid_header", Field: "X-API-Key", Message: "invalid header X-API-Key: expected uuid"})
				return
			}
		}
		if v, ok := any(req).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				var list interface{ ViolationList() []string }
				if errors.As(err, &list) {
					o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "validation_failed", Message: err.Error(), Violations: list.ViolationList(), Cause: err})
					return
				}
				o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "validation_failed", Message: err.Error(), Cause: err})
				return
			}
		}
		control := &responseControl{status: http.StatusOK, header: w.Header()}
		resp, err := srv.GetUser(context.WithValue(withHTTPRequest(r), responseControlKey{}, control), req)
		if err != nil {
			o.writeHandlerError(w, r, err)
			return
		}
		writeJSON(w, control.status, resp)
	}), RequestMetadata{Service: "UserService", Method: "getUser", HTTPMethod: "POST", Route: "/api/v1/users/get", AuthSchemes: nil, Scopes: nil, Meta: nil}))
	mux.Handle("POST /api/v1/auth/login", o.wrapHandler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		req := new(LoginRequest)
		if r.Body != nil {
			r.Body = http.MaxBytesReader(w, r.Body, requestBodyLimit(o.maxRequestBodyBytes))
			if err := json.NewDecoder(r.Body).Decode(req); err != nil && !errors.Is(err, io.EOF) {
				o.writeBodyError(w, r, err)
				return
			}
		}
		{
			value := r.Header.Get("X-API-Key")
			if value == "" {
				o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "missing_header", Field: "X-API-Key", Message: "missing required header: X-API-Key"})
				return
			}
			if value != "" && !validHeaderFormat(value, "uuid") {
				o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "invalid_header", Field: "X-API-Key", Message: "invalid header X-API-Key: expected uuid"})
				return
			}
		}
		{
			value := r.Header.Get("X-Request-Id")
			if value == "" {
				o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "missing_header", Field: "X-Request-Id", Message: "missing required header: X-Request-Id"})
				return
			}
			if value != "" && !validHeaderFormat(value, "uuid") {
				o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "invalid_header", Field: "X-Request-Id", Message: "invalid header X-Request-Id: expected uuid"})
				return
			}
		}
		if v, ok := any(req).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				var list interface{ ViolationList() []string }
				if errors.As(err, &list) {
					o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "validation_failed", Message: err.Error(), Violations: list.ViolationList(), Cause: err})
					return
				}
				o.fail(w, r, &ServerError{Status: http.StatusBadRequest, Code: "validation_failed", Message: err.Error(), Cause: err})
				return
			}
		}
		control := &responseControl{status: http.StatusOK, header: w.Header()}
		resp, err := srv.Login(context.WithValue(withHTTPRequest(r), responseControlKey{}, control), req)
		if err != nil {
			o.writeHandlerError(w, r, err)
			return
		}
		writeJSON(w, control.status, resp)
	}), RequestMetadata{Service: "UserService", Method: "login", HTTPMethod: "POST", Route: "/api/v1/auth/login", AuthSchemes: nil, Scopes: nil, Meta: nil}))
	return nil
}
