// Code generated by onek. DO NOT EDIT.
package api

import (
	"regexp"
	"strings"
	"unicode/utf8"
)

var emailPattern = regexp.MustCompile(`^[^@\s]+@[^@\s]+\.[^@\s]+$`)
var uuidPattern = regexp.MustCompile(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$`)

func inSet(v string, allowed ...string) bool {
	for _, a := range allowed {
		if v == a {
			return true
		}
	}
	return false
}

type ValidationErrors struct {
	Violations []string
}

func (e *ValidationErrors) Error() string { return strings.Join(e.Violations, "; ") }

func (e *ValidationErrors) ViolationList() []string { return e.Violations }

func (m *User) Validate() error {
	if m == nil {
		return nil
	}
	var violations []string
	if m.Id != "" && !uuidPattern.MatchString(m.Id) {
		violations = append(violations, "id must be a valid uuid")
	}
	if n := utf8.RuneCountInString(m.Name); n < 1 || n > 100 {
		violations = append(violations, "name must be between 1 and 100 characters")
	}
	if m.Email != "" && !emailPattern.MatchString(m.Email) {
		violations = append(violations, "email must be a valid email")
	}
	if len(violations) > 0 {
		return &ValidationErrors{Violations: violations}
	}
	return nil
}

func (m *CreateUserRequest) Validate() error {
	if m == nil {
		return nil
	}
	var violations []string
	if n := utf8.RuneCountInString(m.Name); n < 2 || n > 100 {
		violations = append(violations, "name must be between 2 and 100 characters")
	}
	if m.Email != "" && !emailPattern.MatchString(m.Email) {
		violations = append(violations, "email must be a valid email")
	}
	if len(violations) > 0 {
		return &ValidationErrors{Violations: violations}
	}
	return nil
}

func (m *GetUserRequest) Validate() error {
	if m == nil {
		return nil
	}
	var violations []string
	if m.Id != "" && !uuidPattern.MatchString(m.Id) {
		violations = append(violations, "id must be a valid uuid")
	}
	if len(violations) > 0 {
		return &ValidationErrors{Violations: violations}
	}
	return nil
}

func (m *EmailAuth) Validate() error {
	if m == nil {
		return nil
	}
	var violations []string
	if m.Email != "" && !emailPattern.MatchString(m.Email) {
		violations = append(violations, "email must be a valid email")
	}
	if n := utf8.RuneCountInString(m.Password); n < 8 || n > 72 {
		violations = append(violations, "password must be between 8 and 72 characters")
	}
	if len(violations) > 0 {
		return &ValidationErrors{Violations: violations}
	}
	return nil
}

func (m *TokenAuth) Validate() error {
	if m == nil {
		return nil
	}
	var violations []string
	if n := utf8.RuneCountInString(m.Token); n < 10 || n > 256 {
		violations = append(violations, "token must be between 10 and 256 characters")
	}
	if len(violations) > 0 {
		return &ValidationErrors{Violations: violations}
	}
	return nil
}

func (m *SocialAuth) Validate() error {
	if m == nil {
		return nil
	}
	var violations []string
	if !inSet(m.Provider, "google", "github", "facebook", "apple") {
		violations = append(violations, "provider must be one of the allowed values")
	}
	if n := utf8.RuneCountInString(m.AccessToken); n < 20 || n > 512 {
		violations = append(violations, "access_token must be between 20 and 512 characters")
	}
	if len(violations) > 0 {
		return &ValidationErrors{Violations: violations}
	}
	return nil
}

func (m *LoginRequest) Validate() error {
	if m == nil {
		return nil
	}
	var violations []string
	switch v := m.AuthMethod.(type) {
	case *LoginRequestAuthMethodEmail:
		if v.Email != nil {
			if err := v.Email.Validate(); err != nil {
				violations = append(violations, "auth_method.email: "+err.Error())
			}
		}
	case *LoginRequestAuthMethodToken:
		if v.Token != nil {
			if err := v.Token.Validate(); err != nil {
				violations = append(violations, "auth_method.token: "+err.Error())
			}
		}
	case *LoginRequestAuthMethodSocial:
		if v.Social != nil {
			if err := v.Social.Validate(); err != nil {
				violations = append(violations, "auth_method.social: "+err.Error())
			}
		}
	}
	if len(violations) > 0 {
		return &ValidationErrors{Violations: violations}
	}
	return nil
}

func (m *LoginResponse) Validate() error {
	if m == nil {
		return nil
	}
	var violations []string
	if m.User != nil {
		if err := m.User.Validate(); err != nil {
			violations = append(violations, "user: "+err.Error())
		}
	}
	if len(violations) > 0 {
		return &ValidationErrors{Violations: violations}
	}
	return nil
}
