package genswift

import (
	"strings"

	"github.com/1homsi/onekit/internal/onkir"
)

const swiftNil = "nil"

const availability = "@available(macOS 12.0, iOS 15.0, tvOS 15.0, watchOS 8.0, *)"

func GenerateClient(file *onkir.File) []byte {
	return GenerateClientInNamespace(file, "", nil)
}

func GenerateClientInNamespace(file *onkir.File, namespace string, resolver PackageResolver) []byte {
	if !hasHTTPMethods(file) {
		return nil
	}
	p := newPrinter(resolver)
	p.P("// Code generated by onek. DO NOT EDIT.")
	p.P()
	p.P("import Foundation")
	p.P("#if canImport(FoundationNetworking)")
	p.P("import FoundationNetworking")
	p.P("#endif")
	p.P()
	if namespace != "" {
		p.P("extension ", namespace, " {")
		p.Indent()
	}
	for _, s := range file.Services {
		if serviceHasHTTP(s) {
			writeClientClass(p, s)
		}
	}
	if namespace != "" {
		p.Dedent()
		p.P("}")
	}
	return p.Bytes()
}

func hasHTTPMethods(file *onkir.File) bool {
	for _, s := range file.Services {
		if serviceHasHTTP(s) {
			return true
		}
	}
	return false
}

func serviceHasHTTP(s *onkir.Service) bool {
	for _, m := range s.Methods {
		if !m.IsWebSocket() {
			return true
		}
	}
	return false
}

func writeClientClass(p *Printer, s *onkir.Service) {
	name := s.Name + "Client"
	writeDoc(p, s.Doc)
	p.P(availability)
	p.P("public final class ", name, ": Sendable {")
	p.Indent()
	p.P("public let baseURL: String")
	p.P("public let headers: [String: String]")
	p.P("public let timeout: TimeInterval?")
	p.P("public let maxResponseBodyBytes: Int")
	p.P("public let maxSSELineBytes: Int")
	p.P("private let session: URLSession")
	p.P()
	p.P("public init(")
	p.Indent()
	p.P("_ baseURL: String,")
	p.P("session: URLSession = .shared,")
	p.P("headers: [String: String] = [:],")
	p.P("timeout: TimeInterval? = onekitDefaultRequestTimeout,")
	p.P("maxResponseBodyBytes: Int = onekitDefaultMaxResponseBodyBytes,")
	p.P("maxSSELineBytes: Int = onekitDefaultMaxSSELineBytes")
	p.Dedent()
	p.P(") {")
	p.Indent()
	p.P("self.baseURL = onekitTrimSlash(baseURL)")
	p.P("self.session = session")
	p.P("self.headers = headers")
	p.P("self.timeout = timeout")
	p.P("self.maxResponseBodyBytes = maxResponseBodyBytes")
	p.P("self.maxSSELineBytes = maxSSELineBytes")
	p.Dedent()
	p.P("}")
	p.P()
	for _, m := range s.Methods {
		switch {
		case m.IsWebSocket():
			continue
		case m.IsStream():
			writeSSEClientMethod(p, s, m)
		default:
			writeClientMethod(p, s, m)
		}
	}
	p.Dedent()
	p.P("}")
	p.P()
}

func writeMethodHeader(p *Printer, m *onkir.Method) {
	writeDoc(p, m.Doc)
	writeDeprecated(p, m.Deprecated)
}

func writePathAndQuery(p *Printer, route string, req *onkir.Message, withQuery bool) {
	params := onkir.PathParamNames(route)
	hasParam := false
	for _, name := range params {
		if onkir.FindField(req, name) != nil {
			hasParam = true
		}
	}
	if hasParam {
		p.P("var path = ", swiftString(route))
	} else {
		p.P("let path = ", swiftString(route))
	}
	for _, name := range params {
		field := onkir.FindField(req, name)
		if field == nil {
			continue
		}
		p.P("path = path.replacingOccurrences(of: ", swiftString(onkir.PathPlaceholder(route, name)), ", with: ", pathValueFunc(route, name), "(req.", Ident(field.Name), "))")
	}
	var lines []func()
	if withQuery {
		for _, field := range req.Fields {
			d, ok := field.Decorator("query")
			if !ok || field.Type == nil || field.Type.Kind != onkir.KindScalar {
				continue
			}
			queryName, _ := d.Value()
			if queryName == "" {
				queryName = field.Name
			}
			id := "req." + Ident(field.Name)
			key := swiftString(queryName)
			switch {
			case field.Repeated:
				lines = append(lines, func() {
					p.P("for value in ", id, " { query.append((", key, ", onekitQueryValue(value))) }")
				})
			case isNullableKind(field):
				lines = append(lines, func() {
					p.P("if let value = ", id, " { query.append((", key, ", onekitQueryValue(value))) }")
				})
			default:
				lines = append(lines, func() {
					p.P("query.append((", key, ", onekitQueryValue(", id, ")))")
				})
			}
		}
	}
	if len(lines) == 0 {
		p.P("let query: [(String, String)] = []")
		return
	}
	p.P("var query: [(String, String)] = []")
	for _, emit := range lines {
		emit()
	}
}

func writeTypedErrors(p *Printer, m *onkir.Method, status, body string) {
	for _, errType := range m.ErrorTypes {
		code := 500
		if c, ok := errType.StatusCode(); ok {
			code = c
		}
		p.P("if ", status, " == ", code, ", let payload = onekitTryJSON(", body, ") as? [String: Any] { throw try ", p.messageRef(errType), "(json: payload) }")
	}
}

func writeTypedErrorClosure(p *Printer, m *onkir.Method) {
	p.P("typedError: { status, body in")
	p.Indent()
	for _, errType := range m.ErrorTypes {
		code := 500
		if c, ok := errType.StatusCode(); ok {
			code = c
		}
		p.P("if status == ", code, ", let payload = onekitTryJSON(body) as? [String: Any], let error = try? ", p.messageRef(errType), "(json: payload) { return error }")
	}
	p.P("return nil")
	p.Dedent()
	p.P("},")
}

func bodyExpr(m *onkir.Method) string {
	bodyField, ok := m.BodyField()
	if !ok {
		return "req.toJSONValue()"
	}
	field := onkir.FindField(m.Request, bodyField)
	if field == nil {
		return "((req.toJSONValue() as? [String: Any])?[" + swiftString(bodyField) + "] ?? NSNull())"
	}
	id := "req." + Ident(field.Name)
	if field.Oneof != nil {
		return "(" + id + ".map { value -> Any in value.toJSON() } ?? NSNull())"
	}
	if isNullableKind(field) {
		return "(" + id + ".map { value -> Any in " + encodeValue(field.Type, field, "value", false) + " } ?? NSNull())"
	}
	return "(" + fieldWireValue(field, id) + " as Any)"
}

func writeRequestBuild(p *Printer, s *onkir.Service, m *onkir.Method, bodyBearing, stream bool) {
	verb, _ := m.Verb()
	route, _ := m.Path()
	p.P("try onekitCheck(req.validate())")
	writePathAndQuery(p, s.BasePath+route, m.Request, !bodyBearing)
	timeoutExpr := "onekitTimeout(self.timeout, timeout)"
	if stream {
		timeoutExpr = swiftNil
	}
	mutable := "let"
	if bodyBearing || stream {
		mutable = "var"
	}
	p.P(mutable, " request = try onekitRequest(method: ", swiftString(strings.ToUpper(verb)), ", baseURL: self.baseURL, path: path, query: query, headers: onekitMerge(self.headers, headers), timeout: ", timeoutExpr, ")")
	if bodyBearing {
		p.P("request.setValue(\"application/json\", forHTTPHeaderField: \"Content-Type\")")
		p.P("request.httpBody = try onekitJSONData(", bodyExpr(m), ")")
	}
	if stream {
		p.P("request.setValue(\"text/event-stream\", forHTTPHeaderField: \"Accept\")")
	}
}

func writeClientMethod(p *Printer, s *onkir.Service, m *onkir.Method) {
	verb, _ := m.Verb()
	bodyBearing := onkir.IsBodyBearingVerb(verb)
	writeMethodHeader(p, m)
	p.P("public func ", MethodIdent(m.Name), "(_ req: ", p.messageRef(m.Request), ", headers: [String: String] = [:], timeout: TimeInterval? = nil) async throws -> ", p.messageRef(m.Response), " {")
	p.Indent()
	writeRequestBuild(p, s, m, bodyBearing, false)
	p.P("let response = try await onekitSend(session, request, maxBodyBytes: maxResponseBodyBytes)")
	p.P("if response.ok { return try ", p.messageRef(m.Response), "(json: try onekitDecodeBody(response.body)) }")
	writeTypedErrors(p, m, "response.status", "response.body")
	p.P("throw OnekitError.unexpectedStatus(status: response.status, body: response.body, headers: response.headers)")
	p.Dedent()
	p.P("}")
	p.P()
}

func writeSSEClientMethod(p *Printer, s *onkir.Service, m *onkir.Method) {
	writeMethodHeader(p, m)
	p.P("public func ", MethodIdent(m.Name), "(_ req: ", p.messageRef(m.Request), ", headers: [String: String] = [:]) -> AsyncThrowingStream<", p.messageRef(m.Response), ", Error> {")
	p.Indent()
	p.P("onekitStream(")
	p.Indent()
	p.P("session: session,")
	p.P("maxResponseBodyBytes: maxResponseBodyBytes,")
	p.P("maxSSELineBytes: maxSSELineBytes,")
	p.P("request: {")
	p.Indent()
	writeRequestBuild(p, s, m, false, true)
	p.P("return request")
	p.Dedent()
	p.P("},")
	writeTypedErrorClosure(p, m)
	p.P("decode: { try ", p.messageRef(m.Response), "(json: $0) }")
	p.Dedent()
	p.P(")")
	p.Dedent()
	p.P("}")
	p.P()
}

func pathValueFunc(route, name string) string {
	if onkir.IsWildcardParam(route, name) {
		return "onekitPathWildcard"
	}
	return "onekitPathValue"
}
